### ISSUE TITLE
Using bcache in the advanced partitioner during install results in unbootable system

### ISSUE THREAD

**Issue by pauldoo** [ublue-os/bluefin#1004]
The bluefin installer lets me install to a fileystem ontop of bcache when I use the advanced partitioning UI (not to be confused with bcachefs).  However the base image doesn't contain the "bcache-tools" package, so the system doesn't boot correctly after doing this.  If it matters, I'm attempting to put "/home" on a bcache backed filesystem, not the root fs.

A workaround is to install to a non-bcache backed filesystem, then do "rpm-ostree install bcache-tools", then manually futz with filesystems and partitions to put things into the desired locations.

**Comment by castrojo** [comment]
Did everything work after you installed the package?

**Comment by pauldoo** [comment]
Yep - perfectly.  My cursed btrfs on LUKS on bcache on LVM home filesystem is working like a charm after the workaround.  I'm on bluefin gts if it matters.

**Comment by castrojo** [comment]
@noelmiller this would be something we add to the ISO generator repo right? So that bcache-tools can be on there? (Adding it to bluefin isn't a problem)

**Comment by pauldoo** [comment]
Right..  the advanced installer already could work with bcache.  It let me work with the pre existing btrfs filesystem and LUKS volume that sat ontop of bcache.

It was only on reboot after install that things failed.  As you say - bcache-tools is needed on the installed system.

**Comment by pauldoo** [comment]
Thank you for fixing this so promptly!  There can't be many users using bcache with bluefin,  but you fixed it anyway.

How do I tell when my laptop has applied the update and it's safe for me to remove my overlay?

**Comment by castrojo** [comment]
It's 57k so too easy. 😄 

Updating today will do it, then you can remove it.
