### ISSUE TITLE
feat: Add a dictionary

### ISSUE THREAD

**Issue by bketelsen** [ublue-os/bluefin#1006]
### Describe the bug

Too many terms for people new to bluefin/silverblue/fedora

### What did you expect to happen?

we should make it easy for people to learn by adding a `ujust terms` command and putting it in the MOTD`. Use glow, make it pretty.

**Comment by RealVishy** [comment]
I wanna implement this, is this the right file for adding it to ujust?

https://github.com/ublue-os/bluefin/blob/main/just/bluefin-system.just

Also unsure of where to put the markdown for the terms command. Is there a specific place to use?

**Comment by castrojo** [comment]
No one's picked it up so closing
