### ISSUE TITLE
ujust update "ERROR Failed to deserialize /usr/share/ublue-os/topgrade.toml: TOML parse error"

### ISSUE THREAD

**Issue by MrQvest** [ublue-os/bluefin#1011]
### Describe the bug

When running `ujust update` from Ptyxis, the following error appears:

> ERROR Failed to deserialize /usr/share/ublue-os/topgrade.toml: TOML parse error at line 4, column 80
  |
4 | ignore_failures = ["distrobox", "flatpak", "brew_cask", "brew_formula", "nix", "npm", "pip3", "home_manager", "firmware"]
  |                                                                                ^^^^^
unknown variant `npm`, expected one of `a_m`, `app_man`, `asdf`, `atom`, `audit`, `bin`, `bob`, `brew_cask`, `brew_formula`, `bun`, `bun_packages`, `cargo`, `chezmoi`, `chocolatey`, `choosenim`, `composer`, `conda`, `config_update`, `containers`, `custom_commands`, `deb_get`, `deno`, `distrobox`, `dkp_pacman`, `dotnet`, `emacs`, `firmware`, `flatpak`, `flutter`, `fossil`, `gcloud`, `gem`, `ghcup`, `github_cli_extensions`, `git_repos`, `gnome_shell_extensions`, `go`, `guix`, `haxelib`, `helm`, `home_manager`, `jetpack`, `julia`, `juliaup`, `kakoune`, `helix`, `krew`, `lure`, `macports`, `mamba`, `miktex`, `mas`, `maza`, `micro`, `myrepos`, `nix`, `node`, `opam`, `pacdef`, `pacstall`, `pearl`, `pip3`, `pip_review`, `pip_review_local`, `pipupgrade`, `pipx`, `pkg`, `pkgin`, `pnpm`, `powershell`, `protonup`, `raco`, `rcm`, `remotes`, `restarts`, `rtcl`, `ruby_gems`, `rustup`, `scoop`, `sdkman`, `self_update`, `sheldon`, `shell`, `snap`, `sparkle`, `spicetify`, `stack`, `stew`, `system`, `tldr`, `tlmgr`, `tmux`, `toolbx`, `vagrant`, `vcpkg`, `vim`, `vscode`, `winget`, `wsl`, `wsl_update`, `yadm`, `yarn`

However, the update operation works and everything it needs and tries to do is done

### What did you expect to happen?

No error output

### Output of `rpm-ostree status`

```shell
> rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/mrqvest/my-ublue:latest
                   Digest: sha256:ef934d4928821fd8d0637a465b40dd15df8279ef157b79ed729ef734d4914d56
                  Version: 39.20240303.0 (2024-03-05T01:43:14Z)

  ostree-image-signed:docker://ghcr.io/mrqvest/my-ublue:latest
                   Digest: sha256:aab02e44d567cc8cbdd23abc633e1edece0620a6b27b05cd5b7427610a870e64
                  Version: 39.20240303.0 (2024-03-04T17:16:20Z)
```

### Extra information or context

The image in rpm-ostree status is a blue-build image with bluefin-nvidia:latest as a base. All that is different is 2 overriden removed packages and 1 extra package (icon theme). Everything else is stock bluefin

**Comment by p5** [comment]
Yep - Jorge released a fix 12 hours ago, so should be back to normal if you upgrade
https://github.com/ublue-os/bluefin/commit/23ea820ae02093ffe432a604f9c172e5074dbeb1

**Comment by MrQvest** [comment]
Can confirm it is fixed now!
