### ISSUE TITLE
Add gcc-c++ to the base layer

### ISSUE THREAD

**Issue by spa5k** [ublue-os/bluefin#1018]
### Describe the package

I'd like to request the package `gcc-c++` because it's required by the tree sitter etc. for nvim.

### Image

All Images

**Comment by castrojo** [comment]
We're only going to be removing devtools from the image, not adding more, sorry. neovim and treesitter seem to install and run fine via brew, am I missing something?

**Comment by spa5k** [comment]
Yeah it was something that was related to lazyvim, did a clean install separately, and it worked. Closing this issue.
