### ISSUE TITLE
Add a list of youtube videos as a video changelog

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1028]
From chat:

> I wonder if we could embed a youtube video at the end of yafti. Like if we had a tour video. Don't autoplay it anything, but like, let the user just have a video tour as part of the first run

> and the bazzite one is totally a fanmade tutorial in the style of TF2's animated intros. It'd be sick.

> And maybe the play is it's a playlist of videos from content providers so they have a bunch to choose from while they wait for the installation of something to finish. And we just link to it from the motd so they have a "bookmark" of them. And then we just keep them up to date. It'd be like a video changelog made by the content community.

See for example, @Aru 's video from today on the legion go:
https://www.youtube.com/watch?v=q3Mnhygm64A

![image](https://github.com/ublue-os/bluefin/assets/1264109/ef16ad3c-2fb7-4a8a-bfba-a4032c57a11e)

Basically we make this a part of `ujust changelogs` or `ujust votd` or whatever and each of those is a link to a youtube video that would open in your browser. Could we just crib the same thing that motd is doing and we put one url per line and then as part of the build step it snags the title, content creator, short description and pipes it through `glow`. Then we have an motd and votd directory next to each other and that'll be two ways we can reach users. 

cc @KyleGospo since I'm sure bazzite will take full advantage of this since the content already exists. 😄

**Comment by Aman9das** [comment]
Request for changelog rss feed too

**Comment by castrojo** [comment]
Yeah! That's filed here: https://github.com/ublue-os/config/issues/104
