### ISSUE TITLE
XBox Controller calling for remote access

### ISSUE THREAD

**Issue by BGray210** [ublue-os/bluefin#1033]
### Describe the bug

I installed Bluefin-dx-nvidia fresh yesterday, began setting it up with my apps, rebased to Kinoite-nvidia thinking it was the same - it is not (no ujust, no right click and start app with nvidia card, no brew) so I rebased back to dx-nvidia again. I had signed into Gnome desktop in dx to begin with, accessed KDE remote on phone while on Kinoite, now on dx again and anytime I plug in my controller and try to use it in any game it calls for the remote access request pop-up and isn't recognized as a controller anymore.
I have re-downloaded over 200GB of Steam games once again and really don't want to start from scratch if I don't have to, but if someone can reach out to let me know what I did wrong or point me in the direction to fix this?

### What did you expect to happen?

I expected my XBox controller to work as it had before rebasing back to dx

### Output of `rpm-ostree status`

```shell
brandongray@DESKTOP-IF88SAK ~> rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:e4b2978f8b39252612251eda480a9188d03606bbd98e295b6aa4a5955d6605a6
                  Version: 39.20240317.0 (2024-03-17T16:51:47Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:99821bd45bfecef16682d46fec95914bc6fbdad4d5222bc76e70285f44f4336e
                  Version: 39.20240316.0 (2024-03-16T16:52:27Z)
```

### Extra information or context

I love everything about the nvidia-dx edition but would really like a kinoite-dx edition. I have pulled the distro to my github to try and figure out if I can make those changes myself

**Comment by noelmiller** [comment]
If you like Kinoite and the benefits of Bluefin-DX, check out: https://github.com/NiHaiden/aurora

It is a fork of Bluefin that uses KDE. In regards to the issues you are having, it is not recommended to rebase between Gnome and KDE. You will run into issues like you are currently. 

My suggestion would be to start fresh with Aurora or Bluefin-DX, depending upon your preference of DE.

**Comment by m2Giles** [comment]
We now have Aurora built inside this repo for those who prefer kde.

If you switched to kde are you still running into this issue?
