### ISSUE TITLE
A package installed from brew can't locate its dependencies

### ISSUE THREAD

**Issue by mapringg** [ublue-os/bluefin#1035]
### Describe the bug

- ujust brew
- brew install stow
- stow --version

Instead this is the error I got :
`Can't locate lib.pm in @INC (you may need to install the lib module) (@INC entries checked: /usr/local/lib64/perl5/5.38 /usr/local/share/perl5/5.38 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/linuxbrew/.linuxbrew/bin/stow line 462.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/stow line 462.`

### What did you expect to happen?

I expected to see the version of the stow package.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 17min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:d926ea236354a21020716b1ae4461a91533f37cce4741f22a6f71663bfc35ca9
                  Version: 39.20240319.0 (2024-03-19T16:56:24Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:029a6a0e16d3becf5a2a509e829da95bc5d577e23a42c0404aca60a4bfb36b09
                  Version: 39.20240305.0 (2024-03-05T04:54:42Z)
```

**Comment by castrojo** [comment]
I get the same error, needs to be reported to homebrew, thanks! https://github.com/Homebrew/homebrew-core/issues
