### ISSUE TITLE
Cannot install on USB drive or SD Card

### ISSUE THREAD

**Issue by grgendron** [ublue-os/bluefin#1040]
### Describe the bug

 Installation of Bluefin on either a USB connected hard drive or a SD Card fails. (Whereasl Fedora installs on both). 

Installation starts on both kinds of media::  can select the destination, and start the install. Then it just hangs when files are claimed to being copied. During the process it creates EFI (if necessary), creates ext4 boot partition, and creates btrf partition. 

Subsequent inspection reveals that no files are actually copied into the partitions.

### What did you expect to happen?

I expected bluefin to install, just as Fedora installs. Oops I did not try install to USB or SDC with Silverblue.

### Output of `rpm-ostree status`

```shell
no output, not available
```

### Extra information or context

Motivation: I cannot install bluefin on either of my hard drives (which dual boot), and I wanted to try it on something other than a VM. 
As of March 23, I have tried both the general dx release and the "latest" dx release (39) iso's.

**Comment by m2Giles** [comment]
Are you still experiencing this?

What was the size of each drive being used?
