### ISSUE TITLE
Blurry fonts on various apps while using fractional scaling (Framework laptop 13)

### ISSUE THREAD

**Issue by realitymolder** [ublue-os/bluefin#1043]
### Describe the bug

While using bluefin-dx framework image on the framework laptop 13, and using fractional scaling on gnome, some apps have blurry fonts which makes using the OS really, really hard.

### What did you expect to happen?

Sharp image with sharp readable fonts.

### Output of `rpm-ostree status`

```shell
INPUT UPLOAD VIA EDIT
```

### Extra information or context

Maybe it is related to Wayland not working on Flatpaks by default(?) just a thought.

**Comment by castrojo** [comment]
Yeah, not much we can do about that unfortunately. I hate it so much I turn if off and then turn on large fonts instead. 

![image](https://github.com/ublue-os/bluefin/assets/1264109/d4d40732-67cf-4b10-8083-4efc33e51f9c)

**Comment by castrojo** [comment]
@KyleGospo Can we make this a default Framework-specific dconf setting ootb?

**Comment by realitymolder** [comment]
> Yeah, not much we can do about that unfortunately. I hate it so much I turn if off and then turn on large fonts instead.
> 
> ![image](https://private-user-images.githubusercontent.com/1264109/316390103-d4d40732-67cf-4b10-8083-4efc33e51f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTA1ODcsIm5iZiI6MTcxMTQxMDI4NywicGF0aCI6Ii8xMjY0MTA5LzMxNjM5MDEwMy1kNGQ0MDczMi02N2NmLTRiMTAtODA4My00ZWZjMzNlNTFmOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMjM0NDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ4NjA0MWJlZTc4ZDQ3YTg4NDZhZmQwMzUzNGZjZTU5NGY1NGJkZWM3OTc1YjUyMWE1MzExOWVlMmQ0ZmU1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0o3P8sVDoW_ui4GNgPq7RJHHpOTHXZBquslT7H8PkMw)

Thanks a lot for the very fast reply. What is the source of that issue? Wayland or Gnome itself?

**Comment by m2Giles** [comment]
Both. It's a combination of how Gnome implements scaling for Xwayland applications. The best solution for the time being is using the Large Text key. If you need even larger font, you can set a larger one in Gnome Tweaks.

**Comment by cflewis** [comment]
> @KyleGospo Can we make this a default Framework-specific dconf setting ootb?

I'm not usually a fan of making retailer-specific front-end changes, but I think this would be a worthwhile change. I spent a large amount of time fussing around with this on my new Framework 13 Ryzen today. Nothing came out all that great; images too small, fonts cut off and such. Large Fonts was the best option. I didn't think to search for [bluefin blurry fonts] but lots of variations on [fedora blurry fonts] [framework blurry fonts] [gnome fractional scaling blurry] etc etc etc. Having this set out of the box would be helpful.
