### ISSUE TITLE
Update Path to Checksums on the Website

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/bluefin#1067]
### Describe the bug

There is an issue with downloading checksums after moving over to the upstream ISO generator.

### What did you expect to happen?

Be able to download a checksum

### Extra information or context

`bluefin-latest-CHECKSUM` should point to `bluefin-latest.iso-CHECKSUM` now.

**Comment by noelmiller** [comment]
When we switch Bazzite to upstream ISO generator, this will also have to happen there too!

**Comment by KyleGospo** [comment]
https://github.com/castrojo/bluefin-website/commit/6c0d10f217182b924ff7bd1a926cff2418243efd
