### ISSUE TITLE
Missing packages in bluefin-gts 38.20240328.0

### ISSUE THREAD

**Issue by karlisk** [ublue-os/bluefin#1071]
### Describe the bug

I've been using successfully the non-Dx Nvidia variant of Bluefin on one Lenovo laptop for a few weeks now, so I figured I'd install it on a Thinkpad but my clean install seems to be missing some of the core applications and utils like Ptyxis and yafti.

### What did you expect to happen?

Ptyxis and initial setup prompt to launch at first boot.

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: busy
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Transaction: rebase ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts 
  Initiator: client(id:cli dbus:1.219 unit:vte-spawn-2ac8acec-a06b-42a8-8f41-5c05754550e4.scope uid:1000)
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:gts
                   Digest: sha256:05d92756373ecadb1b7d051830db52f8c7539cbdb4a01e30e299e4bc1ac7b4d1
                  Version: 38.20240329.0 (2024-03-29T20:31:51Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:gts
                   Digest: sha256:2b13c4c1e233940076a9cd15595220b7b9ce4d3192fd4d09ec5343e35ebff0bc
                  Version: 38.20240328.0 (2024-03-28T23:16:24Z)
```

### Extra information or context

`fedora gsd-media-keys[5754]: Could not launch 'ptyxis --tab-with-profile=2871e8027773ae74d6c87a5f659bbc74 --new-window %f': Program ‘ptyxis’ not found in $PATH`
```
ujust yafti
yafti /etc/yafti.yml --force
sh: line 1: yafti: command not found
error: Recipe `yafti` failed on line 314 with exit code 127
```
```
which ptyxis
/usr/bin/which: no ptyxis in (/var/home/user/.local/bin:/var/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin)
```

**Comment by castrojo** [comment]
ptyxis is currenty broken (we're working on it) and yafti was removed on purpose (it'll come back at some point)

**Comment by karlisk** [comment]
I must've missed it in the changelogs then - thanks for a swift explanation. I've gotten so used to it that I was confused why it wasn't working or why `Ctr+Alt+T` keybinding was trying to launch it.

**Comment by castrojo** [comment]
Alright just merged it, should be ready in a few minutes, thanks!
