### ISSUE TITLE
Blank "Default applications" on initial launch

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1076]
Default apps is empty on initial install:

![image](https://github.com/ublue-os/bluefin/assets/1264109/8912486c-e33c-4e76-84f4-9d1fb206f0d5)

However if you install something (like Chrome) it fixes it: 

![image](https://github.com/ublue-os/bluefin/assets/1264109/1a5ff778-ee2e-4bcb-bf0a-4f7df0d82aef)

Maybe there's some command or something that we need to run to refresh that window?

**Comment by noelmiller** [comment]
We could use this utility to manually set them: https://portland.freedesktop.org/doc/xdg-settings.html

**Comment by m2Giles** [comment]
Pretty sure we fixed this with the more recent ISOs.

**Comment by m2Giles** [comment]
This is still an issue.

**Comment by m2Giles** [comment]
For Web:
```
xdg-settings set default-web-browser org.mozilla.firefox.desktop
```
For Email:
```
xdg-settings set default-url-scheme-handler/mailto org.mozilla.Thunderbird.desktop
```

**Comment by m2Giles** [comment]
And like was mentioned, if you install a flatpak it seems to sort it self out.

**Comment by ecomized** [comment]
Thanks @m2Giles for sharing the fix!

Would be still great if that could be fixed, it's pretty annoying after the first install to having this kind of problem.
