### ISSUE TITLE
Recently started not waking up from sleep/hibernation

### ISSUE THREAD

**Issue by donaldedgar** [ublue-os/bluefin#1078]
### Describe the bug

Things had been working fine for a while, but recently when I open the laptop lid the key backlights come on, the power button turns on and starts blinking, but that's it. I have to hard restart the computer more often than not.

### What did you expect to happen?

I was expecting the screen to turn on and show the lock screen like it had been doing and still sometimes does.

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-framework:latest
                   Digest: sha256:4cdcf11626f8126b415908f80f53b37bb985e77972a94f94b6d07a3501541ef7
                  Version: 39.20240329.0 (2024-03-29T17:54:21Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-framework:latest
                   Digest: sha256:df174ef0ecf4f4df489af5ae4829d90fb5690d3874e7fa43828aafec1df32732
                  Version: 39.20240325.0 (2024-03-25T20:35:45Z)

AvailableUpdate:
      Timestamp: 2024-03-30T02:41:23Z
         Commit: 6a9b543b842c11b64dbaf9882317a7ad0ca441fd1f71fda8f8c0048ca72d23c9
           Diff: 4 upgraded, 2 added
```

### Extra information or context

I don't know if it's from a recent upgrade, but it hasn't always been like this and it's not 100% of the time it won't fully wake up. Though more frequently than not these days.

**Comment by donaldedgar** [comment]
I'm not 100% sure, but I believe it has to do with too many tabs open in vivaldi. If I hibernate my tabs, it functions as normal. If I forget to, and come back after a while, that's when it doesn't fully wake up.

**Comment by m2Giles** [comment]
Is this still occurring? We have had a few kernel updates since this was reported.

**Comment by donaldedgar** [comment]
I had been hibernating my browser every time I was done, though the last couple of nights I left it as it was and it seems​ to be not still occuring.

**Comment by donaldedgar** [comment]
I've given it a few more days without hibernating my browser, and it seems to have resolved itself at some point with one of the kernel updates. Closing the ticket.

**Comment by pewinski** [comment]
I'm having the same problem and update didn't fix it, I created an issue here: https://github.com/projectbluefin/common/issues/1098
