### ISSUE TITLE
Gnome kick me out like log out

### ISSUE THREAD

**Issue by markob94** [ublue-os/bluefin#1081]
### Describe the bug

I am using my laptop normally, playing games, or vscode, or just browsing the internet, and than suddenly I found my laptop in log out screen. Every app was closed, not saved work.
Everything is default, not additional apps or tweaks

### What did you expect to happen?

Not to close all my apps

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:9949217976c012c27e58c94166daeb252d6652c4806917d81d43e6bb5b448f9f
                  Version: 39.20240331.0 (2024-03-31T17:12:02Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:f613505f2d1f1686aa05d1739475336c82b6610bcd60f2cfee0da889792fc6b5
                  Version: 39.20240330.0 (2024-03-30T16:51:42Z)
```

**Comment by m2Giles** [comment]
Did this happen when the lock screen appeared?

If so, you can try adding the following environment variable (I place this in ~/.config/environment.d/mutter.conf - make it if not present) MUTTER_DEBUG_KMS_THREAD_TYPE=user

**Comment by markob94** [comment]
> Did this happen when the lock screen appeared?
> 
> If so, you can try adding the following environment variable (I place this in ~/.config/environment.d/mutter.conf - make it if not present) MUTTER_DEBUG_KMS_THREAD_TYPE=user

Yes, it happens and then the lock screen appears.
It is not happening always, I mean every day.

**Comment by m2Giles** [comment]
Try adding the environment variable and see if the behavior still exists.

**Comment by m2Giles** [comment]
Are you still experiencing this issue?

**Comment by markob94** [comment]
> Are you still experiencing this issue?

Hi, sorry for not replying. It didn't happen after that trick.

**Comment by markob94** [comment]
Also i noticed on F40 that folder environment.d is not there anymore.
There is just environment file in /etc with  MUTTER_DEBUG_FORCE_KMS_MODE=simple

**Comment by m2Giles** [comment]
Did you put it in /etc or in ~/.config?

**Comment by markob94** [comment]
> Did you put it in /etc or in ~/.config?

now it is in ~/.config? :)
