### ISSUE TITLE
Independent yafti configs between bluefin-dx and bluefin

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1088]
We wanna add more developer oriented options for the -dx yafti setup on first boot. Right now bluefin and bluefin-dx share the same yafti.yml file. 

We need to split them for each image, and then what we can do is when you're on a -dx image we run yafti twice, once with the stock config, and then when they go through that run it with the -dx config, and in there we can add some kickass developer personas: "AI Tools" which pull in ollama and a bunch of goodies, etc. and so on.

**Comment by m2Giles** [comment]
We have different yafti's for bluefin and aurora right now.

I think we can consolidate these two and use sed or something for branding changes at build time. The same method could be used for our -dx config.
