### ISSUE TITLE
Extensions for F40

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1107]
The following need to be done for F40:

- logomenu
- gsconnect
- tailscale QS
- caffeine? 
- dashtodock?

And the following are good to add once supported:

- blur-my-shell

These are all in bazzite so we'll get those updates, just placeholding them here.

**Comment by bketelsen** [comment]
- [x] logomenu 
- [ ] caffeine
- [ ] tailscale qs

**Comment by p5** [comment]
Unless I'm missing something, caffeine and Tailscale QS are already on the image.
Have PRd blur-my-shell since it's now being successfully installed

**Comment by p5** [comment]
Have loaded a VM and can confirm all except GSConnect and Tailscale are working:

Blur:

<details>
![image](https://github.com/ublue-os/bluefin/assets/46304672/581865d6-81a0-4faf-af98-3a6fbc33cfd9)

</details>

Caffeine:

<details>
![image](https://github.com/ublue-os/bluefin/assets/46304672/e3d35114-bb0f-4673-b475-964eb87a2852)

</details>

Tailscale:

<details>

![image](https://github.com/ublue-os/bluefin/assets/46304672/a9410d2e-c1b8-4527-a228-992022a63053)

</details>

Logo Menu:

<details>

![image](https://github.com/ublue-os/bluefin/assets/46304672/423f358c-3db2-4a1a-bc97-509e5916d41b)

</details>

Dash to Dock:

<details>

![image](https://github.com/ublue-os/bluefin/assets/46304672/b9acff21-16c2-4bbc-a335-6a57ee4052c5)

</details>

GSConnect:

<details>

![image](https://github.com/ublue-os/bluefin/assets/46304672/ee202b5e-fecd-4922-ad71-06957647cdee)

</details>

They are all on the image, but some incompatible with the current GNOME version.  This will sort itself out on it's own, but will leave this issue open.

**Comment by citrixscu** [comment]
Confirmed the above with fresh iso install on bare metal.

**Comment by m2Giles** [comment]
Tailscale QS appears in my quick settings now.

GSConnect has been updated.
