### ISSUE TITLE
Add search light to default install

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1117]
I was not aware of this extension. Apparently everyone knew except for me. We'll need to COPR this, and then let's set it to <Super>-space by default. 

OK NOW WE'RE DONE.

https://github.com/icedman/search-light

**Comment by castrojo** [comment]
Kyle already has this in bazzite: https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/package/gnome-shell-extension-search-light

Let's move this to the staging repo via ublue-os/packages so we don't need to add a new copr dependency.

**Comment by KyleGospo** [comment]
This is now in our staging repo
