### ISSUE TITLE
Flatpak fails in first time installer on aurora-39

### ISSUE THREAD

**Issue by nidhoggr-nil** [ublue-os/bluefin#1118]
### Describe the bug

After selecting the flatpak packages you want to install, then continuing, all the installation of the flatpak packages fails. The reason is that they install with --user set, but the repo under --user has no packages. 

### What did you expect to happen?

That the packages were installed correctly.

### Output of `rpm-ostree status`

```shell
● ostree-image-signed:docker://ghcr.io/nihaiden/aurora-dx-nvidia:latest
                   Digest: sha256:3a8ebff5328693b816c8b85ba17febb3efa62a1079d0b87d382f9f76dd65b65f
                  Version: 39.20240409.0 (2024-04-09T16:52:37Z)
          LayeredPackages: btrfs-assistant
```

**Comment by m2Giles** [comment]
#1119
