### ISSUE TITLE
Incus/LXD `Error: Failed to connect to local daemon`

### ISSUE THREAD

**Issue by n3ddu8** [ublue-os/bluefin#1132]
### Describe the bug

When I run `incus admin init` I get:
```shell
Error: Failed to connect to local daemon: Get "http://unix.socket/1.0": dial unix /var/lib/incus/unix.socket: connect: no such file or directory
```

When I run `lxd init` I get:
```shell
Error: Failed to connect to local LXD: Get "http://unix.socket/1.0": dial unix /var/lib/lxd/unix.socket: connect: no such file or directory
```

### What did you expect to happen?

The init configuration wizard to launch

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:25512f5bb5985808f7f1583f06cb1846860aa4661814b8bc2989179f1a59873a
                  Version: 38.20240413.0 (2024-04-13T23:30:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:0c6702c9c0f6de5f850761014a5f74fced652cdbe3ec625c87552cd14dcf05e6
                  Version: 38.20240412.0 (2024-04-12T17:04:37Z)
```

### Extra information or context

I've ensured virtualization is enabled in my bios. I don't have any experience of using Incus, but for LXD I've ensured my user is in the lxd group. I've tried searching the errors online but I'm mostly finding information about snaps, which I don't believe is how it's installed on bluefin (correct me if I'm wrong).

**Comment by m2Giles** [comment]
The sockets for lxd and incus are not enabled by default. Enable them with `systemctl enable --now incus.socket` or `systemctl enable --now lxd.socket`

**Comment by n3ddu8** [comment]
That seems to have done the trick - thank you
