### ISSUE TITLE
Split -dx and base Containerfiles and Workflows

### ISSUE THREAD

**Issue by m2Giles** [ublue-os/bluefin#1134]
Currently our -dx images build the base image in the process of building them. With the reusable build workflow we can possible have -dx built directly from the just built base image.

**Comment by p5** [comment]
I'm in two minds about this...  

It would increase the feedback loop in PRs and make us wait around double the time before merging the PRs, however it would reduce the overall time spent on builders since dx would not need to build everything in the base again.

**Comment by castrojo** [comment]
I bet dx continues to rev fast so it might end up freeing up builders if they were split? I'm curious now lol.

**Comment by m2Giles** [comment]
#1136

**Comment by m2Giles** [comment]
There is a blocker for this. -dx builds are now dependent on the underlying image to build and be available. On pull requests we do not publish those images meaning that we will be unable to ensure that nothing in the underlying base has broken -dx.

**Comment by m2Giles** [comment]
Unless we allow PRs to be published, this is blocked.

**Comment by p5** [comment]
An alternative could be to split the Containerfiles, but build both in a single workflow/job.

E.g. 
1. step to build base
2. optional push to registry
3. step to build DX from local base
4. optional push to registry
