### ISSUE TITLE
Switch to ppd for power management

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1143]
Mario's recommending using ppd for our images: https://community.frame.work/t/custom-fedora-oci-images-for-framework-laptops/34253/60

Let's go ahead and just match upstream Fedora with this, here's the original PR, we need to remove the packages, the override, and the service enablement: https://github.com/ublue-os/bluefin/pull/836/files

**Comment by m2Giles** [comment]
#1144
