### ISSUE TITLE
Follow CoreOS releases as a `stable` tag

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1151]
The 6.8 release hit F38 as fast as F39 so we ended up with broken v42loopback and stuff. I'd like to investigate a slower cadence for kernels. The CoreOS kernels are Fedora kernels, they just update on a slower cadence. I'd like to investigate using those for `gts`. They're still supported by Fedora CoreOS and it might give us the stability sweet spot we're looking for.

And also maybe moving to a weekly cadence might be the play for gts, cut down on the large updates until we have some form of diffs. Thoughts on this?

Discord thread: https://www.answeroverflow.com/m/1222566962320642068

**Comment by xalt7x** [comment]
I don't want to go offtopic here but had UBlue developers considered using [unofficial Fedora LTS kernels maintained by kwizart](https://copr.fedorainfracloud.org/coprs/kwizart/kernel-longterm-6.6/)?
They have been available for a long time and seem to be relatively popular ([recommendation in openzfs-docs](https://github.com/openzfs/openzfs-docs/blob/06d652493c3baf34e1273fc7319c598e7a58ee82/docs/Getting%20Started/Fedora/index.rst), mentions in Fedora forums and various other places).

**Comment by castrojo** [comment]
Those would be a great for a custom image but for bluefin we're going to want to stick to the official kernels from Fedora.

**Comment by castrojo** [comment]
Ok so pulling in a CoreOS kernel leads to a 40 kernel on 39, we probably don't want that so instead we're thinking this: 

`bluefin:latest` -> Always Fedora +0
`bluefin:stable` -> Follows the CoreOS cadence, it updates to 40 when they update to 40.
`bluefin:gts` -> Always Fedora -1

This way people can opt in to the CoreOS cadence but we leave gts and latest alone. CoreOS moved to 40 on May 06, which is about two weeks after release, feels like the kind of padding we're looking for?

**Comment by noahdotpy** [comment]
is there a way to possibly have gts and a slower CoreOS kernel as well?
