### ISSUE TITLE
DevPod on F40

### ISSUE THREAD

**Issue by m2Giles** [ublue-os/bluefin#1153]
We removed DevPod from the Fedora 40 package list temporarily. This issue serves as how we will get this package back.

Dependency List:
libappindicator-gtk3 
webkit2gtk4.0 -> provides libwebkit2gtk-4.0.so.37
openssl1.1 -> provides libssl.so.1.1

Current issue:
Fedora 40 does not provide libssl.so.1.1.

**Comment by aussielunix** [comment]
I have just downloaded the Linux v0.5.6-alpha.1 tarball.
I am on `Fedora Linux 40.20240411.0 (Silverblue)`

The cli is statically compiled so works as expected.
The UI (tauri app) is a dynamic binary but the deps have changed.
libssl is no longer a problem for me

```bash
[~/tmp/dp/usr/bin]
lunix@astro]  -> ldd dev-pod  | grep ssl
	libssl.so.3 => /lib64/libssl.so.3 (0x00007f88ee978000)

[~/tmp/dp/usr/bin]
lunix@astro]  -> ldd dev-pod  | grep "not found"
	libwebkit2gtk-4.0.so.37 => not found
	libjavascriptcoregtk-4.0.so.18 => not found
```

**Comment by m2Giles** [comment]
Alright, when v0.5.6 releases we can look at adding it back in!

**Comment by aussielunix** [comment]
There is still a couple of missing libs in F40.
I think the only way that Devpod on F40 is going to work is if F40 was to be add to the build matrix in their GitHub action and an F40 tarball is created.

**Comment by aussielunix** [comment]
Bingo !

Thank you @tfmoraes 

With this simple [recipe.yml](https://github.com/aussielunix/mystation/blob/main/config/recipe.yml) I can download the v0.5.6-alpha.1 devpod tarball and it works just fine without toolbox/distrobox

**Comment by m2Giles** [comment]
Devpod 5.6 was released. I'll see if we can get devpod building properly with the rpm. As a fallback we can look at going back to directly using the tarball.

I can get devpod working with docker, but it is currently failing with podman.

**Comment by m2Giles** [comment]
#1244

**Comment by m2Giles** [comment]
Good news and bad news:

Good News: It is working with podman unlike the appimage.
Bad News: Both Docker and Podman cannot open in desktop vscode. Browser VSCode is working.

Devpod is an RPM in our staging copr.

**Comment by aussielunix** [comment]
> Here is what I have now that is working:
> 
>     * I have add the files from the v0.5.6-alpha.1 devpod tarball to [config/files](https://github.com/aussielunix/mystation/tree/main/config/files) (replace once 0.5.6 is in ublue COPR)
>     * Add Microsoft's [VSCode repo](https://github.com/aussielunix/mystation/blob/main/config/recipe.yml#L24)
>     * Add `code` and `webkit2gtk4.0` to [recipe.yml](https://github.com/aussielunix/mystation/blob/main/config/recipe.yml#L35) to be installed with rpm-ostree

I just removed the devpod tarball and add the staging RPM, baked a new container and rebased.
This works fine for me.

I start a workspace using a k8s provider and it opens vscode with a correctly setup ssh tunnel for the terminal.

I am ok with the fact devpod and vscode are both installed and run from my custom image and not in a distrobox.

**Comment by m2Giles** [comment]
Issue filed upstream about vscode URL. Otherwise this is working with docker and podman. Closing.
