### ISSUE TITLE
Panda wireless dongle driver 

### ISSUE THREAD

**Issue by profetik-777** [ublue-os/bluefin#1167]
### Describe the package

I'd like to request the package (if it exists) panda wireless drivers , so it can be plug n play , and recognized. What would be best way/place to do this? Silverblue as part of upstream or here?

Device: Panda Wireless® PAU0C AC1200 

### Image

All Images

**Comment by castrojo** [comment]
Does it not work? I've never seen a panda usb one not work before?

**Comment by tepene** [comment]
I just upgraded one of my machines from stock Silverblue to bluefin-dx. After that my [Netgear 6210 AC1200 WiFi USB](https://www.netgear.com/support/product/a6210/) Adapter is no longer recognized. I see it with `lsusb` but the system does not recognize it as a wifi adapter. With a rollback to Silverblue the adapter is working again.

**Comment by bsherman** [comment]
I've seen similar issues with USB Ethernet adapters which worked before... Haven't had a chance to understand why yet.

One such device ( https://sabrent.com/products/NT-S25G ) partially works then degrades performance...
Another ( https://plugable.com/products/usbc-e2500/ ) never works, that is NetworkManager sees the device but considers it "disconnected".

In both cases, they show in `lsusb` also.

I want to do some testing to see if this is unique to Universal Blue/Bluefin or an upstream Fedora problem.

**Comment by bsherman** [comment]
> I just upgraded one of my machines from stock silverblue:39 to bluefin-dx:39. 

Ooops, I read "upgraded" and assumed 40, skipping over the clear "39" here... so my issue is probably not related.

**Comment by profetik-777** [comment]
> Does it not work? I've never seen a panda usb one not work before?

Correct - it didn't even recognize it as if it wasn't plugged in. I agree - I was surprised myself. But fedora has burned me in the past w/ random things not working (my hp gaming pavilion 15nr touch pad just wasn't recognized in fedora 35, but then was recognized in 36).

**Comment by profetik-777** [comment]
@castrojo not sure how you want to address this - since "driver" creep can get crazy. 

I'll close since I hopped to something else but something to think about....what is the dividing line between including drivers for the sake of including bc some one rando had trouble w/ xyz device vs great user experience. 

I don't know how to answer that or how you and the thinks thru this.  But maybe a potential meeting agenda/ topic for you and the team if the answer isn't immediately obvious. 

Impressed how the project is blossoming and thriving! Your vision + your evangelism is paying off, people are getting it!

**Comment by castrojo** [comment]
We want to enable as much hardware as we can reasonably support, adding support for this won't make other people's experiences worse and this is one of the worst parts of using Linux on the desktop so if we can fix it, we try to fix it. 

Can you get us any hardware info on the specific dongle?

**Comment by profetik-777** [comment]
I'll fire it up on a test machine and get back to you within a week since the machine I was originally using it on is now a garuda machine.

**Comment by profetik-777** [comment]
@castrojo after doing lsusb command on ubuntu (it didn't work there either - just on opensuse tumbleweed oddly enough) I found: 

MediaTek Inc. MT7612U 802.11a/b/g/n/ac Wireless Adapter

And after some research, I heard this driver is a pain. 

Let me know what I can do to help.

**Comment by profetik-777** [comment]
@castrojo So what do you think? 

Backlog this? 

Or...

Is there a way to "pinpoint" the driver that openSUSE uses, and try to find the fedora equiv? Or worse, get that repackaged for fedora?
