### ISSUE TITLE
GitHub Action Improvements 

### ISSUE THREAD

**Issue by m2Giles** [ublue-os/bluefin#1187]
Investigate automatic workflow retries for merge queue to not fail merges due to spurious HTTP errors

Investigate better logic gating to allow merges that only affect Bluefin or Aurora to merge without building the other via merge queue.

**Comment by noelmiller** [comment]
> Investigate automatic workflow retries for merge queue to not fail merges due to spurious HTTP errors
> 
> Investigate better logic gating to allow merges that only affect Bluefin or Aurora to merge without building the other via merge queue.

This would be good to do across the board if we can. I know Bazzite was getting some stuff in there and main does as well.

**Comment by castrojo** [comment]
Superceded by: https://github.com/ublue-os/bluefin/issues/1467

The split aurora/bluefin merging is implemented.
