### ISSUE TITLE
ujust brew installing does not configure fish shell

### ISSUE THREAD

**Issue by etrigan63** [ublue-os/bluefin#1205]
### Describe the bug

I ran `ujust fish` which switched my shell as expected. I then ran `ujust brew` and that ran as expected. I then ran `brew doctor` and it says "Command brew not found".

### What did you expect to happen?

After installing brew, the paths of the fish shell should be updated automatically like in bash.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 28min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:41f5b9c3d56eb9849ddb7fb34ff88785584b5ece17ac8be51350cd0f0d7bf115
                  Version: 40.20240423.0 (2024-04-24T14:51:15Z)

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:e73d3323f1023a4ed737fbec1cafbd0e583c2fa0fd0b068800157ad63ba5e397
                  Version: 40.20240423.0 (2024-04-23T14:59:20Z)
```

**Comment by m2Giles** [comment]
Yepp, I see that we have our fish brew code and zsh items currently under dx and not our share code branch.

That needs to be moved over.

**Comment by citrixscu** [comment]
In the interim, you can add `[ -d /home/linuxbrew/.linuxbrew ] && status --is-interactive && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` to your `config.fish` file. I'll take a look at how we pull the stuff from dx back to shared.
