### ISSUE TITLE
Aurora Application Launcher Icon doesn't match theme

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/bluefin#1225]
### Describe the bug

the aurora logo in the application launcher has a white background which doesn't match the panel colour in dark or light mode.

![image](https://github.com/ublue-os/bluefin/assets/62875653/94e3cfa3-9526-4357-af26-153befd76b49)

### What did you expect to happen?

I expect it to have a transparent or dark background which matches the panel's color

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:40
                   Digest: sha256:bf57655fbce0eddfd33a2caa724dcbb570cc29b20ccaf5d8eb2c24d6307d657e
                  Version: 40.20240427.0 (2024-04-27T23:13:59Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"' 

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:40
                   Digest: sha256:624d149bb1a62b9b6fd99c153b0f405b7494ad114df02039ae1ea5ab09dcacc9
                  Version: 40.20240425.0 (2024-04-25T16:51:42Z)
                Initramfs: '"-I /etc/crypttab /etc/modprobe.d/amdgpu.conf"'
```

**Comment by m2Giles** [comment]
Which logo are you using for the application launcher?

The default should /usr/share/icons/hicolor/scalable/places/distributor-logo.svg

From the icon selection for kickoff it is accessible from places/distributor-logo.svg

**Comment by m2Giles** [comment]
#1229

**Comment by RealVishy** [comment]
> Which logo are you using for the application launcher?
> I had it set to the default plasma one so i used the configure option and the other category to get it as the system-logo.

![image](https://github.com/ublue-os/bluefin/assets/62875653/18f0ace3-92c7-4de1-86ff-028b8b594a0f)

**Comment by m2Giles** [comment]
The PR I linked also fixes those logos as well because they shouldn't of had a white background.

**Comment by RealVishy** [comment]
issue solved then
