### ISSUE TITLE
ujust incus: fails on aurora

### ISSUE THREAD

**Issue by acuteaura** [ublue-os/bluefin#1228]
### Describe the bug

`ujust install-incus` asks for developer mode to be enabled; it is.

This is due to checking for `bluefin-dx` specifically: https://github.com/ublue-os/bluefin/blob/e9436f608e9bb5d2d72eca5cefec98a621dcbb81/just/bluefin-apps.just#L114

### What did you expect to happen?

`ujust install-incus` checks for presence of dx-image independent of bluefin/aurora.

**Comment by m2Giles** [comment]
This script will need to be removed. But incus now works with SELinux. I'll add the workaround portion as a service file like swtpm.

**Comment by m2Giles** [comment]
#1231

**Comment by m2Giles** [comment]
This will now work on Aurora and the SELinux items are in place.

The ujust is still available to conveniently setup subuid/subgid and run the init/setup firewall
