### ISSUE TITLE
Aurora: Aurora icon on application launcher widget looks odd in light theme

### ISSUE THREAD

**Issue by noahdotpy** [ublue-os/bluefin#1234]
### Describe the bug

When I use the aurora logo on plasma launcher applet, the middle part which has the letter A looks odd due to being a light icon on a light background.

### What did you expect to happen?

I expect there to be an icon for the light theme as well as dark theme.

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status    
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/noahdotpy/aurora-dx-latest:latest
                   Digest: sha256:90a3b5e440069660b04e6be37f13ad0694e1fe70f87174274fbf33df655d8273
                  Version: 40.20240428.0 (2024-04-28T17:18:48Z)

  ostree-image-signed:docker://ghcr.io/noahdotpy/aurora-dx-latest:latest
                   Digest: sha256:cf4177c51bbc516435f8e0f991345a033693f26a8cd211a1e19a375efa8bde33
                  Version: 40.20240426.0 (2024-04-26T23:37:49Z)
```

**Comment by noahdotpy** [comment]
Pretty much I am asking for an aurora icon that fits a light background

**Comment by NiHaiden** [comment]
Do you have a screenshot so I can see what the aurora logo looks like on a light theme? I don’t have my Aurora PC with me on my vacay so it would be very helpful

**Comment by noahdotpy** [comment]
![image](https://github.com/ublue-os/bluefin/assets/80379684/f54e8f96-5d0a-493a-9493-4066f8eb9d7e)

**Comment by noahdotpy** [comment]
admittedly it doesn't look too bad, but the contrast with the 'A' is not the greatest

**Comment by NiHaiden** [comment]
I see, thank you for providing the screenshot!

**Comment by NiHaiden** [comment]
![aurora](https://github.com/ublue-os/bluefin/assets/40402114/9d77c593-4522-4a34-8187-e8702c59ddaa)
Hi @noahdotpy, how does this remixed version of the logo look on your desktop?

**Comment by noahdotpy** [comment]
> ![aurora_logo_remixed](https://private-user-images.githubusercontent.com/40402114/333736439-b8813d07-df14-44de-8bfb-43224bc8193e.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzQzMDQsIm5iZiI6MTcxNjYzNDAwNCwicGF0aCI6Ii80MDQwMjExNC8zMzM3MzY0MzktYjg4MTNkMDctZGYxNC00NGRlLThiZmItNDMyMjRiYzgxOTNlLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEwNDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3OTM1Y2MwZTg3ZDM0OWNlZGY3NDRiMDMzZGRhODFmNzI3NjEyNWU1YTBjMWFkZjM5YTc2MTJkYzk5YjQ2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X4SULI9NUx4hEZ0Eyf4DApfvSWGw4LZVasq_pT587ZI)
> 
> Hi @noahdotpy, how does this remixed version of the logo look on your desktop?

This one looks much better with the contrast to the white background! Thank you so much

**Comment by noahdotpy** [comment]
Just me personally I did remove the stars because I have a very small panel width so it was like 1 pixel anyway, looking a bit cluttered
