### ISSUE TITLE
VScode flickering & input lag

### ISSUE THREAD

**Issue by FelipeCabelloE** [ublue-os/bluefin#1238]
### Describe the bug

When opening vscode, either in a folder or in a devcontainer, the window flickers on basic interactions, sometimes I cannot click on menus and also have click and hover lag.

### What did you expect to happen?

I expected a seamless experience

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.service: last run failed
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:2016122155ee6a5a40a25feede6b3f1baa2832684b59bfba16fb6a6790d66619
                  Version: 39.20240427.0 (2024-04-27T14:33:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:bc6df7b2787c2753e4e2ffc988460c93194f44cab4789ca6df505a4e21395c43
                  Version: 39.20240423.0 (2024-04-23T16:55:52Z)
```

### Extra information or context

[Screencast from 2024-04-29 19-09-07.webm](https://github.com/ublue-os/bluefin/assets/98831429/ed616363-1cef-48ec-8606-74e807c212cc)
A short video of the problem

**Comment by citrixscu** [comment]
Looks like classic wayland nvidia driver electron app flickering. The 555 drivers that should be coming sometime next month are supposed to implement explicit sync and then there will need to be some patches. For now, I think the only thing you can do is run X11 or swap to the NVK driver.

**Comment by Six6pounder** [comment]
same issue in aurora

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest
                   Digest: sha256:ce78730ed2752088fd2ee6a605618426e5434217bc07d1a4df58c0ccb7df736e
                  Version: 40.20240429.0 (2024-04-29T16:53:01Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:4f57a20701f039880e3726523330a6a0ac2d9c82f4cd9e6b5f06dfec8bd8f4cd
                  Version: 40.20240428.0 (2024-04-28T20:43:01Z)
                   Pinned: yes
```

**Comment by FelipeCabelloE** [comment]
Many thanks for your answer!
Is there a "best practices aproach" when dealing with these kinds of issues in atomic distros?

**Comment by FelipeCabelloE** [comment]
Thank you for your answer
I was hoping on using my 3060 with bluefin, I guess there is no scaping the nvidia-linux problem.

**Comment by castrojo** [comment]
Hang in there!
