### ISSUE TITLE
Bluefin/Aurora does not automatically update Brew packages

### ISSUE THREAD

**Issue by tobiasmicheler** [ublue-os/bluefin#1245]
### Describe the bug

The Version of ublue-update in Bluefin/Aurora does not include the addition of updates of brew added here:
https://github.com/ublue-os/ublue-update/pull/107
See copr of ublue-update:
https://copr.fedorainfracloud.org/coprs/ublue-os/staging/package/ublue-update/

### What did you expect to happen?

brew packages update automatically

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status 
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:4af98763fefe784a8b53332c98877989c47532b53319e1c0d10953830c6912d6
                  Version: 40.20240501.0 (2024-05-01T19:08:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:b491292743e983ba9b3ec036dae66ab7cb019af5fc0d1aba2eea7fa7e1e022aa
                  Version: 40.20240501.0 (2024-05-01T18:17:14Z)
```

### Extra information or context
EDIT: The topgrade config file is now set correctly, but as the brew location is only in PATH for interactive shells, topgrade does not detect a brew installation when called from systemd.

**Comment by m2Giles** [comment]
Did you disable ublue-update.timer?

**Comment by GrumiumXD** [comment]
When running the `ujust update` command, it does update "brew" packages, which made me realize that the `ujust` command and the `ublue-update` service execute "topgrade" with different config files.

Is this intended? I thought one is meant to be the manual updater in case automatic updates are disabled, but still both would do the same thing in the end.

**Comment by m2Giles** [comment]
Yes the service only updates a limited subset of items. We update automatically rpm-ostree, distroboxes, flatpaks, and brew (the last one was not due to copr needed a rebuild)

The manual method is supposed to update more. You additionally can tune the manual update to only update certain things.

**Comment by m2Giles** [comment]
#1249

**Comment by m2Giles** [comment]
Okay, we'll need to update ublue-update then.

**Comment by m2Giles** [comment]
#1293

Implements systemd timers for auto updating and auto upgrading homebrew.

If the brew user is not UID 1000, you will need to override the service (that sounds like a just command).

This service runs at the system level but executes as the specified user.

**Comment by m2Giles** [comment]
It has been merged.
