### ISSUE TITLE
Add quickemu dependencies to devmode (on dx)

### ISSUE THREAD

**Issue by realitymolder** [ublue-os/bluefin#1246]
### Describe the package

I'd like to request the packages `edk2-tools  lsb  spice-gtk-tools xrandr` because it will help setup quickemu. Might as well add quickemu itself! 
quickemu is a cli tool that allows the user to spin qemu kvm-vms EXTREMELY quickly 

### Image

All Images

**Comment by castrojo** [comment]
virt-viewer is already on the image and can do spice (and remmina from flathub should be able to handle spice connections). 

Unfortunately it seems that xrandr is already on our image but that'll be on the chopping block at some point. Have you tried it in a distrobox? That should work.
