### ISSUE TITLE
deja-dup missing

### ISSUE THREAD

**Issue by bketelsen** [ublue-os/bluefin#1255]
### Describe the bug

on a fresh install there is no Backup app

### What did you expect to happen?

I expected to be able to open deja-dup

### Output of `rpm-ostree status`

```shell
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:14431c0b0213b861beab72f88ce41165ce78bb7dca432c01b0a1cf6d50f87d42
                  Version: 40.20240428.0 (2024-04-28T18:29:54Z)
```

### Extra information or context

fresh install from latest Iso available May 5, 2024

**Comment by m2Giles** [comment]
#1266 

Added to flatpak list.
