### ISSUE TITLE
Aurora blank screen on discrete gpu followed with os crash 

### ISSUE THREAD

**Issue by tomrutsaert** [ublue-os/bluefin#1261]
Aurora after while shows a blank screen on displays connected to discrete GPU followed up with a system crash and automatic reboot.

This happens not immediately, sometimes it happens after a half day of work, and sometimes after a n hour of gaming.
I am suspecting it has to do with amd drivers on my discrete GPU because only the displays connected to the discrete gpu go blank. The display connected met integrated gpu keeps working untill the pc crashes after a couple of seconds.
Music also keeps on playing.

device info:
https://paste.centos.org/view/237b191d

Can I add any other info ? Because I have no clue where to start and search for the cause?

**Comment by tomrutsaert** [comment]
Thx (work + gaming pc in one)
This happens daily at least once
I will try the vt switch next time, but I might not be fast enough to type the dump journalctl dump?

Does it help to pastbin the ujust logs-last-boot?

I could link my other display also on my discrete gpu if really needed and see if it goes away

**Comment by m2Giles** [comment]
Yeah last boot logs should work.

**Comment by tomrutsaert** [comment]
https://paste.centos.org/view/89598922
this the log last boot from the afternoon when i had the crash

**Comment by m2Giles** [comment]
Do you have any additional plasmoids installed?

You have this: `plasmashell[6779]: kf.svg: findInCache with a lastModified timestamp of 0 is deprecated`

Being spammed after login. You then also get H264 decode errors.

Pipewire and Spectacle also seem to have issues with getting Codecs as well.

Then at the end you hit some sort of Kernel bug:
` kwin_wayland[6510]: kwin_wayland_drm: Pageflip timed out! This is a kernel bug`

**Comment by tomrutsaert** [comment]
not that I am aware of. I am running rather stock aurora, I only changed keyboards shortcuts, installed brew, jetbrains, flatpaks and some distroboxes.....
I did some  cpu/ram/disk widgets on the desktop at one time, but removed them again very rapidly

What codecs would I be missing, aren't all necesaary codecs included in the image?

Is that kernel the bug the crash? Anyway to figure out what caused it?

**Comment by m2Giles** [comment]
Can you try switching from the Aurora theme to the stock Fedora Theme? I want to rule out the Aurora theme.

The Codecs in question is saying bitstream error on H264. If you were inside a flatpak, the driver should of been provided there. I haven't seen that message in my logs but was an interesting note. Pipewire and Spectacle both call vainfo and they do find the radeonsi.so, but they call it multiple times.

The most jarring thing is that deprecated notice is being spammed over and over. The warning at the end said DRM flip action timed out and likely why the desktop went black.

**Comment by tomrutsaert** [comment]
I have switched the theme to fedora (breeze dark)
I will post my my log-last-login again when I have my next crash

**Comment by tomrutsaert** [comment]
It happened again

the last-boot-log (only last 2 hours - log was too big for pastebin): https://paste.centos.org/view/ee772d38

I was trying to taking a rectangle screenshot with spectacle from intellij.
my theme is now fedora.
Could it be related to intellij and wayland?

**Comment by m2Giles** [comment]
I'm leaning to something with spectacle.

**Comment by tomrutsaert** [comment]
So I did not have a crash for a couple of days (did not use spectacle), and just now had a crash again after taking several rectangle screenshots with spectacle. So if it is really spectacle this should be easily reproducible of another machine by taken a couple of rectangle screenshots....

**Comment by m2Giles** [comment]
I haven't been able to reproduce with my intel based machine.
