### ISSUE TITLE
Framework power management wedges to Battery Saver when unplugged

### ISSUE THREAD

**Issue by cflewis** [ublue-os/bluefin#1276]
### Describe the bug

I got a Framework 13 Ryzen yesterday and placed Bluefin DX 40 on it.

I have noticed that when the laptop is plugged in, I can move between power management settings (Performance/Balanced/Battery Saver). When it's unplugged, changing the setting doesn't do anything: it'll revert back to Battery Saver.

### What did you expect to happen?

Power management when unplugged should respect what I am telling it and not switch straight back to Battery Saver. Let me have the juice!

**Comment by castrojo** [comment]
You can set the default in logomenu -> power profile switcher:

![image](https://github.com/ublue-os/bluefin/assets/1264109/0c82c36e-9199-4041-898f-46255090ca73)

**Comment by cflewis** [comment]
Ah, thanks.

Can we revisit the decision to have this extension on by default? There are two places where the power management is exposed:

1. The top right menu with the little switches (sorry, don't know what Gnome calls it :smile: )
2. The system settings app

Neither of these give any indication that an extension is managing the power. The extension itself gives no notification when it switches the power management to clue in the user that some behavior is taking place that is a feature, not a bug.

I think if there was a notification, it would all be peachy. But without it just looks like the Gnome is not responding correctly.

**Comment by castrojo** [comment]
Yeah I'd accept a PR that turned it off by default, good idea.
