### ISSUE TITLE
DisplayLink eats CPU after closing and opening laptop lid

### ISSUE THREAD

**Issue by defunctl** [ublue-os/bluefin#1277]
### Describe the bug

Using older Intel hardware (Lenovo t480s, 8th gen core i5), close the laptop lid. Open it again and observe the DisplayLink binary using `htop` start using CPU, enough that fans crank up to max.

### What did you expect to happen?

Use the normal amount of CPU it does before the laptop lid was closed and opened.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:fa74370b26b0a657ed38130a0783edf9401c14dbb2c459ab57e20d9c0136b6e7
                  Version: 39.20240507.0 (2024-05-08T11:30:34Z)
                     Diff: 1 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:7e01d78a71032ec8cf7571e715422b051b15fe372ea74094a5aa2d92516f38c8
                  Version: 39.20240507.0 (2024-05-08T01:12:14Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:7e01d78a71032ec8cf7571e715422b051b15fe372ea74094a5aa2d92516f38c8
                  Version: 39.20240507.0 (2024-05-08T01:12:14Z)
```

### Output of `groups`

```shell
defunct wheel
```

**Comment by castrojo** [comment]
Should we consider shipping this service off by default and documented to people how to turn it on?

**Comment by m2Giles** [comment]
I'm leaning towards wanting to disable the service.

I can confirm there is some odd behavior at times. I think this will be a perfect toggle item for new yafti. The only concern I have is if a person doesn't know what display link is and doesn't know they should enable it or not.

**Comment by m2Giles** [comment]
Displaylink is also connected to our Xorg in qemu issue: #868

**Comment by catdevnull** [comment]
I also have weird CPU usage of displaylink (which I don't even use :)

After ~10 hours of uptime,         CPU: 18min 24.286s

**Comment by m2Giles** [comment]
We've identified that the displaylink service and module are always enabled and loaded even when a user doesn't use them.

We've asked from clarification why the change was made upstream.

**Comment by m2Giles** [comment]
Displaylink after today's build should not have the service enabled by default or evdi loaded by default.

Please let me know if you are still seeing this issue with an image dated after 20240513.
