### ISSUE TITLE
Add zfs to bluefin image

### ISSUE THREAD

**Issue by pypeaday** [ublue-os/bluefin#1283]
### Describe the package

Hello, thanks for the great work on this project, I'm excited to try it out. I forked the template repo and see this in `containerfile`

```bash
# SOURCE_IMAGE arg can be anything from ublue upstream which matches your desired version:
# See list here: https://github.com/orgs/ublue-os/packages?repo_name=main
# - "silverblue"
# - "kinoite"
# - "sericea"
# - "onyx"
# - "lazurite"
# - "vauxite"
# - "base"
#
#  "aurora", "bazzite", "bluefin" or "ucore" may also be used but have different suffixes.
ARG SOURCE_IMAGE="bluefin"

## SOURCE_SUFFIX arg should include a hyphen and the appropriate suffix name
# These examples all work for silverblue/kinoite/sericea/onyx/lazurite/vauxite/base
# - "-main"
# - "-nvidia"
# - "-asus"
# - "-asus-nvidia"
# - "-surface"
# - "-surface-nvidia"
#
# aurora, bazzite and bluefin each have unique suffixes. Please check the specific image.
# ucore has the following possible suffixes
# - stable
# - stable-nvidia
# - stable-zfs
# - stable-nvidia-zfs
# - (and the above with testing rather than stable)
ARG SOURCE_SUFFIX="-dx-nvidia"

```

But when I try to pull bluefin-stable-nvidia-zfs I get 403/4, which I think probably just amounts to this tag not being available. I see zfs in the ucore repo and I'm brand new so I'm not sure how all the image flow in and out of each other, but I'm a developer and would love to have zfs available in the base images that magically take care of nvidia and container setup too :D

I'll probably try to get it installed myself in the build script but for the time being wanted to request/ask if zfs in bluefin is a possibility?

### Image

Ubuntu

**Comment by castrojo** [comment]
This won't work today, the zfs stuff for ucore doesn't work in bluefin. 

This is something I'd love to do long term but it would depend on us using the coreos kernel, which is on the roadmap.

**Comment by pypeaday** [comment]
amazingly fast response! 

so in the time being can I ask for a recommendation? I'm a dev and I do a lot of stable diffusion + python stuff at home so I definitely want the Nvidia stuff and dev stuff all baked into an immutable image... question is, would it be feasible for me to build off the ucore image to get zfs and then setup the containerfile to install all the dev tools?
otherwise I might look for another storage solution since this project feels so promising!

**Comment by m2Giles** [comment]
Ucore is an excellent storage solution option.

If what you are looking for is a GUI, ucore comes with a web application called cockpit to manage your server.

Note, ucore doesn't support root on zfs at this time so your zpool needs to be at the bare minimum a different partition or more likely separate disks.

**Comment by m2Giles** [comment]
Work has started on shipping the coreOS Kernel.

**Comment by m2Giles** [comment]
CoreOS kernel is now being shipped.

GTS and Stable will have zfs included. We will build and include it; however, the coreOS kernel is a leading edge kernel and there may be the possibility that a kernel release occurs before a zfs release is made.

Follow this PR #1456

**Comment by xaque** [comment]
> GTS and Stable will have zfs included

Will there be separate "-zfs" tags, or stable tag will eventually include it?

**Comment by castrojo** [comment]
https://universal-blue.discourse.group/t/bluefin-and-aurora-3-0/2650

This is shipping now, ymmv, etc.
