### ISSUE TITLE
Install homebrew out of the box

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1290]
This is a tracking issue for getting a better homebrew experience. Ideal endstate is just to do it as part of the container build instead of a first-boot extra step. 

Then phase two will be slimming down the image and sourcing from brew packages instead where it makes sense to do so.

**Comment by m2Giles** [comment]
My idea is to see if we can do the same assumptions that we made for the original bluefin-cli setup.

**Comment by m2Giles** [comment]
Using testing branch to test out some ideas.

**Comment by m2Giles** [comment]
Working out of this PR now:
https://github.com/ublue-os/bluefin/pull/1293

Need to work on permissions

**Comment by m2Giles** [comment]
The pr is ready for local testing.

You can test brew on image by checking out the homebrew branch and you will need docker configured (or use rootful podman).

```
just build # build bluefin 39 container
just build-iso # build bluefin 39 iso
just run-iso # start qemu and install bluefin 39 iso
```
If you prefix the just commands with sudo when you don't have docker configured, it will run with rootful podman. To build the ISO you need a rootful privileged container. I recommend using the devcontainer which will use your systems docker socket.

**Comment by m2Giles** [comment]
Users can now brew install out of the box.
