### ISSUE TITLE
Sizes of applications are highly variable

### ISSUE THREAD

**Issue by cflewis** [ublue-os/bluefin#1291]
### Describe the bug

Applications bundled with Bluefin appear to be the right size, but some popular applications from Flathub display in different sizes. I am using Framework 13 screen at 100% scaling with Large Fonts on (as is now default).

 Zoom and Discord are the ones I have tried (see screenshot below). Both have enormous title bars. 

Zoom displays text at the size I would expect. Discord displays with enormous text as well. Turning Large Fonts off makes the window fit, but it's still rendering at what would appear to be 200% scaling, which it surely isn't allowed to choose to do all by itself...? If I go into its settings and scale it down to 0.5, low and behold, everything inside the viewport is the right size. Enormous title bars remain.

I don't have this issue with any of the Bluefin bundled apps (Firefox, Ptyxis, anything that comes with Gnome). I don't know it it's some sort of Flatpak thing, Fedora 40 thing, or something else.

### What did you expect to happen?

All apps have the same title bar size and text size within as those bundled with Bluefin.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:40
                   Digest: sha256:a0f41fac9cec2db4c3f43b262b51713ca1af5437e170bcd0cd32381308c04845
                  Version: 40.20240511.0 (2024-05-11T17:00:22Z)
                     Diff: 19 upgraded, 7 removed, 8 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:40
                   Digest: sha256:c7166f9b426c0be7bcea251ba8be1331c81796eedb4960947f53da5c34998d64
                  Version: 40.20240509.0 (2024-05-09T16:53:04Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:40
                   Digest: sha256:a2f10747da235b82ad3f6a8ca9a5a6798da175d1220e1afdff3b544854420e66
                  Version: 40.20240508.0 (2024-05-08T16:54:59Z)
```

### Output of `groups`

```shell
cflewis wheel
```

### Extra information or context

I have not tried this outside of Wayland. In the attached screenshot, we see that the Files app has a reasonable title bar size and the text on the left is the right size too (ignore the big text the empty directory warning has!). Zoom has the enormous title bar, but the text inside is OK if a little small (I doubt it is respecting the Large Fonts from Accessibility). Discord has enormous title bar _and_ enormous text as it's rendering at 200% scale.

![Screenshot from 2024-05-11 14-05-43](https://github.com/ublue-os/bluefin/assets/43708/b2d5ccdf-d3fc-44e2-b025-fd9b55db8915)

**Comment by m2Giles** [comment]
Try changing the size of the legacy title font size in gnome tweaks.

**Comment by cflewis** [comment]
Unfortunately legacy title font size appears to be gone: https://gitlab.gnome.org/GNOME/gnome-tweaks/-/issues/443 , so I'm not sure how to progress on the title bar issue. Discord itself is being finicky, I'll report back if I figure anything out on that side.

**Comment by cflewis** [comment]
OK, the best thing I have found thus far (after spending _far_ too much time on this installing extensions and uninstalling extensions and everything else) is to use ungoogled Chromium to add apps as a "Run in Window" shortcuts. That's made Discord far more tolerable than the Flatpak. Zoom is tolerable enough as it is because it's just running fullscreen anyway. The situation is however a bit of a PITA.

I'm going to leave this open as it would be nice to see if anyone else has any thoughts.

**Comment by cflewis** [comment]
For posterity, the issue with Discord's viewport correctly working with the Framework's resolution is this: https://www.reddit.com/r/discordapp/comments/6shs9n/comment/dld24oi/ The suggested fix by the dev + scaling the appearance in the app to 50% makes it look normal. Doesn't help with title bars in Gnome, but it now works correctly in KDE.

I'm now going to bed for real now :sleeping:
