### ISSUE TITLE
Scheduled ISO builds aren't getting uploaded

### ISSUE THREAD

**Issue by tobiasmicheler** [ublue-os/bluefin#1300]
### Describe the bug

Bluefin and Aurora build new ISOs every week, but the built ISOs are getting deleted after build. For expample see: https://github.com/ublue-os/bluefin/actions/runs/9048396123/job/24861397720
This is because in 
https://github.com/ublue-os/bluefin/blob/6b38313476623d90a1f672f909f72d179a5a34aa/.github/workflows/reusable-build-iso.yml#L183
and 
https://github.com/ublue-os/bluefin/blob/6b38313476623d90a1f672f909f72d179a5a34aa/.github/workflows/reusable-build-iso.yml#L199
the restriction github.event_name == 'workflow_dispatch' applies.

It seems wasteful to me to build ISOs and immediately delete them after.

### What did you expect to happen?

I expected either the ISOs to get uploaded, or not being built in the first place.

**Comment by m2Giles** [comment]
We had turned them off last week when there was an issue with including bootc.

We are respinning ISOs today.
