### ISSUE TITLE
Add a script to install InvokeAI to Ujust

### ISSUE THREAD

**Issue by RPGFSjosh** [ublue-os/bluefin#1310]
### Describe the package

I am suggesting/requesting that InvokeAI installation be added to ujust. Given that Ollama installation is included for user-focused LLM use, an image-generation tool with comparable polish seems appropriate. InvokeAI is fully featured with multiple modes of use, and it will even download the models for you.

[Invoke AI Repo](https://github.com/invoke-ai/InvokeAI)

![Screenshot from 2024-05-16 12-23-18](https://github.com/ublue-os/bluefin/assets/121073536/09ddbbce-d2b7-46b9-ad75-dbfc71e33834)

![Screenshot from 2024-05-16 12-24-11](https://github.com/ublue-os/bluefin/assets/121073536/cbe25e18-e2fc-4c77-ba32-4ea6fa6eec97)

![Screenshot from 2024-05-16 12-26-33](https://github.com/ublue-os/bluefin/assets/121073536/d6da5fe9-0edf-49d1-8ff0-ad34f14d6a35)

### Image

All Images

**Comment by p5** [comment]
There is currently no published InvokeAI Docker image, so it's not as easy to add this one.  There's an open issue for it though - https://github.com/invoke-ai/InvokeAI/issues/6318
