### ISSUE TITLE
Recommend a service management tool

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1320]
This would be a cool thing to add via a yafti option, JeremyGraeme had this:

![image](https://github.com/ublue-os/bluefin/assets/1264109/cee17402-6652-4f7c-ac18-9f193b8c3bcf)

https://extensions.gnome.org/extension/1804/sermon/

TThis tool also can show the containers and all the other stuff, this would be great, especially for app developers that need to just quickly bounce one of them.

**Comment by bketelsen** [comment]
hmm, nice!

**Comment by p5** [comment]
Looks very similar to https://github.com/ublue-os/packages/issues/22, but explicitly calls out containers.  
Although most of our containers run as systemd services anyway

**Comment by castrojo** [comment]
Mission Center has this built in.

**Comment by p5** [comment]
> Mission Center has this built in.

Unless I'm missing something, I cannot see any quadlets in Mission Center

**Comment by castrojo** [comment]
Yeah, I see what you mean. Do we wanna still try to do this or should we instead look at things like a dedicated applet for ollama, etc?
