### ISSUE TITLE
Make stock bluefin less container focused

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1321]
Note that I mean from a user experience perspective, not a technical level. Now that we have homebrew on the image we can do cooler stuff and gives us some new options that I think we should explore. `bluefin-dx` remains unchanged of course, this will be for our `bluefin` image that we give to our friends. 

First things first I'd like to:

- Remove Containers from the logo menu. 
- Remove boxbuddy
- Strongly de emphasize distrobox and containers in general. 

Let's keep all the container stuff in -dx, there's definitely an audience that loves this brew-first setup, and after trying every combination this one is the one that feels like the sweet spot. I've also totally moved to this model, I keep the devcontainers as part of my IDE and then I have everything else. Feels like we might be overrotating on the need to learn containers, it's supposed to be invisible anyway lol. 

When I need a distrobox we ship 2 keyboard shortcuts to ubuntu and fedora containers, and those get cleaned up every update. And all of those things will still be there, we just won't show them as part of the default experience.

**Comment by Malix-off** [comment]
Are there any GUI to manage homebrew packages?
Also, one-click install `.deb` packages with BoxBuddy felt very user and noob friendly

**Comment by tulilirockz** [comment]
Is this still of interest? Would be a lot easier to do now after the default container purge

**Comment by tulilirockz** [comment]
Everything mentioned here seems to be addressed by now? And boxbuddy also seems like a pretty nice entrypoint for the "how to container" things

**Comment by castrojo** [comment]
I'll close this for now, let's reinvestigate at a later date.

**Comment by Malix-Labs** [comment]
_@castrojo wouldn't closing as not planned be better for now?_
