### ISSUE TITLE
 aurora-dx-nvidia  /  bluefin-dx-nvidia Version Not Updating Daily For latest / 40 

### ISSUE THREAD

**Issue by Mortifier13** [ublue-os/bluefin#1322]
### Describe the bug

For the last several days, the versions have been showing the same  40.20240513.0.  Looking at the daily images for latest/40/40-20240517, the manifest shows under labels -  "org.opencontainers.image.version": "40.20240513.0" (Example - https://github.com/ublue-os/bluefin/pkgs/container/aurora-dx-nvidia/217732600?tag=latest)

### What did you expect to happen?

This appears to be the case for both  aurora-dx-nvidia  /  bluefin-dx-nvidia versions but not the non-nvidia versions.  There appears to be package updates daily but the version does not change.

### Output of `rpm-ostree status`

```shell
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 0)
                   Digest: sha256:e51b5010809dccaba808cb917db6f3771e6e2879e89daadc1034dd05950c3260
                  Version: 40.20240513.0 (2024-05-17T16:55:35Z)
                   Commit: 1c310ef7b30f03972bdd2efcbae7833d360ec4a8049557c3320e1ada589509bc
                   Staged: yes
                StateRoot: default
                 Upgraded: kcli 99.0.0.git.202405161147.1f9eaa5-0.fc40 -> 99.0.0.git.202405171406.e83ee2a-0.fc40

● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 1)
                   Digest: sha256:63403d49032de89a99243a521a0965f7eee758b082c785e7590efe72e98345cd
                  Version: 40.20240513.0 (2024-05-16T22:00:15Z)
                   Commit: 80b9b99456dabc546c1c063d552981b62626250c79bc61759d4c41562b134c39
                StateRoot: default
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 2)
                   Digest: sha256:2465f9988cb9b28f4caf9d793ad2c884046b49762e11c139f5460bbdd299d001
                  Version: 40.20240513.0 (2024-05-16T02:08:54Z)
                   Commit: d3d0079811c8b6a011109ab26794565311b28cc89a201bd565b78c9471564939
                StateRoot: default
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 3)
                   Digest: sha256:9d24df23018c2167ddaf888a7eae04f48e70aa44df3beb3d08b4576ed28b2a9b
                  Version: 40.20240513.0 (2024-05-14T16:54:35Z)
                   Commit: 1a100a9c8ca24aac87f73b937676b8f00f88ac825e838fdd9a0233ccb79c5341
                StateRoot: default
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 4)
                   Digest: sha256:0e712738a323008dc26b14ce10f855649c252128a51c7575ad11ed353cd5762c
                  Version: 40.20240513.0 (2024-05-13T18:07:08Z)
                   Commit: f772481096ccdc28e764b2c428bf331e0ac547bdfdb76962b01faf875cc9cd93
                StateRoot: default
                   Pinned: yes
```

**Comment by p5** [comment]
Unfortunately the Nvidia builds are failing due to mismatches in the upstream Fedora packages and RPMFusion packages.  There's not much we can do about it, but they tend to work themselves out after a few days.  

I know it's not ideal, but it's better that it's not failing on your local system during upgrades 😄

**Comment by castrojo** [comment]
These are caught up now: `"org.opencontainers.image.version": "40.20240520.0"`

**Comment by Mortifier13** [comment]
aurora-dx-nvidia:latest is not updating again and is still stuck on 2024-07-02 name image as of tonight even after the recent key update, it doesn’t look like it is updating daily.

https://github.com/ublue-os/bluefin/pkgs/container/aurora-dx-nvidia

❯ rpm-ostree status -v
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 23h ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 0)
Digest: sha256:887bf42d1e0c06caac59e24c393202559243bafbc2a4f7ad63b64ca2e62a4f3e
Version: 40.20240702.0 (2024-07-03T04:52:41Z)
Commit: 00f78a22113bd435c7c2cc0aee14a715fa0818634a89845ecf0003a47aff5ab3
Staged: no
StateRoot: default

❯ rpm-ostree upgrade
note: automatic updates (stage) are enabled
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest
No upgrade available.

**Comment by p5** [comment]
Yeah, the builds are failing again due to more mismatches between upstream projects.
Unfortunately there's not much we can do about it, and it'll sort itself out eventually.

This usually happens for a few days whenever there's a new kernel available.
