### ISSUE TITLE
kdeglobals file has invalid contents

### ISSUE THREAD

**Issue by notnotno** [ublue-os/bluefin#1323]
### Describe the bug

The current contents of system_files/kinoite/usr/etc/xdg contains the following text:
`../../../usr/share/kde-settings/kde-profile/default/xdg/kdeglobals`

### What did you expect to happen?

The content of system_files/kinoite/usr/etc/xdg should contain something like this:
```
[KDE]
LookAndFeelPackage=dev.getaurora.aurora.desktop
SingleClick=false
ColorScheme=BreezeDark
widgetStyle=Breeze

[KDE Control Module Restrictions][$i]
kcm_plymouth.desktop=false

[General]
TerminalApplication=kde-ptyxis
TerminalService=org.gnome.Ptyxis.desktop
desktopFont=Noto Sans,10,-1,5,50,0,0,0,0,0
fixed=FiraCode Nerd Font,10,-1,5,50,0,0,0,0,0
font=Noto Sans,10,-1,5,50,0,0,0,0,0
menuFont=Noto Sans,10,-1,5,50,0,0,0,0,0
smallestReadableFont=Noto Sans,8,-1,5,50,0,0,0,0,0
toolBarFont=Noto Sans,9,-1,5,50,0,0,0,0,0
```

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 36min ago
Deployments:
● ostree-unverified-registry:ghcr.io/notnotno/aurora-dx-nvidia:latest
                   Digest: sha256:9618110833689a51883dc35408af52889a20081889b5a71b472220a51bdee2b5
                  Version: 40.20240513.0 (2024-05-18T04:40:57Z)

  ostree-unverified-registry:ghcr.io/notnotno/aurora-dx-nvidia:latest
                   Digest: sha256:ac10212ccf95660718bd58547aa1ad6b7336c7880453b8ce1f543e94b28de3a8
                  Version: 40.20240513.0 (2024-05-17T16:59:28Z)
```

### Output of `groups`

```shell
myname wheel lxd incus-admin libvirt docker
```

**Comment by KyleGospo** [comment]
That's a symlink

**Comment by KyleGospo** [comment]
![SmartSelect_20240518_094457_GitHub.png](https://github.com/ublue-os/bluefin/assets/10704358/f6ff2e9f-50ac-493b-9616-4b93cb96f49e)

The arrows denote a symlink. Please provide the contents of that file on a running system.

**Comment by m2Giles** [comment]
They are supposed to be symlinks:
![image](https://github.com/ublue-os/bluefin/assets/69128853/ff9b2625-c5fc-4843-916d-f1b865228cf9)
![image](https://github.com/ublue-os/bluefin/assets/69128853/6dd28763-efc9-4755-89bb-cb824cabc580)

**Comment by KyleGospo** [comment]
> Thanks, it seems to be a bug with KDE's Ark not preserving symbolic links:  https://bugs.kde.org/show_bug.cgi?id=415723.

These are relative links, if you're downloading a zip they're likely to be linked to the wrong location.
