### ISSUE TITLE
HDMI monitor not responsive 

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/bluefin#1328]
### Describe the bug

HDMI monitor is not responsive (power light unchanged either) 

### What did you expect to happen?

A working HDMI monitor

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:2c4a1b9f415dd89d88d23bc53fafae54fb374d3f04371d9cb68a4ec26c47ec3d
                  Version: 39.20240517.0 (2024-05-19T01:42:22Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:9c5fec8c500736d313e53fdb4198025b1d71e49efc1baf4288832508e1999987
                  Version: 39.20240517.0 (2024-05-19T01:42:22Z)
```

### Output of `groups`

```shell
❯ groups
malix wheel
```

### Extra information or context

Fresh install (bluefin-dx-nvidia)

Lenovo Legion 5
AMD Ryzen 7 5600H
NVIDIA GeForce RTX 3060 Laptop

**Comment by Malix-off** [comment]
Maybe it has to do with that
![image](https://github.com/ublue-os/bluefin/assets/76160668/d5144cf6-5330-4f4b-b3f0-1a2fead884d6)

**Comment by Malix-off** [comment]
Oh boy

![image](https://github.com/ublue-os/bluefin/assets/76160668/d310ae56-2117-4440-96f2-b4598f8bafcd)

**Comment by Malix-off** [comment]
![image](https://github.com/ublue-os/bluefin/assets/76160668/cd9a58ce-9ab1-4c08-803b-049b08a24400)

**Comment by Malix-off** [comment]
![image](https://github.com/ublue-os/bluefin/assets/76160668/8a5b0fc9-3fb5-4252-b79c-33af2d8b3edf)

**Comment by KyleGospo** [comment]
You don't have our secure boot key enrolled so none of our kernel modules can load.

This is not causing your issue though, just producing these errors.

**Comment by m2Giles** [comment]
Is the display detected by your display configurator?

Does the monitor say no signal detected when manually powered on?

**Comment by Malix-off** [comment]
@KyleGospo 
> You don't have our secure boot key enrolled

Following https://universal-blue.discourse.group/t/bluefin-administration-guide/40 indeed worked, I might have missed that documentation step, thanks!
