### ISSUE TITLE
Downloading a 'try it' image (other brands, developer, Intel) from website yields a Fedora 39 based iso, and not a Fedora 40 based iso.

### ISSUE THREAD

**Issue by mogwaidao** [ublue-os/bluefin#1333]
### Describe the bug

Downloading a 'try it' image (other brand, developer, Intel) from website yields a Fedora 39 based iso, and not a Fedora 40 based iso.

### What did you expect to happen?

When downloading an image from the website, the expectation is to download the latest iso (-latest, major stable release), consistent with the other 'Try' download options.

### Output of `rpm-ostree status`

```shell
Not needed in this case.

Just look at the download file name (bluefin-dx-gts.iso). The other downloadable images are post-fixed with -latest indicators, which suggest this is just an reference update oversight on the webpage.

Additionally, I have confirmed the downloaded image indeed installs a Fedora Silverblue 39 based image on first boot. A subsequent reboot of same machine after auto updates then takes the machine to 40 latest.
```

### Output of `groups`

```shell
Not needed in this case.
```

**Comment by maxexcloo** [comment]
Had this issue also, an update doesn’t seem to update to Fedora 40 either…

**Comment by p5** [comment]
We prefer to ship the most stable version by default, which is GTS.  GTS is one version older than the latest available.  It tends to be more reliable and moves slower, which is a good thing for most users.

Users who wish to use the absolute latest version of Fedora can download the ISO by manually updating the URL (replacing "gts" with "latest").

E.G.
https://download.projectbluefin.io/bluefin-gts.iso -> https://download.projectbluefin.io/bluefin-latest.iso

**Comment by castrojo** [comment]
Rebasing instructions here: https://universal-blue.discourse.group/docs?topic=40#upgrades-and-throttle-settings-8

**Comment by tunix** [comment]
> Users who wish to use the absolute latest version of Fedora can download the ISO by manually updating the URL (replacing "gts" with "latest").

IMO, this should be more visible on the site. Not everyone may be familiar with the term GTS. I was looking for a way to download the latest ISO and found this thread.

**Comment by castrojo** [comment]
`bluefin:stable` and `bluefin-dx:stable` exist now and it's the latest Fedora with a bit of a delay. I'm much more comfortable exposing this channel than `latest`, and we should add this to the website. 

If anyone has ideas on wording, target audience will be enthusiasts who want to be on latest Fedora. GTS is the minivan, this would be the sports car.

**Comment by tunix** [comment]
Hi @castrojo , I may have got you wrong. So just to clarify, how much of a delay are we talking about for GTS? Fedora 40 was released on April and we're in June. Do GTS users have to wait for Fedora 41 to have Fedora 40 or do you plan to have a different cadence?

**Comment by castrojo** [comment]
GTS will always be fedora -1, so that won't move to F40 until latest moves to F41 in October. We're introducting a `stable` tag that will sit inbetween latest and gts: 

https://universal-blue.discourse.group/t/call-for-testing-stable-branch-for-bluefin-aurora/2530/5

**Comment by tunix** [comment]
Is there an ISO for stable channel? https://download.projectbluefin.io/bluefin-stable.iso doesn't seem to work.

**Comment by m2Giles** [comment]
Not yet. We are actively working on this.

**Comment by tunix** [comment]
I just found out that this link now works: https://download.projectbluefin.io/bluefin-dx-stable.iso 💯

**Comment by castrojo** [comment]
If we can get a Flatcar style table thing we can put that on the website to advertise the channels and then people will be able to just pick and choose what they want:

https://github.com/ublue-os/main/issues/594

**Comment by castrojo** [comment]
Nice try bot lol. This will be solved when we add the stable images to the website, so just closing this now.
