### ISSUE TITLE
Solaar launch at startup but is not listed in gnome tweaks startup apps

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/bluefin#1337]
### Describe the bug

Solaar launch at startup but is not listed in gnome tweaks startup apps

### What did you expect to happen?

To be able to make Solaar not launch at startup and having it be listed in the gnome tweaks startup apps

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 8h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:3cbe7ef4077fe931769b42232fed59692991a3649d009fb6eb60cb1eec56891b
                  Version: 40.20240521.0 (2024-05-21T16:53:08Z)
                     Diff: 3 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:bc65a31ca851f2d6abdf6af833f079b634e2bd86549503f325ccb4e08bb56e1d
                  Version: 40.20240520.0 (2024-05-20T22:10:57Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:ca2e8767e525d12af07e06c302274d4e328c832a0798487b403fe3c6d19dcae7
                  Version: 40.20240518.0 (2024-05-19T16:56:29Z)
```

### Output of `groups`

```shell
❯ groups
malix wheel
```

**Comment by itskhanow** [comment]
I agree that it should be more discoverable for an end user, but in the meantime you can remove `/etc/xdg/autostart/solaar.desktop`

If you decide you want it back you can find the desktop file at `/usr/etc/xdg/autostart/solaar.desktop` and just copy it back to the above location.

**Comment by m2Giles** [comment]
Correct. Gnome tweaks only shows the contents of ~/.config/autostart. The system level autostart is /etc/xdg/autostart.

**Comment by Malix-off** [comment]
Ohkay

Can someone provide a step-by-step guide to do that in an idiomatic way?

**Comment by castrojo** [comment]
`sudo rm /etc/xdg/autostart/solaar.desktop` should do it.

**Comment by Malix-off** [comment]
Is there a command to add it back?

**Comment by m2Giles** [comment]
Copy it from /usr/etc/xdg
