### ISSUE TITLE
Feature: Add Stable Diffusion with ComfyUI to ujust

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/bluefin#1341]
We currently have things like Ollama and InvokeAI available in ujust. It would be really awesome to include a ujust command for creating a quadlet to run Stable Diffusion and ComfyUI.

**Comment by noelmiller** [comment]
@castrojo found this: https://github.com/AbdBarho/stable-diffusion-webui-docker?tab=readme-ov-file

We likely could just create a quadlet from this and go from there.

**Comment by lslowmotion** [comment]
@noelmiller Here is my repo [here](https://github.com/lslowmotion/stable-diffusion-webui-podman). I think it would be more suitable for Podman environment like we have in bluefin.

**Comment by castrojo** [comment]
Oh yeah, that's looking really dope!

**Comment by remggo** [comment]
What does work great as well, is installing [SwarmUI](https://github.com/mcmonkeyprojects/SwarmUI), which uses ComfyUI as a backend locally onto the machine as ROCm is installed anyway. This saves around 60GB of ROCm Containers. Only caveat: One needs to do a `brew install dotnet` to make swarmui function on Bluefin.
