### ISSUE TITLE
Can't use aurora as source image.

### ISSUE THREAD

**Issue by proJM-Coding** [ublue-os/bluefin#1342]
### Describe the bug

`ARG SOURCE_IMAGE="aurora"` doesn't work and gives the error:
```
Error: buildah exited with code 125
Trying to pull ghcr.io/ublue-os/aurora-main:latest...
error creating build container: initializing source docker://ghcr.io/ublue-os/aurora-main:latest: Requesting bear token: invalid status code from registry 403 (Forbidden)
time="2024-05-24T01:29:03Z" level=error msg="exit status 125"
```

Using bluefin works fine though.

### What did you expect to happen?

The github action passes and makes a github package.

### Output of `rpm-ostree status`

```shell
N/A
```

### Output of `groups`

```shell
N/A
```

### Extra information or context

Unsure if I should put this here or the image-template repo.

**Comment by castrojo** [comment]
The image name is `aurora` not `aurora-main`, maybe we need to adjust the image template? cc @noelmiller

**Comment by proJM-Coding** [comment]
Thanks for that! I didn't notice the `aurora-main` in the error because I was looking at the error code `403` on the third line. I will close the issue.
