### ISSUE TITLE
Xbox Controller 1708 not working in programs (bottles/steam/...)

### ISSUE THREAD

**Issue by Destro706** [ublue-os/bluefin#1343]
### Describe the bug

The xbox controller doesn't get input in applications.
With evtest and Input Remapper it's working.
It's shown in Steam Controller settings but the keys doesn't work.
It starts to work fine after applying the workaround (see extra information).

### What did you expect to happen?

The controller should work without applying the workaround after reboot

### Output of `rpm-ostree status`

```shell
ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:1c7d83efe53b07402964f4092b19de126d6e9848bdd1d63319cf344d9294dc3b
                  Version: 39.20240523.0 (2024-05-23T16:53:06Z)
          LayeredPackages: langpacks-de
```

### Output of `groups`

```shell
saschalemke wheel docker incus-admin lxd libvirt
```

### Extra information or context

Seems to be a problem with xpadneo. (ACL)
The device is working fine in regular Silverblue with default driver.

The permissions for the hidraw looks like this:

❯ getfacl /dev/hidraw8
getfacl: Entferne führende '/' von absoluten Pfadnamen
# file: dev/hidraw8
# owner: root
# group: root
user::rw-
group::rw-
other::rw-

It works in evtest as expected but doesn't work in applications.

After revoke the permissions for hidraw:

sudo chmod a-rwx /dev/hidraw8

❯ getfacl /dev/hidraw8
getfacl: Entferne führende '/' von absoluten Pfadnamen
# file: dev/hidraw8
# owner: root
# group: root
user::---
group::---
other::---

the Controller works perfectly fine in the applications.

**Comment by rferris** [comment]
Having the same issue. Have included udev log, hoping someone more skilled than I can understand which rule is causing the problem.
[udevadm monitor p monitor.txt](https://github.com/user-attachments/files/16536161/udevadm.monitor.p.monitor.txt)

**Comment by rferris** [comment]
I'm not 100%, but it looks like 92-viia.rules might be the culprit:
```
❯ cat 92-viia.rules
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666", TAG+="uaccess", TAG+="udev-acl"
```

I'm no udev expert, but my understanding is this is setting permissions on any hidraw device, regardless of manufacturer?

**Comment by Destro706** [comment]
Since xpadneo is removed from the image I face no more issues and the controller works now as expected.

Thank you very much
