### ISSUE TITLE
Bluefin-cli requires some unknown password

### ISSUE THREAD

**Issue by LogExE** [ublue-os/bluefin#1354]
### Describe the bug

When I'm trying to create a bluefin-cli container, it asks for password. I tried using my default user (devoops) password, it doesn't seem to work
![Screenshot from 2024-05-28 23-48-45](https://github.com/ublue-os/bluefin/assets/27575516/8bd2cbfc-d3a1-4bec-adff-dc2b89191f58)

### What did you expect to happen?

I expected bluefin-cli to start right away

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 12h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:efc2e4211887133a0159c77718efb930a25b1513fa71dbdbdfd9afcd5ddad874
                  Version: 39.20240527.0 (2024-05-28T04:14:19Z)

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:9d3ea78c7ea224dd7697b3e1f0441e36c6a2451a1a3ceb431b0fa1548388ab06
                  Version: 39.20240527.0 (2024-05-27T16:53:48Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:a21a58edf1a441d325a12d9985ac339aacd4b6254a7457f11593a3663b464d7f
                  Version: 39.20240526.0 (2024-05-26T18:48:27Z)
```

### Output of `groups`

```shell
❯ groups
devoops wheel docker incus-admin lxd libvirt
```

**Comment by LogExE** [comment]
Issue is gone after a reboot. Maybe this issue can be closed then

**Comment by m2Giles** [comment]
This can occur if the /etc/sudoers.d/sudoers file is not created properly. bluefin-cli uses sudo to setup things. If sudo is not configured to work without a password this obviously will fail.

At this time the bluefin-cli is working correctly.

**Comment by LogExE** [comment]
> This can occur if the /etc/sudoers.d/sudoers file is not created properly. bluefin-cli uses sudo to setup things. If sudo is not configured to work without a password this obviously will fail.
> 
> At this time the bluefin-cli is working correctly.

Yes, /etc/sudoers.d/sudoers doesn't exist on host. Where can I find contents of the file for copying?

**Comment by LogExE** [comment]
It does exist on a recreated container where setup is failed though. See the picture
![Screenshot from 2024-06-10 17-02-47](https://github.com/ublue-os/bluefin/assets/27575516/2eca0f8d-75c4-42fb-99c5-39b163e83db1)

**Comment by m2Giles** [comment]
That appears to be the correct contents of the file.

Please try repulling the container image and recreating the container.

**Comment by m2Giles** [comment]
Have you pulled the latest image?

**Comment by LogExE** [comment]
Sorry, I no longer use Bluefin, so I can't try your advise. Maybe someone else could see if pulling latest image helps, but I'm pretty sure I did have latest image back when figuring out the issue
