### ISSUE TITLE
No hibernation

### ISSUE THREAD

**Issue by DarkGhostHunter** [ublue-os/bluefin#1358]
### Describe the bug

On the power options, there is no hibernation available, only lock, sleep and shutdown.

### What did you expect to happen?

To have hibernation (even on a desktop).

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1h 59min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:e55c75c5b08e5725ab73d8d8fd82a5dde8ba24d59c0c3a921cfb73770615b4f6
                  Version: 40.20240530.0 (2024-05-30T17:09:59Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:199270f406be436fcb6847ce9424313bda68b2f6318a2d2c8aef4523a4cb608d
                  Version: 40.20240528.0 (2024-05-28T16:52:43Z)
```

### Output of `groups`

```shell
superman wheel docker incus-admin lxd libvirt
```

### Extra information or context

It should be available on a desktop and laptops. I don't know if a desktop is considered "un-hibernable", but anyway, it's kind of a pain to re-arrange whole workflows all over again the next day.

**Comment by castrojo** [comment]
Fedora doesn't support hibernation, there's not much we can do here.

**Comment by KyleGospo** [comment]
Important to note as well that this is for security reasons.

**Comment by DarkGhostHunter** [comment]
> Important to note as well that this is for security reasons. Especially important on a laptop.

I assume that is for dumping the RAM content into an unencrypted partition.

> Fedora doesn't support hibernation, there's not much we can do here.

Does it support deep sleep?
