### ISSUE TITLE
Ptyxis as Flatpak

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/bluefin#1361]
Ptyxis was released as a flatpak [on Flathub 23 days ago](https://flathub.org/apps/app.devsuite.Ptyxis#:~:text=version%2046.2,days%20ago)

![image](https://github.com/ublue-os/bluefin/assets/76160668/a40e9144-9565-4ff7-bfc9-a831f3f3571d)

If it doesn't remove functionalities or introduce bugs, it would be a good idea to remove Ptyxis as a base package and use the flatpak version instead

**Comment by KyleGospo** [comment]
This removes functionality unfortunately

**Comment by Malix-off** [comment]
- [Comment](https://github.com/ublue-os/bluefin/issues/1361#issuecomment-2143637425) from @KyleGospo :

	> This removes functionality unfortunately

	Oh, okay	
	Is there any documentation about it?

**Comment by KyleGospo** [comment]
> - [Comment](https://github.com/ublue-os/bluefin/issues/1361#issuecomment-2143637425) from @KyleGospo :
> 
> 	> This removes functionality unfortunately
> 
> 	Oh, okay	
> 	Is there any documentation about it?

Our solution for changing the default terminal would need to be modified and the plugin for replacing the nautilus shortcut doesn't support this yet. We'd also need to force install this for existing users which would require a network connection, and leave them in a position to uninstall their terminal.

**Comment by Malix-off** [comment]
- [Comment](https://github.com/ublue-os/bluefin/issues/1361#issuecomment-2143640334) from @KyleGospo :

	> Our solution for changing the default terminal would need to be modified and the plugin for replacing the nautilus shortcut doesn't support this yet. We'd also need to force install this for existing users which would require a network connection, and leave them in a position to uninstall their terminal.

	Understandable

	> yet

	Does that mean that after this blocker has been resolved, the switch to platpack will be considered?

- [Comment](https://github.com/ublue-os/bluefin/issues/1361#issuecomment-2143639279) from @Malix-off :

	> [⋯](https://github.com/ublue-os/bluefin/issues/1361#issuecomment-2143639279) Is there any documentation about it?

	Is there any documentation about the broken functionality in the Ptyxis Flatpak compared to the base package Ptyxis?

**Comment by KyleGospo** [comment]
The issue is not in Ptyxis. My opinion is that we should not consider the flatpak.

**Comment by KyleGospo** [comment]
The issue is not in Ptyxis. My opinion is that we should not consider the flatpak.

**Comment by Malix-off** [comment]
The main blocker for that issue is

> the plugin for replacing the nautilus shortcut doesn't support this yet

Right ?

If so, is there any issue in Flatpak / Flatseal / the nautilus shortcut repo to track it ?
