### ISSUE TITLE
Shell startup is slow (brew completions)

### ISSUE THREAD

**Issue by catdevnull** [ublue-os/bluefin#1363]
### Describe the bug

In `/usr/share/fish/vendor_conf.d/brew.fish` (and other paths for other shells), `brew completions link` gets called. However, this is very slow (~1sec) and delays shell startup.

### What did you expect to happen?

Shell starts up quickly.

**Comment by m2Giles** [comment]
Brew completions should only link if the link is not present.

**Comment by m2Giles** [comment]
Removed the completions link.
