### ISSUE TITLE
VSCode Settings Sync is broken

### ISSUE THREAD

**Issue by Moneydollar** [ublue-os/bluefin#1367]
### Describe the bug

So, I have a fresh install of the Project Bluefin ISO installed on my laptop. My problem is that when I attempt to enable Settings Sync in VSCode, I select "sign in with GitHub" and instead of opening the login page in Firefox, it opens a HTML document in gedit. 

### What did you expect to happen?

I expect that when I select sign in with GitHub on the VSCode settings sync dialog, a web browser page will open displaying the GitHub login page.

### Output of `rpm-ostree status`

```shell
rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:177270853492a06d0fc096ce342a3ff5f076c9fbdc834cbee94f71efd3f94086
                  Version: 39.20240603.0 (2024-06-03T17:06:18Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:gts
                   Digest: sha256:ccc5ae93cfcf923daa60184d79c03190e91e6cdb32f2c6567402c6ab774c159f
                  Version: 39.20240601.0 (2024-06-01T18:11:31Z)
```

### Output of `groups`

```shell
groups
cashc wheel
```

**Comment by adrian-herscu** [comment]
Cannot change the default Web application, nor other default applications, in Settings :(

**Comment by vibuz** [comment]
I was not able to replicate this with version 40.20240531.0

**Comment by vibuz** [comment]
Trying a few more variations, I've been able to replicate this in `bluefin-dx-nvidia:gts` (The original posters version), `bluefin-dx:gts` and `bluefin:gts`. It doesn't seem to affect any of the `:latest` images.

In `:latest`, Firefox gets correctly set as the default web browser while in `:gts`, this is left unset.

**Comment by vibuz** [comment]
I was not able to replicate this in the latest build of Silverblue 39.
```
State: idle
Deployments:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240605.0 (2024-06-05T01:01:47Z)
                   Commit: 7f432f6695e3c9faeda0974b5cf8032311bbe7cf7d6ba3a316234c703f2547e8
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
```

**Comment by vibuz** [comment]
Probably related to https://github.com/ublue-os/bluefin/issues/1076

**Comment by vibuz** [comment]
The "solution" here is to install some kind of flatpak, doesn't matter which one. This will trigger a refresh of all the default apps which will make Firefox the default web browser, and VSCode should then behave correctly.

**Comment by adrian-herscu** [comment]
Maybe this helps...
```
rpm-ostree status 
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 3h 0min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:b3c7cfe3bd106a50189ab540678dd37a842ecf615504df8668d7af2e709440e4
                  Version: 39.20240604.0 (2024-06-04T16:53:16Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:887caf4a03eb2e0f3b87d76620422920ea2234e86919129e966bf0ab2254e01a
                  Version: 39.20240603.0 (2024-06-03T17:06:55Z)
```
After installing the Google Chrome flatpak, it correctly registred as the default Web browser, and all default applications under Settings became editable.
