### ISSUE TITLE
Some Yaru themes have a different name than the ones in flathub.

### ISSUE THREAD

**Issue by alfaroale** [ublue-os/bluefin#1379]
### Describe the bug

If i set my gtk theme to Yaru-blue (b in lowercase) and then i run flatpak update, it doesn't download the theme because the name in flathub is Yaru-Blue (B in uppercase). Because of this, yaru-blue doesn't get applied automatically to my flatpaks.

### What did you expect to happen?

This yaru theme comes included in the image, so i think they should sync well with your flatpaks.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:57aab5bdd11517027cdfc548e2761ffd2edaadd0a488abf4c10d01dae0598eaf
                  Version: 40.20240608.0 (2024-06-08T16:51:01Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:gts
                   Digest: sha256:214048d32908eec23e039ec2d70b91ffa9b1aa6e85feeba5b10a4c7f3f335e63
                  Version: 39.20240607.0 (2024-06-08T14:37:20Z)
```

### Extra information or context

I didn't download any theme, i experience this with the yaru themes included in the image. I also found that not every yaru theme in flathub are in uppercase.

I downloaded Yaru-Blue theme from flathub and use flatseal to applied it to my flatpaks.

Sorry for my bad english.

**Comment by m2Giles** [comment]
That works for applying the theme.

Unfortunately we do not control the naming for the Fedora rpms or Flatpaks. You can file a bug report on Flatpak that the gtk theme name doesn't match.
