### ISSUE TITLE
Visual Studio Code Crashing right after start

### ISSUE THREAD

**Issue by spacimek** [ublue-os/bluefin#1396]
### Describe the bug

I was using VSCode since quite some weeks without any issue. Today, when starting it, it reopens my 3 windows and after a few seconds disappears - no error.

### What did you expect to happen?

I expect VSCode to stay along with my files :)

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:e5f417316d973b9989b023e07027cc4ed484e53378fed6c19525a749c792cf3a
                  Version: 40.20240613.0 (2024-06-14T16:53:05Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:85f5962a9bac172e8e67ce2bccb4580eb51fd5c18bb00059a8b14a1cba029d28
                  Version: 40.20240611.0 (2024-06-11T16:52:09Z)
```

### Output of `groups`

```shell
❯ groups
me wheel docker incus-admin lxd libvirt
```

### Extra information or context

Initial problem seems to start with 40.20240611.0 and upgrade to the latest one doesn't seem to help. I am not sure how can I debug or even when the logs are stored, so I can see whether it's some extension, or VSCode itself. If I understood well, it's on the image, but not sure how:
- certainly not part of OS (also there's nothing in journalctl -xe)
- I don't see it with brew
- and it's not coming from Flatpak (there they offer me their own version)

Any thoughts on where else I can check?

**Comment by castrojo** [comment]
Can you run `code` in a terminal and see if it spits out an error?

**Comment by spacimek** [comment]
`code` itself gives nothing. 

`code --verbose` is giving these errors:
...
[0615/005633.801618:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0615/005633.802373:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0615/005633.802657:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0615/005633.810505:ERROR:directory_reader_posix.cc(43)] opendir /home/smi/.config/Code/Crashpad/attachments/a1572f27-3a84-40dd-9675-d22764fe3ec2: No such file or directory (2)

`code --version`
1.90.1
611f9bfce64f25108829dd295f54a6894e87339d
x64

Quick digging suggests it's really VSCode issue...

**Comment by m2Giles** [comment]
This is an issue with vscode. The only thing you can try locally is deleting your ~/.cache and the vscode state/configure files and hope for the best.

You can also create another use to see if it is something in your homedir causing the issue

**Comment by MuchHustle** [comment]
I have same problem except it's when I try to launch "code" from within bluefin-cli terminal. It immediately crashes with error code 132.. Should I just use the vs code that came preinstalled and connect to bluefin-cli as remote dev container?

**Comment by fonnesbeck** [comment]
I'm getting this as well. Clicking "repoen" results in another crash. Only closing and re-opening code (either from the command line or the doc) results in a persistent window. This appears to occur after reboot.

**Comment by spacimek** [comment]
For me what worked was to delete `~/.config/Code`. It was maybe too harsh, but didn't have any issue since. When I was reading about similar issues with other OSes, they recommended just to delete:

>  ~/.config/Code/Cache/
>  ~/.config/Code/CachedData/

So you can start with those. As a next step you can remove remaining caches, i.e. `rm -rf  ~/.config/Code/*Cache*`

Obviously I also updated my OS in the meantime, I believe there were 2 patches for VS Code in the meantime, so that could have helped also.
