### ISSUE TITLE
[Improvement suggestion] Simple command to check the ostree update details

### ISSUE THREAD

**Issue by spacimek** [ublue-os/bluefin#1401]
Unless I missed something, we don't have any easy command that would show us what would be updated once an update is available. That can give a hint of the urgency of the update, or simply checking whether awaited update is included. 

`rpm-ostree status` is giving just generic idea, i.e.:
>                      Diff: 54 upgraded, 6 added

It would be nice to have a bit more specific command, something like `ujust check-update`.

I don't think it should be complicated - what I like to see it something like [this suggestion](https://github.com/coreos/rpm-ostree/issues/1953#issuecomment-565111304). 

Giving:

> Upgraded:
>   amd-gpu-firmware 20240513-1.fc40 -> 20240610-1.fc40
>   amd-ucode-firmware 20240513-1.fc40 -> 20240610-1.fc40
>   atheros-firmware 20240513-1.fc40 -> 20240610-1.fc40
> ...
> Added:
>   argyllcms-3.2.0-1.fc40.x86_64
>   argyllcms-data-3.2.0-1.fc40.noarch
> ...

**Comment by m2Giles** [comment]
You can view with `ujust changelogs` or `rpm-ostree db diff --changelogs`
