### ISSUE TITLE
The systemd-tmpfiles service on Fedora is failing to resolve the 'systemd-journal' group, resulting in multiple errors in the systemd configuration file

### ISSUE THREAD

**Issue by Mystrain308** [ublue-os/bluefin#1407]
**Details:** Upon executing ujust log-this-boot alias to sudo journalctl -b 0, this appear in my logs. 
![image](https://github.com/ublue-os/bluefin/assets/105970725/fd230667-8e1c-4570-bf86-ff17eecbcd0c)

**Steps to Reproduce:**
1. Boot the bluefin-nvidia system. (i think is valid for all ublue images)
2. Run the command `ujust log-this-boot` to view the logs for the current boot.
3. Observe the errors related to the `systemd-journal` group in the log output.

**Expected Behavior:** The systemd-tmpfiles service should resolve the 'systemd-journal' group without any errors.

**Actual Behavior:** The systemd-tmpfiles service fails to resolve the 'systemd-journal' group, resulting in multiple errors in the system logs.

**Device Info:** https://paste.centos.org/view/4f34addd

**Comment by m2Giles** [comment]
This is not a file modified by ublue. You'll see that if the systemd-journal group is not present when systemd.conf tmpfile is run, it will instead use acls to give access to other admin groups. This is how fedora has it configured.
