### ISSUE TITLE
Zenity or kdialog is required for graphical rootful distrobox apps

### ISSUE THREAD

**Issue by dtg01100** [ublue-os/bluefin#1410]
Creating a distrobox that needs to be rootful, a good example would be following the instructions on the distrobox site: https://distrobox.it/posts/run_libvirt_in_distrobox/ requires either zenity or kdialog. Aurora already pulls in kdialog as a dependency for something else, and I've already put in a pull request to make sure it works. Bluefin needs one of these to be present as well for this to work.
Currently, after following the directions, launches of the app from the gui will fail silently until the package is layered.

**Comment by m2Giles** [comment]
For Aurora ksshaskpass is available. For Bluefin gnome-ssh-askpass is available. Both are already setup as your SSH_ASKPASS.

To configure distrobox to use either of them, you can add the following to your distrobox configuration ($XDG_CONFIG_HOME/distrobox/distrobox.conf or $HOME/.distroboxrc)

```
distrobox_sudo_program="sudo --askpass"
```

If you do not want to use `sudo --askpass` you can also use `pkexec` or a variation of `systemd-run --shell --uid=0 --gid=0`
