### ISSUE TITLE
Audio does not output through Xbox controller over USB

### ISSUE THREAD

**Issue by Pixelguin** [ublue-os/bluefin#1417]
### Describe the bug

Using an Xbox gamepad connected via USB, the gamepad functions in controlling games, etc. but the computer does not recognize when headphones are plugged into the gamepad and it does not output audio to them. Tested with both Aurora NV and Bazzite NV.

Audio output *does* work when the gamepad is connected wirelessly via the official Xbox dongle (appears as sound device "Xbox Wireless Adapter for Windows"), but it *does not* work when the gamepad is connected over USB specifically.

### What did you expect to happen?

I expected to see a new audio output device appear in KDE Plasma after connecting headphones to the headphone jack in an Xbox gamepad plugged in via USB, just like when using the wireless dongle or when using USB in Fedora KDE with the [**xone** + **xone-firmware** drivers](https://copr.fedorainfracloud.org/coprs/sentry/xone/).

When connected over USB in Fedora, a new audio output appears named "Analog Out" and it functions as you'd expect.

### Output of `rpm-ostree status`

```shell
Aurora:

❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-nvidia:latest
                   Digest: sha256:a00d79643396f8f0f529975445d2def0c8670df314aaf8bce67f6db9ecff5be1
                  Version: 40.20240620.0 (2024-06-20T16:51:02Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-nvidia:latest
                   Digest: sha256:d297326eeaed792ee4d3141bdf0297eadf3a0e1b4967140cf808e9a56b31c750
                  Version: 40.20240613.0 (2024-06-15T18:27:24Z)

~

Bazzite:

name-redacted@fedora:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:376ffb04e940fce1390027c1ffa65662e8521d209dc7f5fbd1bc4ba3c235f718
                  Version: 40.20240619.0 (2024-06-20T01:06:19Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia:stable
                   Digest: sha256:376ffb04e940fce1390027c1ffa65662e8521d209dc7f5fbd1bc4ba3c235f718
                  Version: 40.20240619.0 (2024-06-20T01:06:19Z)
```

### Output of `groups`

```shell
Aurora + Bazzite:

❯ groups
[name redacted] wheel

~
```

### Extra information or context

Tested and confirmed this issue occurs with the following XInput controllers:
* Xbox One S Controller (the model with Bluetooth and 3.5mm jack)
* Xbox Series X|S Controller
* Xbox Elite Controller Series 2
* 8BitDo M30 Wired Controller for Xbox

Results of `rpm -qa | grep xone`:
* Aurora:
```
kmod-xone-6.9.4-200.fc40.x86_64-0.0.git.115.fdbb71f1-1.fc40.x86_64
xone-kmod-common-0.0.git.115.fdbb7151-1.fc40.noarch
```
* Bazzite:
```
kmod-xone-6.9.4-201.fsync.fc40.x86_64-0.0.git.115.fdbb71f1-1.fc40.x86_64
xone-kmod-common-0.0.git.115.fdbb71f1-1.fc40.noarch
```

Confirmed `/lib/firmware/xow_dongle.bin` exists in both Aurora and Bazzite.
* `sha256sum` is identical (`48084d9fa53b9bb04358f3bb127b7495dc8f7bb0b3ca1437bd24ef2b6eabdf66`)

**Comment by KyleGospo** [comment]
We ship a stripped xone driver that is missing the USB components. This is to avoid conflicting with other controller drivers and provide the maximum amount of compatibility. 

I'm afraid this is a won't fix, you would need to make a custom image if you want the full featured xone.
