### ISSUE TITLE
Unread/alert badge showing erroneously

### ISSUE THREAD

**Issue by fonnesbeck** [ublue-os/bluefin#1454]
### Describe the bug

Some apps in the dock have unread/alert badges showing when there are no messages/alerts/unreads in the app. A screenshot of what I'm seeing is shown below.

### What did you expect to happen?

Badges should only be shown when the app has something to report.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 16h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:37982919f241d6b3882e1d4b2c03df5f8b4102040c92e0288ffee60292cfdaf8
                  Version: 39.20240627.0 (2024-06-27T15:18:35Z)
                     Diff: 58 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:c192a8306619c0b83daf9bb7d03168bfc2c506c0005f5cd6ea7c8db7e6383c50
                  Version: 39.20240624.0 (2024-06-25T03:10:58Z)
```

### Output of `groups`

```shell
fonnesbeck wheel
```

### Extra information or context

Here is what I'm seeing:

![image](https://github.com/ublue-os/bluefin/assets/81476/709c35f7-5468-44b3-8898-6f3913e7cb71)

Yet, for both Slack and Spotify there are no messages, unread items, direct messages, etc. Restarting the app has no effect on this behavior.

**Comment by fonnesbeck** [comment]
After restarting the system, the badge for Slack has cleared but the Spotify badge persists.

**Comment by castrojo** [comment]
I've seen this a few times, not sure what causes it.

**Comment by fonnesbeck** [comment]
Even logging out of Spotify does not clear it, so definitely not associated with an alert.

**Comment by fonnesbeck** [comment]
Looks like this is a long-standing issue: https://www.reddit.com/r/gnome/comments/11s6pej/how_to_disable_notification_dotsbadges_in_the_dock/?rdt=45894

Is there a setting for simply turning them off globally?
