### ISSUE TITLE
App switching preference has no effect

### ISSUE THREAD

**Issue by fonnesbeck** [ublue-os/bluefin#1455]
### Describe the bug

When I change my app switching preference in settings to "Include apps from all workspaces", the app switcher continues to show only apps from the current workspace.

### What did you expect to happen?

App switcher should show all active apps in the session.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 16h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:37982919f241d6b3882e1d4b2c03df5f8b4102040c92e0288ffee60292cfdaf8
                  Version: 39.20240627.0 (2024-06-27T15:18:35Z)
                     Diff: 58 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:c192a8306619c0b83daf9bb7d03168bfc2c506c0005f5cd6ea7c8db7e6383c50
                  Version: 39.20240624.0 (2024-06-25T03:10:58Z)
```

### Output of `groups`

```shell
fonnesbeck wheel
```

**Comment by fonnesbeck** [comment]
Its not clear where to modify the suggested setting. The settings pane should be the appropriate place to specify this.

**Comment by castrojo** [comment]
See if `gsettings set org.gnome.shell.window-switcher current-workspace-only true` unwedges it.

**Comment by fonnesbeck** [comment]
That did the trick. Looks like a bug in the GUI then.
