### ISSUE TITLE
[Remove GNOME Extension] : Tailscale QS

### ISSUE THREAD

**Issue by Malix-off** [ublue-os/bluefin#1457]
### Describe the package

# Remove Package

- [GNOME Extension - Tailscale QS](https://extensions.gnome.org/extension/6139/tailscale-qs/)

## Context

In GNOME Settings → Network, network parameters, VPN and Proxy cover most of Tailscale QS features 

![GNOME Settings → Network](https://github.com/ublue-os/bluefin/assets/76160668/378301a3-3ad7-4576-b62e-155f5ec6a3d8)

### Image

All Images

**Comment by castrojo** [comment]
I don't understand this issue, what are you trying to do?

**Comment by Malix-off** [comment]
I do not think Tailscale QS is bringing enough value to be shipped and enabled in the base image

**Comment by castrojo** [comment]
You can turn it off via the instructions: 

- https://universal-blue.discourse.group/docs?topic=290
- https://universal-blue.discourse.group/t/managing-gnome-extensions/166

**Comment by castrojo** [comment]
raindrac is working on a ujust script that will toggle both the service and the extension on and off, that's probably the best we can do for now.
