### ISSUE TITLE
Suggest adding a couple CLI tools in Bluefin & Aurora

### ISSUE THREAD

**Issue by TeamLinux01** [ublue-os/bluefin#1460]
### Describe the package

I am requesting that `fd` and `bat` be included in the base images.

I have been using `fish` for a while now and want to start using `fzf` and have it integrated with fish. I found a project [GitHub - PatrickF1/fzf.fish: 🔍🐟 Fzf plugin for Fish](https://github.com/PatrickF1/fzf.fish) to add that functionality and besides requiring `fzf` it also needs `fd` and `bat`.

For now, I installed `fd`, `bat`, and `fisher` via brew and installed the `fzf.fish`, but it would be nice to include `fd` and `bat` so that everyone can use them.

I started a discussion on https://universal-blue.discourse.group/t/suggest-adding-a-couple-cli-tools-in-bluefin-aurora/2574 moving it to here for more input.

### Image

All Images

**Comment by castrojo** [comment]
Sorry this one is out of scope, we're slimming down what we can.
