### ISSUE TITLE
ujust update ignores topgrade-user.toml and topgrade-system.toml entries

### ISSUE THREAD

**Issue by fonnesbeck** [ublue-os/bluefin#1468]
### Describe the bug

Updating the system via `ujust update` includes conda/mamba by default (which it probably should not FWIW). Attempting to prevent this by adding `ignore=["mamba", "conda"]` to the `[misc]` section of either of the `topgrade*` files in `/etc/ublue-update` does not prevent these from being included in the update. Am I doing this wrong, or is this a bug?

### What did you expect to happen?

conda and mamba should be ignored when `ujust update` is called.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 21h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:e16afbddf4517f9f5b70734b9cc1f9662ee7034859aba197c8e5d3c192b0ccca
                  Version: 39.20240630.0 (2024-06-30T05:56:06Z)
                     Diff: 10 upgraded, 7 removed, 7 added
          LayeredPackages: 1password 1password-cli

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:d3317191c0e2947a448dddeb89b8aec13733c77c076ca7639f72301d5ae24dce
                  Version: 39.20240628.0 (2024-06-28T23:00:31Z)
          LayeredPackages: 1password 1password-cli

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:37982919f241d6b3882e1d4b2c03df5f8b4102040c92e0288ffee60292cfdaf8
                  Version: 39.20240627.0 (2024-06-27T15:18:35Z)
          LayeredPackages: 1password 1password-cli
```

### Output of `groups`

```shell
fonnesbeck wheel incus-admin lxd docker libvirt
```

**Comment by fonnesbeck** [comment]
Tried creating a `~/.config/topgrade.toml` with the relevant ignores, but had no effect either.

**Comment by m2Giles** [comment]
`ujust update` runs the following command:

`/usr/bin/topgrade --config /usr/share/ublue-os/topgrade.toml`

This will update everything on your system it can only excluding itself, toolbx (since it thinks distrobox containers are toolbx), containers, and helm.

Everything else will be upgraded. If you wish to do a finer grained upgrade. You can use topgrade directly with a specified config file

**Comment by fonnesbeck** [comment]
It does not look like the file in `/usr/share` is editable. Is there any way of being able to edit the defaults? -- I never want any update to ever touch `conda` or `mamba` unless I manually do so using `conda`, so I'd like to guard against it happening accidentally. It would be great if there was a way to specify what gets updated and what doesn't.
