### ISSUE TITLE
KDE Konsole desktop file not properly working in Aurora

### ISSUE THREAD

**Issue by moritz-john** [ublue-os/bluefin#1471]
### Describe the bug

After a clean installation of Aurora, there is no working start menu entry for KDE Konsole:

![Screenshot_20240701_143439](https://github.com/ublue-os/bluefin/assets/70295002/9903ce8d-7b3f-4400-8acc-83fed05e0385)

There is only the option to run "konsole" as a command line prompt (which yes, would technically open KDE Konsole)

### What did you expect to happen?

I expect to find a working KDE Konsole start menu entry like on my EndeavourOS installation:

![image](https://github.com/ublue-os/bluefin/assets/70295002/1f7fdb4b-d89f-428b-9d4b-fcc9f133705f)

### Extra information or context

I don't know if this bug has anything to do with: https://github.com/ublue-os/bluefin/pull/1162

Also I would love for Aurora to adopt something like Bazzite:
They offer a [`ujust restore-original-terminal`](https://github.com/ublue-os/bazzite/blob/f6af79b0b19333dd0b735fb180e762fc7cbea83c/system_files/desktop/shared/usr/share/ublue-os/just/80-bazzite.just#L4) command to "restore" the default terminal (e.g. KDE Konsole)

___
Another screenshot showcasing the missing desktop/menu entry:
![Screenshot_20240701_143458](https://github.com/ublue-os/bluefin/assets/70295002/65e0da6b-dc21-4175-b195-a7bac28f8669)

(At least the deskop file appears to be working in the Default Application settings panel:)

![Screenshot_20240701_143419](https://github.com/ublue-os/bluefin/assets/70295002/eb02573a-34ab-4a13-a141-92e74e044cf1)

**Comment by m2Giles** [comment]
The konsole desktop entry is hidden since we use Ptyxis by default. However, we do not delete it.

The entry is still on disk inside of /usr/share/applications. Copy it to `/usr/local/share/applications` or `~/.local/share/applications` and remove the `Hidden=true` key to have it appear.

**Comment by paidhi** [comment]
> The konsole desktop entry is hidden since we use Ptyxis by default. However, we do not delete it.
> 
> The entry is still on disk inside of /usr/share/applications. Copy it to `/usr/local/share/applications` or `~/.local/share/applications` and remove the `Hidden=true` key to have it appear.

This does not work for me. There is no entry for `Hidden` in `/usr/share/applications/org.gnome.Ptyxis.desktop` or `/usr/share/applications/org.kde.konsole.desktop`. I copied both files to `~/.local/share/applications/` and added `Hidden=true` to `org.gnome.Ptyxis.desktop` and `Hidden=false` to `org.kde.konsole.desktop`. Still Konsole does not appear.

I also noticed that `/usr/share/applications/org.gnome.Ptyxis.desktop` includes the string `konsole` in `Keywords=`.

It would be great if `ujust restore-original-terminal` could be made available.

I don't mind ptyxis being installed. But with KDE I really would prefer to use Konsole and it's profiles feature.


```text
> rpm-ostree status -vb
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable (index: 0)
                   Digest: sha256:c30840261554f6b5184366c982d58409ebe3a6ea6258b823fd5d5207cf8caec5
                  Version: 40.20240730.0 (2024-07-30T05:51:15Z)
               BaseCommit: ea0048af2b4212d64c4909c6fcecba5f6ce7c774b422acfabd5723603957d60c
                   Commit: d1f5d2de71056d3be605f29edec37a85bc4353db81c135b1f2eb04759573a0ae
                           ├─ copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr (2024-07-26T07:24:25Z)
                           ├─ fedora (2024-04-14T18:51:11Z)
                           ├─ updates (2024-08-01T02:48:03Z)
                           └─ updates-archive (2024-06-30T05:31:17Z)
                   Staged: no
                StateRoot: default
          LayeredPackages: borgbackup gnome-disk-utility gparted snapper

```

**Comment by paidhi** [comment]
I just found the problem.
It's not `Hidden=` but `NoDisplay=` instead.
