### ISSUE TITLE
The android udev rules need to be updated

### ISSUE THREAD

**Issue by mbruzek** [ublue-os/bluefin#1478]
### Describe the bug

I was reviewing the boot logs for my ublue latest image on 07/01 and I saw some errors in the logs:

```
/usr/lib/udev/rules.d/10-switch.rules:1 Unknown group 'nintendo_switch',>
/usr/lib/udev/rules.d/30-linksys-ae1200.rules:1 The line has no effect, >
/etc/udev/rules.d/51-android.rules:206 Invalid key/value pair, ignoring.
/etc/udev/rules.d/51-android.rules:207 Invalid key/value pair, ignoring.
/etc/udev/rules.d/51-android.rules:517 Invalid key/value pair, ignoring.
/etc/udev/rules.d/51-android.rules:518 Invalid key/value pair, ignoring.
/etc/udev/rules.d/51-android.rules:521 Invalid key/value pair, ignoring.
/etc/udev/rules.d/51-android.rules:157 GOTO="go_adb" has no matching lab>
/etc/udev/rules.d/51-android.rules:157 The line has no effect any more, >
/etc/udev/rules.d/51-android.rules:158 GOTO="go_adbrndis" has no matchin>
/etc/udev/rules.d/51-android.rules:158 The line has no effect any more, >
/etc/udev/rules.d/51-android.rules:159 GOTO="go_adbmtp" has no matching >
/etc/udev/rules.d/51-android.rules:159 The line has no effect any more, >
/etc/udev/rules.d/51-android.rules:160 GOTO="go_adbptp" has no matching >
/etc/udev/rules.d/51-android.rules:160 The line has no effect any more, >
/etc/udev/rules.d/51-android.rules:161 GOTO="go_adbmidi" has no matching>
/etc/udev/rules.d/51-android.rules:161 The line has no effect any more, >
/etc/udev/rules.d/51-android.rules:162 GOTO="go_adb" has no matching lab>
```

It seems the file 51-android.rules contains some errors. I inspected this file and all the lines with errors have "inline" comments. I don't think they are supported.

I tried to find the source file in the ublue-os repositories but I was unsuccessful. I did find an issue about this same problem that was fixed back on Nov 3, 2023.

https://github.com/M0Rf30/android-udev-rules/issues/287

Please help me find where we get the 51-android.rules file in this repo and I would be happy to remove the inline comments to fix this issue. If we are pulling it from somewhere else, the latest file here: https://github.com/M0Rf30/android-udev-rules/blob/main/51-android.rules does NOT have any inline comments.

I am happy to submit a fix to resolve this issue, but I can not determine where we get the 51-android.rules udev configuration from. Please point me in the right direction and I will do my best to resolve.

Thank you.

### What did you expect to happen?

I expected the udev rules that we are using to not generate errors when getting parsed. 

The latest 51-android.rules file here:  https://github.com/M0Rf30/android-udev-rules does not contain inline comments.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:cbae715dd100fff19b642a60e06d1c261fa7117223afafd53e7c45f35bd94cce
                  Version: 40.20240702.0 (2024-07-02T04:54:50Z)
                     Diff: 9 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:d8d55f5f27490f47a9e4f1a6b8ada06d4d9dc7cbb497f4baf3f96c7a20fe378d
                  Version: 40.20240701.0 (2024-07-01T21:39:54Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:e7d4f63d35c1cd1232d831dcba6be611180b50a1fc260471ef5655067c1619af
                  Version: 40.20240617.0 (2024-06-17T20:07:42Z)
```

### Output of `groups`

```shell
mbruzek wheel incus-admin docker lxd libvirt
```

**Comment by fiftydinar** [comment]
Hello, Android udev rules are located here:

https://github.com/ublue-os/android-udev-rules

**Comment by fiftydinar** [comment]
It's just 3 commits behind, oppositely of what the version indicates, since maintainers didn't touched that.

But the build in COPR was built 9 months ago, so just a merge of those 3 new commits & build trigger should solve the issue.

**Comment by mbruzek** [comment]
Thank you @fiftydinar I will take a look at fixing these issues.

**Comment by mbruzek** [comment]
I created the pull request here: https://github.com/ublue-os/android-udev-rules/pull/5

But as you pointed out the version in the ublue repo was newer than what I see on the latest image. Please advise how I can initiate a build of COPR. 

Thank you!

**Comment by fiftydinar** [comment]
@mbruzek Unfortunately, only certain Universal Blue maintainers have access to ublue-os/staging COPR repo, where Android udev rules reside.

So build can be pushed by them only.

**Comment by castrojo** [comment]
This looks good to go?

**Comment by fiftydinar** [comment]
@castrojo just looking at the COPR, package is still not rebuilt

**Comment by fiftydinar** [comment]
Now package rebuilt, so this issue is now officially solved

**Comment by bsherman** [comment]
I shouldn't have reopened this as it was correctly closed back in July.

Since then there were more updates in the upstream android-udev-rules and a PR was opened: https://github.com/ublue-os/android-udev-rules/pull/8

I've merged that and will rebuild the COPR.

**Comment by fiftydinar** [comment]
Reopening, because commit needs to be merged, which updates RPM version & then rebuild in COPR needs to be triggered.

When same RPM version is used for multiple builds, it can happen that you don't get the latest build.

**Comment by castrojo** [comment]
We sorted this didn't we?

**Comment by fiftydinar** [comment]
Now it's sorted
