### ISSUE TITLE
Investigate support for Brother MFC-L2750DW printer. 

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1479]
From lemmy: Brother MFC-L2750DW

Don't have time to investigate now so just filing here.

**Comment by fiftydinar** [comment]
`mfcl2750dwpdrv` is the RPM package name for this specific printer, which can be downloaded from the Brothers support page.

I wonder if there is some yet another generic print driver which covers this one, or resorting to `mfcl2750dwpdrv` is needed
