### ISSUE TITLE
Adverts for `ujust` commands in the terminal motd gives a false sense of their security. 

### ISSUE THREAD

**Issue by StudioLE** [ublue-os/bluefin#1487]
### Describe the bug

By default the terminal motd includes adverts or *tips* for executing random `ujust` commands without including any links to documentation about what these features do.

It instils a false sense of reliability in the command and there's no clear recourse for when they go wrong.
 

![image](https://github.com/ublue-os/bluefin/assets/193290/a1a42f4b-60e9-430e-8a1f-3a306df089e1)

### What did you expect to happen?

One of the suggestions is:

```
Using full disk encryption and tired of entering your password?  ujust setup-luks-tpm-unlock  can help you
  use your CPU's TPM to unlock your device. 
 ``` 

But executing the suggested command is not reliable.

It can perform an unknown portion of the task, outputs a cryptic error and then the user if left without any clear path for reverting the process:  https://github.com/ublue-os/bluefin/issues/1469.

Instead it would make more sense to link to documentation for the ujust command. 

### Output of `rpm-ostree status`

```shell
N/A
```

### Output of `groups`

```shell
N/A
```

**Comment by m2Giles** [comment]
`ujust` is a wrapper around `just`, which is a task runner.

`ujust --choose` will give you am `fzf` view with a preview window to inspect what each command will do.

A large amount of the commands have been moved from inline commands to scripts that can be viewed in `/usr/libexec` often prefixed with ublue.
