### ISSUE TITLE
Add fish container indicator from bazzite

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1491]
Filing as a reminder:

https://github.com/ublue-os/bazzite/pull/1337

**Comment by RealVishy** [comment]
I'd like to help with this when I've got time 😄

**Comment by RealVishy** [comment]
I'll test it out now that it's merged but I think starship might conflict with this fish function

**Comment by RealVishy** [comment]
I believe the function assumes that you're using the same home directory for your distrobox for it to be able to load in the fish function. Probably needs a rename as well.
