### ISSUE TITLE
Investigate adding chromebook-linux-audio

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1500]
https://github.com/WeirdTreeThing/chromebook-linux-audio.git

Not sure if this is appropriate to ship ootb but tracking it here so we can take a look.

**Comment by TeamLinux01** [comment]
I have successfully run this on a ASUS C302A running Fedora 40 at the beginning of the year. I have since given that machine away, but it would still be nice to include it for Ublue users.

**Comment by WeirdTreeThing** [comment]
I've only now just need this. I don't know if you all are still interested in this but I'd be willing to work out the issues needed for this to work.

**Comment by Zorro92** [comment]
Was this issue ever considered? I too had this issue and ended up having to just stick to plain ol fedora and use WeirdTreeThing's fix. Would have loved to use bluefin.

**Comment by nothingneko** [comment]
> Was this issue ever considered? I too had this issue and ended up having to just stick to plain ol fedora and use WeirdTreeThing's fix. Would have loved to use bluefin.

you can install the `alsa-ucm-cros` package from Terra if you enable layering, that provides Tree's script.

https://fedora.pkgs.org/43/terra/alsa-ucm-cros-0:0.8-1.fc43.noarch.rpm.html

**Comment by znmeb** [comment]
What does this tool do and what kind of audio use case would it have? Is it a Chrome (as in browser) thing? Chromium audio from the flatpak works fine on my system.

**Comment by WeirdTreeThing** [comment]
It's for chromebooks which use non-standard audio hardware.

**Comment by znmeb** [comment]
> It's for chromebooks which use non-standard audio hardware.

Ah ... I have a ChromeBook but I run stock ChromeOS and `crostini` Debian on it. Audio works as I expected there as well as on my Bluefin machine/

**Comment by WeirdTreeThing** [comment]
My stuff is for non-ChromeOS linux

**Comment by Zorro92** [comment]
> > Was this issue ever considered? I too had this issue and ended up having to just stick to plain ol fedora and use WeirdTreeThing's fix. Would have loved to use bluefin.
> 
> you can install the `alsa-ucm-cros` package from Terra if you enable layering, that provides Tree's script.
> 
> https://fedora.pkgs.org/43/terra/alsa-ucm-cros-0:0.8-1.fc43.noarch.rpm.html

Thanks I actually ended up figuring it out yesterday! 
Except I used this one: 
https://copr.fedorainfracloud.org/coprs/pvermeer/chromebook-linux-audio
