### ISSUE TITLE
Bluefin-cli bat command not working

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/bluefin#1517]
### Describe the bug

I used `ujust bluefin-cli` to enable the bling tools and tried to use bat and ran into this error.

```
❯ bat
bat: error while loading shared libraries: libgit2.so.1.7: cannot open shared object file: No such file or directory
```

Tried reinstalling bat by uninstalling through brew and installing again but recieved the same error.

### What did you expect to happen?

I expected to be able to use bat.

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1h 11min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:37dd516c827b119b49ce4c461d12e5dd7bdcd67d3e5d3094657a5006f366b6b1
                  Version: 40.20240718.0 (2024-07-18T04:53:03Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:latest
                   Digest: sha256:44a60cfbba774da969dbfcef49eaf983a6fc04368b845c854f02cefbaeb9831d
                  Version: 40.20240717.0 (2024-07-17T17:08:12Z)
```

### Output of `groups`

```shell
❯ groups
vishwas wheel incus-admin lxd docker libvirt
```

### Extra information or context

Only thing i can think of is that it's a packaging error on homebrew?
This is functional on my laptop but i get this error on my pc

**Comment by castrojo** [comment]
Interesting, it's running fine here, and I tried removing it and reinstalling it and it also still works.

**Comment by RealVishy** [comment]
Hmm, is there a way to revert the changes and reapply it? It's strange cause it works perfectly on my laptop, it just seems to be having this issue on my pc

**Comment by castrojo** [comment]
I think manually brew installing the rest of the list and running the bling script manually should unstick you, but don't have time to dig into what to do, I'll look tonight unless someone gets to it first.

**Comment by RealVishy** [comment]
well i uninstalled bat again and reinstalled it and now it works fine lol
