### ISSUE TITLE
Bluefin stable does not boot properly after bluefin-stable.iso installation in Gnome Boxes

### ISSUE THREAD

**Issue by carpediem29** [ublue-os/bluefin#1538]
### Describe the bug

I'm using Fedora SilverBlue 40 and want to test Bluefin stable. I created a new VM in Gnome Machines to test Bluefin stable (2c64d7986c508ad9e7af06668c775a20c2a542921ad9ccfd0bc0bdd841c7f849 checksum verified) , did all the installation configuration (just selected french keyboard and used automatic partitioning) and first post-installation boot fails. It seems the issue is related to disk (/dev/disk/by-uuid/93701bf-cb03-4c4c-af83-95f67435adb9 does not exist causing script timeouts)

### What did you expect to happen?

Gnome session to start but I'm stuck at maintenance / emergency mode. 

### Output of `rpm-ostree status`

```shell
N/A
```

### Output of `groups`

```shell
N/A
```

### Extra information or context

Screen captures below

**Comment by carpediem29** [comment]
![Capture d’écran du 2024-07-28 10-30-23](https://github.com/user-attachments/assets/4bf9c6e4-561d-43d3-8710-78f2e5d0eb61)
![Capture d’écran du 2024-07-28 10-32-00](https://github.com/user-attachments/assets/70af3184-6c90-4708-b135-c0f154757e87)

**Comment by carpediem29** [comment]
SElinux issue ? 

![image](https://github.com/user-attachments/assets/62474527-ca5f-45a0-8fd5-6647a6fbac99)

**Comment by carpediem29** [comment]
I though the issue was due to the disk size - I increased it from 20G to 60G with no success.
I donwloaded and booted bluefin-dx-stable. Automatic partioning layout .. Same issue.

**Comment by castrojo** [comment]
ISOs are working here in virt-manager and qemu, this appears to be a GNOME Boxes specific issue afaict?

**Comment by carpediem29** [comment]
Thanks for the feedback. Weird. Will try on another Fedora 40  device.

**Comment by carpediem29** [comment]
It's pretty weird : no issue with Aurora stable iso on the same machine.

**Comment by carpediem29** [comment]
> ISOs are working here in virt-manager and qemu, this appears to be a GNOME Boxes specific issue afaict?

When you mean working do you mean you can boot the ISO & create a VM successfully ? 
The 2 ISO boots fine on my side : it's just that the install process does not work / getting stuck but if waiting enough completes.
Example of stage being stucked : 
![Capture d’écran depuis 2024-07-29 13-30-52](https://github.com/user-attachments/assets/38744a9b-796f-44ee-89cd-80acbd70dbad)

**Comment by carpediem29** [comment]
Will close the bug. I suspect a local issue. 
I installed my new computer with SilverBlue but will plan to reinstall it with Bluefin instead (VM tests successful in the end).
Getting a working computer with bulk SilverBlue is time-consuming - each time I forget some steps - such as installing some Flathub versions of programs instead of SilverBlue to have correct features (H264 for videos players for instance), ...  
Bluefin is really easing the job for workstation or developers users. Bravo/Congrats
