### ISSUE TITLE
Add zoom workaround for wayland sharing

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1546]
We should ship this if we can, I don't like touching userspace but I hate doing zoom tech support even more:

https://hiiruki.dev/blog/setup-zoom-linux-wayland/

**Comment by castrojo** [comment]
Yeah I'm on the webui for the moment, the refresh seems to be pretty janky across the board. I hate that I have to use this tool lol.

**Comment by p-sims** [comment]
I've been tried out ProjectBlueFin this week and can report that Zoom screensharing under wayland appears to have start working ....  Well the sharing bit works (both windows and full screen), but you can't end the share without complete crashing zoom.... (it hangs whether you stop share from gnome task bar or via zoom, and requires Force Quit). So progress I guess....
