### ISSUE TITLE
Add Tailscale tray app for Aurora

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/bluefin#1547]
### Describe the package

I'd like to request one of the below packages for Aurora/Bazzite so it matches the tailscale QS shipped in gnome. I'll try them out and see which one i end up liking more.

https://github.com/DeedleFake/trayscale 

https://github.com/f-koehler/KTailctl

### Image

All Images

**Comment by RealVishy** [comment]
KTailctl integrates better with KDE and it seems to have about the same features as trayscale so I think it's the better pick.

I'd like to submit a PR for it but i'm not sure how to add a flatpak to the images.

**Comment by castrojo** [comment]
https://github.com/ublue-os/bluefin/blob/main/aurora_flatpaks/flatpaks

Great idea! After you PR let's give it a few days for people to weigh in, both of them appear to be maintained recently so that's always a positive sign. Thanks!

**Comment by RealVishy** [comment]
one "caveat" is that for full functionality of the app, it requires the user to have run `sudo tailscale up --operator=$USER`.

I'm currently following the [existing issue](https://github.com/ublue-os/bluefin/issues/862) for it and i'll see if i can also merge the fix used in bazzite.

**Comment by RealVishy** [comment]
Turns out someone already put in the fix from bazzite, closing the issue now.
