### ISSUE TITLE
Add Samsung Unified Linux Driver .rpm driver pack from negativo17 repository

### ISSUE THREAD

**Issue by Pryka** [ublue-os/bluefin#1550]
### Describe the package

Is it possible to add drivers for some Samsung printers, from my knowledge most if not all Samsung printers need **uld** - **Samsung Unified Linux Driver** - https://ftp.hp.com/pub/softlib/software13/printers/SS/SL-C4010ND/uld_V1.00.39_01.17.tar.gz

I know that ublue team use some of the stuff that negativo17 host and he also host a .rpm packaged for that driver pack - https://negativo17.org/samsung-unified-linux-driver-printers-scanners/

Repository link - https://negativo17.org/repos/uld/fedora-40/x86_64/

I personally tested them multiple times, and they do work.

### Image

Bluefin, Aurora and Bazzite(If Bazzite maintainers want it!)

**Comment by castrojo** [comment]
Don't have time to finish this so leaving the issue open. From fiftydinar: You need to add custom repo for this:

https://negativo17.org/repos/fedora-uld.repo

**Comment by Pryka** [comment]
I know, already added repo and installed the drivers, that was actually the first thing I did on Bluefine because i need this printer operational :D

It would be nice to have it build in into image and not have to layer it since it covers a lot of Samsung printers not only mine, hence my request.

**Comment by LLNeto** [comment]
I am experiencing this exact problem, I am trying to add thecustom repo
