### ISSUE TITLE
DistroBox Nvidia repo broken for RHEL-based images

### ISSUE THREAD

**Issue by lunacd** [ublue-os/bluefin#1552]
### Describe the bug

- Create a distrobox using almalinux, rockylinux, centos, or RHEL ubi
- Run `sudo dnf update`
- rpmfusion nvidia repo cannot be found:
```
Error: Failed to download metadata for repo 'rpmfusion-nonfree-nvidia-driver': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-nvidia-driver-9&arch=x86_64 (IP: 158.69.60.128)
```

### What did you expect to happen?

Distrobox containers should have valid repo configuration.

**Comment by castrojo** [comment]
I don't think there's much we can do here, we don't make any of those distroboxes?

**Comment by lunacd** [comment]
I see. I'm having a bit of trouble understanding where the broken repo files come from:
```
drwxr-xr-x. 1 root   root    308 Jun  7 09:36 .
drwxrwxr-x. 1 root   root   1178 Jul 31 18:29 ..
-rw-r--r--. 1 nobody nobody  876 Jul 31 08:24 negativo17-fedora-nvidia.repo
-rw-r--r--. 1 nobody nobody  597 Jul 31 08:24 nvidia-container-toolkit.repo
-rw-r--r--. 1 root   root   6610 Jun  7 09:35 rocky-addons.repo
-rw-r--r--. 1 root   root   1165 Jun  7 09:35 rocky-devel.repo
-rw-r--r--. 1 root   root   2387 Jun  7 09:35 rocky-extras.repo
-rw-r--r--. 1 root   root   3417 Jun  7 09:35 rocky.repo
-rw-r--r--. 1 nobody nobody 1487 Jul 31 08:28 rpmfusion-nonfree-nvidia-driver.repo
```

Specifically the three that is owned by nobody and matches exactly what's used in ublue. I thought it was done intentionally but seems not. Then my next best guess is that distrobox is trying to copy over nvidia-related repos to get nvidia integration working? Those are indeed the only three that has nvidia in their name:

```
$ ls -l /etc/yum.repos.d/ | grep nvidia
-rw-r--r--. 1 root root  876 Jul 31 08:24 negativo17-fedora-nvidia.repo
-rw-r--r--. 1 root root  597 Jul 31 08:24 nvidia-container-toolkit.repo
-rw-r--r--. 1 root root 1487 Jul 31 08:28 rpmfusion-nonfree-nvidia-driver.repo
```

**Comment by lunacd** [comment]
Aha, found what's being funny: https://github.com/89luca89/distrobox/blob/4c38d6b3f9bc833e58a435471158935824727805/distrobox-init#L1862-L1876.

**Comment by lunacd** [comment]
I'll file an issue with distrobox. Sorry for the noise!
