### ISSUE TITLE
MOK management: Password doesn't match

### ISSUE THREAD

**Issue by ubionexd** [ublue-os/bluefin#1554]
### Describe the bug

I cannot enroll the ublue kernel key after install, because it returns [ERROR] Password doesn't match. I'm entering 'universalblue' as password. I don't have a numpad, and I don't know what it means to use the `-` on it.

### What did you expect to happen?

Enroll the key.

### Output of `rpm-ostree status`

```shell
Can't boot, so can't provide this.
```

### Output of `groups`

```shell
Can't boot, so can't provide this.
```

**Comment by ubionexd** [comment]
Never mind, I looked trough the Universal Blue Discord server and used the password `ublue-os` to enroll the key.

**Comment by castrojo** [comment]
Weird I thought we updated this to `universalblue`? cc @m2Giles

**Comment by castrojo** [comment]
How old is the ISO you downloaded?

**Comment by Pryka** [comment]
> How old is the ISO you downloaded?

I downloaded and installed Bluefin on Jul 27 and it was `ublue-os` also.

Used the latest available DX iso at that time - the documentation on discourse is still stating that the password is ublue-os.

https://universal-blue.discourse.group/t/bluefin-administration-guide/40

**Comment by ubionexd** [comment]
I just downloaded it today. Like 1-2 hours ago.

**Comment by m2Giles** [comment]
Stable and GTS ISOs are older than the change.

Probably just needs a button press on them.

**Comment by castrojo** [comment]
Ok I kicked off all three, thanks everyone for helping out!
