### ISSUE TITLE
Latest version of DevPod is v0.5.18, but the image only ships with v0.5.9

### ISSUE THREAD

**Issue by Tichael** [ublue-os/bluefin#1556]
### Describe the bug

The version of DevPod shipped with the image is v0.5.9, which was released on May 27. The latest version is v0.5.18 released on July 17.

In #1350, it's stated that the version is handled at the image level, probably using a RPM package. But on [DevPod's website](https://devpod.sh/docs/getting-started/install), it says:

> The official package is the Appimage [...]
> Since we're not providing deb or rpm packages anymore, we're now providing a tar.gz that can be used as source for your custom package.

So if this image uses an old RPM for DevPod, that's probably why it isn't up to date anymore?

### What did you expect to happen?

I expected DevPod to be kept up to date, especially on the developper version of Bluefin/Aurora since they are tailored at containter development.

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable
                   Digest: sha256:c30840261554f6b5184366c982d58409ebe3a6ea6258b823fd5d5207cf8caec5
                  Version: 40.20240730.0 (2024-07-30T05:51:15Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable
                   Digest: sha256:c056b38f8bd11c105350b7bfa836beb3289a03de2c406bd20b68e29aa741fd35
                  Version: 40.20240730.0 (2024-07-30T05:51:15Z)
```

### Output of `groups`

```shell
tichael wheel docker incus-admin lxd libvirt
```

**Comment by castrojo** [comment]
Missed this merge, sorted: https://github.com/ublue-os/packages/pull/26

I kicked off an aurora stable build, you'll get an update when these turn green: https://github.com/ublue-os/bluefin/actions/runs/10204745991

Then that should sort it! I need to setup renovatebot in the packages repo so we don't miss version updates.

**Comment by castrojo** [comment]
Ok p5 checked and the renovatebot was set up, there was a misconfiguration in the webapp side, which he corrected, this should automate updates in the future, thanks!
