### ISSUE TITLE
Terminal (Ptyxis) won't open container profile directly, only from BoxBuddy

### ISSUE THREAD

**Issue by novakwh** [ublue-os/bluefin#1557]
### Describe the bug

When I click the + menu in terminal, and select the arch container that I created, I receive a "Process Exited" error and the following:

 /usr/bin/distrobox-enter: eval: line 690: syntax error near unexpected token `('

I get that same error if I just try to enter the distrobox from the command line. Note that I can still get into the container terminal fine if I open BoxBuddy and click "Open Terminal." But this is a new error in Ptyxis, which has always worked before.

### What did you expect to happen?

I expected Ptyxis to open a terminal window in the correct distrobox profile.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:stable
                   Digest: sha256:1afce620e1190ad2cd194579b38d1eeb45f843c40a9380da78940b4b0c7585a9
                  Version: 40.20240730.0 (2024-07-30T05:49:18Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:gts
                   Digest: sha256:6b7d2f988902ef14e4293746716839d2c2d6370e222e52818e314c5c101af71a
                  Version: 39.20240728.0 (2024-07-28T05:50:02Z)
```

### Output of `groups`

```shell
username wheel
```

**Comment by castrojo** [comment]
> I get that same error if I just try to enter the distrobox from the command line. 

This is likely the root cause, can you paste in the entire error?

**Comment by novakwh** [comment]
After rebooting/updating this evening, the terminal seems to be working fine.
