### ISSUE TITLE
Ctrl-Alt-u dead because Black Box terminal is not installed.

### ISSUE THREAD

**Issue by hirnidrin** [ublue-os/bluefin#156]
### Describe the package

The layered package was removed in #33 but never added back as flatpak in yafti.

The keyboard shortcut and BlackBox config to run distrobox are there in [/etc/dconf/db/local.d/01-ublue](https://github.com/ublue-os/bluefin/blob/main/etc/dconf/db/local.d/01-ublue), works well after installing the flatpak manually.

### Image

Silverblue

**Comment by bketelsen** [comment]
Yea please
