### ISSUE TITLE
Ship the Howdy Copr

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/bluefin#1563]
### Describe the package

I'd like to request the package `howdy` because it's useful for windows hello style authentication. It does require some configuration for sddm/gdm so that could be added as a ujust. A tip about it could also be added to the MOTD in the terminal

I currently have it layered so it'd be nice to have it in the base so I can bootc upgrade.

### Image

All Images

**Comment by RealVishy** [comment]
The info I need to implement this is where copr repos and packages go and where ujust's would go.

**Comment by m2Giles** [comment]
My hesitation is that howdy is tested quite a bit less than fprintd.

I could see including the package, but hesitate on having any sort of automatic configuration that messes with pam.

**Comment by castrojo** [comment]
We looked into this before and decided that this should happen at the distro level.
