### ISSUE TITLE
wpa_suplicant broken on Broadcom

### ISSUE THREAD

**Issue by FrantaNautilus** [ublue-os/bluefin#1591]
### Describe the bug

`wpa_supplicant` fails to perform scan of wireless networks, in consequence `NetworkManager` is not able to connect to Wi-Fi networks.

### What did you expect to happen?

Before the yesterday's update `wpa_supplicant` was able to scan for Wi-Fi connections and `NetworkManager` was able to connect to found Wi-Fi networks. The wireless functioned without problem since configuring Broadcom (`ujust configure-broadcom`) until now.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:5e6fb0c2957dea7740ccadfe93e81b8b705ac4834cb7eb4bdc68d667d3503101
                  Version: 40.20240811.0 (2024-08-11T04:50:41Z)
                     Diff: 138 upgraded, 8 removed, 12 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:a6620da7358f6e36b23950b4f9b22ede90a113e0762daf05563a9aa4002a681b
                  Version: 40.20240802.0 (2024-08-02T04:52:53Z)
                   Pinned: yes
```

### Output of `groups`

```shell
myuser wheel
```

### Extra information or context

* `myuser` in  the previous field is placeholder for my username
* I have noticed, that there is a change in the latest update:
```
wpa_supplicant 1:2.10-10.fc40.x86_64 -> 1:2.11-2.fc40.x86_64
    * Su aug 04 2024 Janne Grunau <janne-fdr@jannau.net> - 1:2.11-2
    - Revert commit breaking authentication on brcmfmac (#2302577)

    * Mo jul 29 2024 Davide Caratti <dcaratti@redhat.com> - 1:2.11-1
    - Update to version 2.11 (#2299036)
    - Disable OpenSSL ENGINE API (#2301368)
```
* The journal contains `wpa_supplicant` errors of form
```
wpa_supplicant reports CTRL-EVENT-SCAN-FAILED ret=-22 retry=1
```
* Running `ujust configure-broadcom` again does not change the result
* May not be connected , however on the pinned deployment where Wi-Fi works the Wireguard VPN stopped working after the update.

**Comment by castrojo** [comment]
Looks like this? https://www.reddit.com/r/Fedora/comments/1eqh3xb/it_was_a_clean_install_and_i_only_installed/

**Comment by FrantaNautilus** [comment]
Not really, the Wi-Fi button is displayed correctly in the quick settings, Wi-Fi is reported as "on" and can be turned "off" (although this does not help). When the Wi-Fi settings are opened, it is displayed as "scanning" indefinitely. When inspecting the journal the error `wpa_supplicant reports CTRL-EVENT-SCAN-FAILED ret=-22 retry=1` keeps appearing in regular intervals. The changelog about `wpa_supplicant` commit revert is connected with the following bug [https://bugzilla.redhat.com/show_bug.cgi?id=2302577](url) affecting Broadcom devices, and if I understand correctly it is not solved to this day.

**Comment by FrantaNautilus** [comment]
Unfortunately the problem is not solved in newer kernel. After today's update the problem persists (`rpm-ostree status` below), the kernel was updated to version `6.10.4-201.fsync.fc40_x86` and there was also an update of the `wpa_supplicant`:
```
wpa_supplicant 1:2.10-10.fc40.x86_64 -> 1:2.11-3.fc40.x86_64
    * Sat Aug 10 2024 Davide Caratti <dcaratti@redhat.com> - 1:2.11-3
    - re-enable OpenSSL ENGINE API on f40 (#2303165)
```
Output of `rpm-ostree status` (the pinned image is not affected):
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:e279b580828dbfd1d7086ef6e3a78a7a993412bc0ed1631caddf65d386728cc7
                  Version: 40.20240817.0 (2024-08-17T04:51:16Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:a6620da7358f6e36b23950b4f9b22ede90a113e0762daf05563a9aa4002a681b
                  Version: 40.20240802.0 (2024-08-02T04:52:53Z)
                   Pinned: yes
```

**Comment by danilaros** [comment]
> Looks like this? https://www.reddit.com/r/Fedora/comments/1eqh3xb/it_was_a_clean_install_and_i_only_installed/

Hi. An upstream wpa_supplicant update broke WPA2/3 on all Broadcom chips. This is been already fixed in Fedora but in the latest stable image of Bluefin the bug is still present.

Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2302577

**Comment by FrantaNautilus** [comment]
The problem seems to be fixed by updating to the Bluefin 3.3 release, Wi-Fi works normally now.

**Comment by castrojo** [comment]
Ok closing for now. See you all next time when Broadcom breaks!

**Comment by danilaros** [comment]
> Ok closing for now. See you all next time when Broadcom breaks!
😄 Thank you Jorge and congratulations for this amazing project.
