### ISSUE TITLE
nvidia ISO variants do not produce working system

### ISSUE THREAD

**Issue by ylor** [ublue-os/bluefin#1592]
Firstly thanks for your work here, I really love the Bluefin model. I'm new to Linux on the desktop but not to Unix in general. After **many** unsuccessful tries to install several versions of Bluefin I finally pieced together a workaround to get a functional Bluefin system and posting here to document the issue and workaround.

# The System
Desktop system
- Chipset: B650 AORUS ELITE AX
- CPU: AMD Ryzen 7 7800X3D
- GPU: NVIDIA GeForce RTX 3080
- RAM 64GB

Happy to provide any other info needed

# The Issue
All of the currently provided nvidia variant ISOs (gts or latest) fail to produce a working system (for me). ISOs were run with both Ventoy and Balena with the same results.

## gts-39-20240804
- SHA256: `ebb170724b4b02bb1a957f524b7c7175babbccb890d2c9436aa5ac8414e758fd `
- Crashes on first launch with message `Oh no! Something has gone wrong.` and `A problem has occurred and the system can't recover. Please contact a system administrator` I read this as a kernel crash/panic but don't know enough of Fedora to capture any more relevant information. Video of first bootup sequence leading to crash below. 

https://github.com/user-attachments/assets/3a7a67fc-1a56-4e26-a650-c777c37fea9d

## latest-40-20240810
- SHA256: `9cf5d24b3d686b3094ba78ca81609a510fc988da9822169fda6748bae9b00f51`
- Boots successfully but UI is unresponsive. I am able to get a console using `CTRL+ALT+F5` but since I never created an account I don't know what credentials I could use here. Video of unresponsiveness on first boot below.

https://github.com/user-attachments/assets/33c59ad2-b303-4b3a-b776-cb12bc597a0a

# The Workaround
1. Install Fedora Silverblue (I used `Fedora-Silverblue-ostree-x86_64-40-1.14.iso`)
1. Go through setup and create your account
1. Rebase to `silverblue-nvidia:latest` or `bluefin-nvidia:latest` (maybe others, but these are the only 2 I tested) following [these](https://universal-blue.discourse.group/t/how-to-install-universal-blues-base-images/868) steps
1. UI will be very sluggish, basically unusable so press `CTRL+ALT+F5` to access console
1. Login using credentials created in step 2
1. Run `ujust nvidia`, select `set needed kernel modules`, and then reboot
1. You (should) now have a working system!
<img width="877" alt="Screenshot 2024-08-11 at 10 37 30 PM" src="https://github.com/user-attachments/assets/1f596c14-139c-4c2d-8c8c-572c1ca67624">

Edit: ~system is functional but Firefox is *very* crash happy~ Firefox issue(s) are as described here: https://universal-blue.discourse.group/t/nvidia-555-drivers-incoming-important-information/2554

**Comment by castrojo** [comment]
Sorted this out in chat, this is nvidia being nvidia unfortunately.
