### ISSUE TITLE
Breeze-GTK is not included by default on Aurora

### ISSUE THREAD

**Issue by ThoriumTextile** [ublue-os/bluefin#1596]
### Describe the bug

On any fresh install of Aurora, GTK apps will default to adwaita dark.

### What did you expect to happen?

GTK apps should use the Breeze theme, but this package is missing by default.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 36min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/aurora:stable
                   Digest: sha256:109a1480aefa1faef8f37b5de7ae143c2b2c961cd372c2415ec6fe7777944efe
                  Version: 40.20240807.0 (2024-08-07T13:32:18Z)
                     Diff: 1 upgraded
          LayeredPackages: breeze-gtk corectrl distrobox docker java-17-openjdk kontact micro wine-core

● ostree-image-signed:docker://ghcr.io/ublue-os/aurora:stable
                   Digest: sha256:109a1480aefa1faef8f37b5de7ae143c2b2c961cd372c2415ec6fe7777944efe
                  Version: 40.20240807.0 (2024-08-07T13:32:18Z)
          LayeredPackages: breeze-gtk corectrl distrobox docker java-17-openjdk kontact micro wine-core

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora:stable
                   Digest: sha256:109a1480aefa1faef8f37b5de7ae143c2b2c961cd372c2415ec6fe7777944efe
                  Version: 40.20240807.0 (2024-08-07T13:32:18Z)
          LayeredPackages: corectrl distrobox docker java-17-openjdk kontact micro
```

**Comment by ThoriumTextile** [comment]
Also `wine-core` should definitively be included by default too.

**Comment by sekalengrengginang** [comment]
> Also `wine-core` should definitively be included by default too.
is there any use case for wine being included in base image? since for wine using Bottles/Lutris is preferred

**Comment by RealVishy** [comment]
> Also `wine-core` should definitively be included by default too.

Is there any benefit to including it in the base image?I imagine most people interact with wine/proton through steam/lutris/bottles.

**Comment by ThoriumTextile** [comment]
@RealVishy @sekalengrengginang Yes, because the native wine implementation works better.  Also there's no way to interact through CLI with flatpak Wine AFAIK.

**Comment by sekalengrengginang** [comment]
i think that is out of scope for Bluefin/Aurora since flatpak is preferred way to using wine

**Comment by RealVishy** [comment]
Wine being included is out of scope for this issue, lets open a new issue for it. In regards to breeze-gtk, I'm in favour of it being included in the base image. I'm happy to open a PR to include it.

**Comment by RealVishy** [comment]
should i add the package to this repo to the main images?

**Comment by castrojo** [comment]
https://github.com/ublue-os/bluefin/blob/daeb35e3365c877165238bb768c2a25347ccc2e1/packages.json#L6 fixes this according to m2.
