### ISSUE TITLE
Please add Samsung Unified Linux Drivers

### ISSUE THREAD

**Issue by randogoth** [ublue-os/bluefin#1604]
### Describe the package

I'd like to request the package `uld` because it was the only driver that allowed me to use Samsung printers/scanners. Right now I have it layered but I think it should be part of the OS. 

More info here:

https://negativo17.org/samsung-unified-linux-driver-printers-scanners/

**Comment by castrojo** [comment]
Tracking this here: https://github.com/ublue-os/bluefin/issues/1550
