### ISSUE TITLE
Any interaction with Ptyxis terminal profiles results in empty black pane

### ISSUE THREAD

**Issue by fonnesbeck** [ublue-os/bluefin#1606]
### Describe the bug

If I try to manipulate the profiles in the Ptyxis preferences, I get an empty black pane. This occurs if I try to activate a profile by clicking on it or attempting to edit it. The panel immediately turns black and I have to restart the Ptyxis app to get rid of it.

### What did you expect to happen?

Expected to see profile preferences, etc.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:38dca9730b1bee4f70cc3bf6ec491e1f36ef29c59d38f2b8ebf2713a971329e3
                  Version: 39.20240811.0 (2024-08-11T05:52:38Z)
          LayeredPackages: 1password 1password-cli

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:9a07e503aedae790207b38e9d26b3c6dd0b6f0fa2d3913878d72b5e23236b370
                  Version: 39.20240804.0 (2024-08-04T05:53:21Z)
          LayeredPackages: 1password 1password-cli
```

### Output of `groups`

```shell
fonnesbeck wheel incus-admin lxd docker libvirt
```

**Comment by castrojo** [comment]
This is because of the old version we're putting in bluefin-gts. This will get updated in the fall, there's not much we can do about it now.

However if you `ujust rebase-helper` then rebase to bluefin:stable, which is currently Fedora 40, which fixes the issue: 

https://github.com/ublue-os/bluefin/issues/1286
