### ISSUE TITLE
`ujust ollama` should show the help by default

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1607]
Running it by itself isn't very friendly, perhaps have the help be the default? 

![image](https://github.com/user-attachments/assets/13133ab8-bf9d-4288-aa68-8d912efbffcc)

**Comment by bronson** [comment]
It would be nicer to show an interactive menu, the way the other ujust commands work. But #1611 is better than nothing!

**Comment by bronson** [comment]
... and it looks like the interactive menu is already implemented, just commented out: https://github.com/ublue-os/bluefin/blob/main/just/bluefin-tools.just#L40-L42

The code looks fine. Maybe @anoldguy wanted to implement OLLAMA_SERVICE_STATUS to remove invalid choices first?  (like installing when ollama is already installed)
