### ISSUE TITLE
Plasma crashing

### ISSUE THREAD

**Issue by haroldcrews** [ublue-os/bluefin#1612]
### Describe the bug

On two of the most recent Aurora system updates Plasma crashes shorting after logging in. It logs me out of the current session and when I attempt to log back in the PC shuts down.

### What did you expect to happen?

I expected the boot and DE log in to happen normally and not terminated the session.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-nvidia:latest
                   Digest: sha256:11c3dcca6ca21c7621437dbffd8657630dc4ece0bd7382ac77fe6248405829b7
                  Version: 40.20240818.0 (2024-08-18T04:48:17Z)
                     Diff: 40 upgraded, 6 removed, 6 added

● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-nvidia:latest
                   Digest: sha256:1ef44c8a5f48ca1a0224a01f7b20687d4f7337b80ad15d489ce23b29bfc90121
                  Version: 40.20240814.0 (2024-08-14T14:12:31Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-nvidia:latest
                   Digest: sha256:1ba1be745cf1cf4225ddad53e21a4dc17b3f4f30e6912c5d2694d7a2065eab26
                  Version: 40.20240812.0 (2024-08-12T04:49:06Z)
```

### Output of `groups`

```shell
groups
anonymousguy wheel
```

**Comment by aar65537** [comment]
I think I am having the same issue, except my PC just hangs instead of shutting down when I attempt to log back in. I'm pretty sure its an SELinux issue. If I hop into tty2 and disable SELinux with `sudo setenforce Permissive` before logging in everything works. I'm still trying to find a more permanent solution, but maybe this will allow you to login for now.

**Comment by m2Giles** [comment]
If it's SELinux put into permissive mode and look at the audit log for the offending process

**Comment by aar65537** [comment]
I'm not sure SELinux is the issue anymore. It turns out that I don't actually have to disable SELinux to fix the problem. As long as I login to tty2 before logging into KDE there is no crash. I don't actually have to do anything else, just login.

**Comment by aar65537** [comment]
I finally figured out the issue was with sddm (see sddm/sddm#1537). I was able to fix it by changing `/etc/sddm.conf.d/kde_settings.conf` from 
```
[X11]
ServerArguments=-dpi 108
```
to
```
[X11]
ServerArguments=-dpi 96
```
I don't know if this will work for everyone, but you might be able to fix your system by playing with your sddm settings.
