### ISSUE TITLE
Install `vagrant` by default on the dev image

### ISSUE THREAD

**Issue by dnikoloski** [ublue-os/bluefin#1614]

**Comment by dnikoloski** [comment]
Is there any particular reason why `vagrant` is not installed by default on the dev image?

**Comment by tepene** [comment]
> Is there any particular reason why `vagrant` is not installed by default on the dev image?

this i don't know but it can be easily installed with homebrew

```
brew tap hashicorp/tap
brew install hashicorp/tap/vagrant
``` 

source: https://developer.hashicorp.com/vagrant/install#linux

**Comment by castrojo** [comment]
I haven't tested how well vagrant works via brew but generally speaking we're cloud native so we focus on container-first tech, though since we ship libvirt and co. it shouldn't be too hard of a lift for people who want to use it.

**Comment by tepene** [comment]
> I haven't tested how well vagrant works via brew but generally speaking we're cloud native so we focus on container-first tech, though since we ship libvirt and co. it shouldn't be too hard of a lift for people who want to use it.

brew installed vagrant did work quit well for me but i struggled with the `vagrant-libvirt` plugin. But i found a solution which is more "cloud native". They offer a container image where vagrant and the vagrant-libvirt plugin is already installed: 
https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#docker--podman

I simply created the file `~/.local/bin/vagrant` with the following content:

```sh
#! /bin/env bash

docker run -it --rm \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w "${PWD}" \
  --network host \
  vagrantlibvirt/vagrant-libvirt:latest \
  vagrant "$@"
```

then `chmod +x ~/.local/bin/vagrant`. Et voila. The command `vagrant` starts the container and executes the necessary commands

![image](https://github.com/user-attachments/assets/57cbcb36-9836-41c2-af73-fc5683da3dc3)

**Comment by dnikoloski** [comment]
@tepene This works pretty good for me, and I don't need to worry about any dependencies and additional plugins.
