### ISSUE TITLE
Quadlet Management Improvements

### ISSUE THREAD

**Issue by p5** [ublue-os/bluefin#1626]
So far we've been managing Quadlets in a less-than-ideal way - defining them inline inside a Just script.  

This can certainly be improved upon.  We are facing issues where the syntax could be incorrect, the scripts are becoming overly complicated and overall both the UX and DX aren't great at all.  

I can think of a few options we have to improve these.  I will try and detail them all below.

## Option 1: Keep everything as-is

This needs to be an option.  

## Option 2: Move all Quadlets to a central GitHub repo

Keep a centralised library of Quadlets (such as the [containers/appstore](https://github.com/containers/appstore) project) and create a ujust script that picks and chooses the respective quadlet when the user requests it. 

Any logic which selects a quadlet type (i.e. CUDA/ROCM) will be done inside the ujust script.

This solves some of the challenges since we can validate the syntax is correct in CI, and developers are just writing the plain old Quadlet definitions.  No bash hackery.

## Option 3: Hardcode Quadlets into the images

Store the Quadlets in a readonly location inside the image, and configure ujust to invoke (i.e. systemctl start) the respective quadlet.
Maintenance here is slightly easier since quadlets on each system will be identical, and updates handled through the regular OS updates.

Any logic which selects a quadlet type (i.e. CUDA/ROCM) will be done inside the ujust script.

This solves the same issues as Option 2 in a simpler way, although people may complain that they have quadlets they don't want.

**Comment by p5** [comment]
Personally, I like the sound of option 2 - and we can provide a single Just script that iterates over the Quadlets, allowing the user to select the one they wanted.  Although we would need to try and handle updates.

**Comment by castrojo** [comment]
I love option 2 as well. 

You've submitted to containers/appstore before, think we can just throw everything in there? Ideally it'd be great to just help them build out a collection. 

This would be slower but if we hosted them ourselves but IMO if we shake out the quadlets first before submitting them then it'd be a good virtuous circle. We can probably do a better job encouraging people to submit to the podman repo anyway.

**Comment by m2Giles** [comment]
Strongly in favor of 2. 3 is basically what we are doing with the ubuntu/fedora distroboxes and it definitely isn't the method I would go with now.

For 2. We can use ublue-os/toolboxes. We've started branching into having apps (though admittely under a distrobox consumption model). Going upstream would be nice for spreading the good ideas.
