### ISSUE TITLE
Reinvestigate default fractional scaling settings for Framework

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1628]
https://www.reddit.com/r/framework/comments/1eymj2j/my_core_ultra_with_28k_arrived_works_great_with/

**Comment by xlionjuan** [comment]
I'm the OP, I disable fractional scaling and set scaling to 200%, looks great for me, but you can do a survey before determine.

**Comment by inffy** [comment]
There is fixes in Gnome 47 atleast for the xwayland apps. Propably Fedora 41 won't  enable that by default, so would need a FW+F41 combo to test if this makes things better.

_GNOME 47 includes an enhanced fractional display scaling feature, which provides better support for legacy X11 apps. This feature is still considered experimental and should only be used for testing. To enable it, you can run the following from the command line: gsettings set org.gnome.mutter experimental-features '["scale-monitor-framebuffer", "xwayland-native-scaling"]'_

**Comment by castrojo** [comment]
Related: https://github.com/ublue-os/bluefin/issues/1701
