### ISSUE TITLE
Aurora : Automatic Night Light Broken

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/bluefin#1641]
### Describe the bug

When enabling the automatic setting for night light in kde settings, it gets stuck locating forever.
![image](https://github.com/user-attachments/assets/ef9e2930-3c08-4956-9282-0410347e559b)

### What did you expect to happen?

Locate my coordinates and enable night light during the right times

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 3 days ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable
                   Digest: sha256:a0492cc42585cac503d397e7bbc27cab75d71aa219f3df7169e3324632d19b6f
                  Version: 40.20240828.0 (2024-08-28T20:44:57Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx:stable
                   Digest: sha256:cfcf6fae18d9231a9ba4c7df44b2b197e973cc6b3e506ce4961a87efbd69a180
                  Version: 40.20240821.0 (2024-08-22T23:14:07Z)
```

### Output of `groups`

```shell
vishwas wheel incus-admin lxd docker libvirt
```

### Extra information or context

Mozilla Location services seem to be working fine, so i think it might be trying to write to somewhere that's marked RO to save it's config and failing.

**Comment by dko0** [comment]
This appears to be an upstream issue. https://discussion.fedoraproject.org/t/geoclue-location-query-broken-due-to-mozilla-service-retirement/128262

**Comment by tulilirockz** [comment]
Upstream issue indeed, Geoclue died, you gotta set your coordinates manually. Try copying them on Google Maps and putting them there instead
