### ISSUE TITLE
Installation of aurora-dx-nvidia-40 fails

### ISSUE THREAD

**Issue by solkrans** [ublue-os/bluefin#1664]
### Describe the bug

After clicking Begin Installation it runs for a while and then I get the following error message:

> The following error occurred while installing the payload. This is a fatal  error and installation will be aborted.  

> The command 'ostree admin instutil set-kargs resume=UUID-0e17c1f0-b5c0-4ad3-93cc-65a92d62e259 rhgb quiet root=UUID=2b41ffd4-c9b4-481e-93ff-fd99787a75cd rw' exited with the code 1. 

### What did you expect to happen?

Expected to complete the installation.

### Extra information or context

I'm trying to replace a Windows 10 installation (so not dual booting) with secure boot. I turned it off, or rather set it to `Other OS` as that was the only option. I couldn't even get in to the installation app without doing that.

I'm using two disks for this. Two SSDs both Samsungs but different sizes. One as "primary" with `/`, `/boot/efi/` and `swap` and the other disk on `/home/`.

Tried to do the installation twice:  
First time the primary disk with btrfs and the home disk with ext4.
Second time the primary disk with ext4 and the home disk with ext4.

Same result both times.

I built this desktop back in 2010-2012, don't remember exactly when. I'm mentioning this because I've earlier installed Bazzite on a laptop from 2018/19 without issues. So my mind went to if my desktop is too old, if that is even possible? My other concern is if there is more configuration I have to change in the BIOS? But I wouldn't even know where to start there.

Would greatly appriciate some help.

**Comment by Malix-Labs** [comment]
Please try again using the [Bluefin Installation Runbook](https://docs.projectbluefin.io/introduction#installation-runbook)

**Comment by solkrans** [comment]
I found this through @Malix-Labs link:
https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/#manual-partition

And following that I was able to install it. It was probably the swap partition.

> Why did you add a swap partition?
I don't actually know what I'm doing. Even though I've used Linux off and on through the years I still am a noob when it comes to these things.

Anyway, Aurora froze after a while and now I can't boot into the OS anymore, and I can't boot into the install app either. I'm getting the same error as when I tried to start the install app the first time and I had forgotten to change Secure Boot to `Other OS` (don't seem to be able to turn it off? Can't find an explicit option to do that, just changing it between `Windows UEFI` and `Other OS`.) Almost feels like it's bricked.

But I don't want to take up anymore of your time, I'll figure something out, so you can close this.
