### ISSUE TITLE
Bluefin suspends with active SSH session when suspend is turned off

### ISSUE THREAD

**Issue by fbunt** [ublue-os/bluefin#1670]
### Describe the bug

I'm not sure if this belongs here, but I figured I would start here to get the ball rolling. If there is a better place for this, please let me know. I am also opening this so that others can find it and see our workaround.

We have a computer we use for remote work that is running Bluefin. The system suspend feature is turned off in the settings menu on this computer but it continued to go into the suspend state while we had active SSH sessions with jobs running. We tried multiple reboots and an update after turning it off in the menu. This is the message we received each time:

```sh
fred in 🌐 fedora in ~ 
❯ 
Broadcast message from gdm@fedora on tty1 (Fri 2024-09-06 16:31:49 MDT):

The system will suspend now!
```

We tried several things to prevent the system from suspending but what finally worked was the following commands followed by a reboot:

```sh
$ sudo -u gdm dbus-run-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing';
$ sudo -u gdm dbus-run-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0;
$ sudo -u gdm dbus-run-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'
```

We found these commands on this forum post: [link](https://forums.fedoraforum.org/showthread.php?330373-f38-The-system-will-suspend-now!)

### What did you expect to happen?

We expected the system to stop suspending after turning the feature off in the settings menu.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 19h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:afdb3367335c5137216dc09969e907031f58d2f7de185d44eddaa25b97061934
                  Version: 40.20240911.0 (2024-09-12T18:44:39Z)
            SecAdvisories: 1 low, 6 moderate, 1 important
                     Diff: 172 upgraded, 6 removed, 41 added
          LayeredPackages: gnome-shell-extension-pop-shell neovim
            LocalPackages: insync-3.9.0.60000-fc40.x86_64

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:51dd6bdcf1542e155b53f23905f29665e145d7b31028d4c614cf185145dd9faa
                  Version: 40.20240902.0 (2024-09-03T19:41:17Z)
          LayeredPackages: gnome-shell-extension-pop-shell neovim
            LocalPackages: insync-3.9.0.60000-fc40.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:57dbf5c37861b2e270957f7a2bea7423bb143e6edaa2576e1384529106d77130
                  Version: 40.20240901.0 (2024-09-02T05:20:39Z)
          LayeredPackages: gnome-shell-extension-pop-shell neovim
            LocalPackages: insync-3.9.0.60000-fc40.x86_64
```

### Output of `groups`

```shell
fred wheel lxd incus-admin libvirt docker brew-admin
```

### Extra information or context

We are running Wayland.

**Comment by castrojo** [comment]
Turning on the caffeine extension in the top right menu might be a good workaround while we investigate.

**Comment by fbunt** [comment]
Ah I hadn't seen that one. Thanks. I'll turn that on for our other machines.

**Comment by m2Giles** [comment]
You can also disable suspend in the power settings in gnome settings if you want the device to never go to sleep.
