### ISSUE TITLE
Automatic Flatpak Theming with StylePak

### ISSUE THREAD

**Issue by secretmango** [ublue-os/bluefin#1677]
### Describe the package

I am not sure if this is needed, but looks like a nice tool!

https://github.com/refi64/stylepak

This is only relevant to variants using GNOME

### Image

Silverblue

**Comment by tulilirockz** [comment]
AFAIK this is gonna be some footgun if we add this by default either as a `ujust` thing or a default setup thing. We closed a few PRs related to theming and whatever else like `MoreWaita`.

**Comment by castrojo** [comment]
This is up to the user to use if they want it.
