### ISSUE TITLE
Ship Bing Picture of the Day

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1679]
![image](https://github.com/user-attachments/assets/a044b0cc-f7a2-407b-9638-43cd637686f2)

These are too good!

I don't want to add another extension, I use [Damask](https://flathub.org/apps/app.drey.Damask) and it's great for setting a bunch of options. So I was thinking, in the containerfile just grab the upstream 4k version of the bing wallpaper of the day, and then copy it to the right place on disk, then we have it as an option just "built in" the wallpaper picker. No need to keep the history just copy over it each run.

**Comment by p5** [comment]
Not quite sure how this would work.  
AFAIK there's no way to inform the user that this is a rolling wallpaper, so may cause confusion when someone selects one wallpaper and it changes on updates.
