### ISSUE TITLE
Move to libadwaita by default

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1684]
Let's switch to stock GNOME now that we have accent colors. I guess we should keep the yaru theme on the image for those that want it. 

We need to figure out what accent color we want to set ootb. Note that we should merge this one close to release, it's best to make the change all at once when the OS updates.

**Comment by Raindrac** [comment]
> We need to figure out what accent color we want to set ootb. 

Easy! Blue for Bluefin, and purple for Aurora because it's a prominent color in the branding.

**Comment by hanthor** [comment]
resoved by: https://github.com/ublue-os/bluefin/pull/1813 ?
