### ISSUE TITLE
Unable to pull ollama docker image

### ISSUE THREAD

**Issue by tylsch** [ublue-os/bluefin#1694]
### Describe the bug

When executing the `ujust ollama install` or `ujust ollama install-open-webui` I receive the following error message:

[Cannot pull or build images due to "Error: writing blob: storing blob to file '/var/tmp/storage813872647/1': happened during read: unexpected EOF"](https://github.com/containers/podman/issues/12962)

After some research I was discovered this same issue in the Podman GitHub Repository.  This looks to be a bug when pulling down the ollama and ollama-web-ui containers as I attempted this just using the `docker pull` command.  This resulted in the following error: _layers from manifest don't match image configuration_

The fix mentioned in that is to remove pigz to be able to pull down the image and then install it again: [link](https://github.com/open-webui/open-webui/discussions/2636#discussioncomment-10389035)

Is there a potential fix for this in an upcoming release or is the mentioned fix to permanent workaround for it?

### What did you expect to happen?

Executing the `ujust ollama install` or `ujust ollama install-open-webui` should not result in error to pull down the image.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1 week 1 day ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
                   Digest: sha256:bc6ff31c60414fed3bfeb0bcffaa48ccd93faf30f2b71e0b3d57d5a4a4709aef
                  Version: 40.20240909.0 (2024-09-11T17:22:59Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
                   Digest: sha256:b95b0bd3b36be48bd4638d061c85f7e1f64ae3f396c54c5d7494d95c80962cfe
                  Version: 40.20240902.0 (2024-09-03T05:52:48Z)
```

### Output of `groups`

```shell
tylsch wheel docker incus-admin lxd libvirt
```

**Comment by p5** [comment]
Please can you try updating to a newer version (a version newer than 16th September).  

The Podman team contributed to the zlib-ng library to resolve this error, so I'm hoping the same fix works for Docker.

**Comment by tylsch** [comment]
Thanks for the response, I updated my system and was able to pull the image and get ollama and the web UI running.
