### ISSUE TITLE
Turn on xwayland-native-scaling

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1701]
Turn on xwayland-native-scaling for F41:

Looks like this is a new setting: `gsettings set org.gnome.mutter experimental-features '["scale-monitor-framebuffer", "xwayland-native-scaling"]'.`

**Comment by p5** [comment]
Enabled this in the testing branch

**Comment by hanthor** [comment]
Also resolved by https://github.com/ublue-os/bluefin/pull/1813
