### ISSUE TITLE
GNOME extensions app is not removed

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1712]
![image](https://github.com/user-attachments/assets/cf618f1b-3d51-4183-b3bb-c3ff094343eb)

We explicitly remove this in packages.json but it still shows up in the menu and exists on the image. We need to nuke this thing from orbit, it's the only way to be sure.

**Comment by p5** [comment]
I'm unable to see this app on my Bluefin installation :thinking:

**Comment by Raindrac** [comment]
Oh yeah, it's showing up on my virtual machine. Here's the default layout.
![image](https://github.com/user-attachments/assets/7c884997-3e20-4dba-9ba6-0c121797d850)

I noticed this issue a couple times, but I never thought to report it. Whoops!

**Comment by Pryka** [comment]
I don't have that app either. I'm on Bluefin-DX Stable.

**Comment by fiftydinar** [comment]
Maybe some package pulls Gnome extension as a weak dependency

**Comment by castrojo** [comment]
Yeah it looks like something else is pulling it in: https://github.com/ublue-os/bluefin/actions/runs/11085524956/job/30802038952#step:20:827

**Comment by castrojo** [comment]
p5 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 

![image](https://github.com/user-attachments/assets/8be7c385-1a18-4ffc-8bb3-b16a7f255431)
