### ISSUE TITLE
fastfetch config hardcoded for fish shell

### ISSUE THREAD

**Issue by etrigan63** [ublue-os/bluefin#1715]
### Describe the bug

Fastfetch rotates through logos in bash and zsh, but is hardcoded to dolly in the fish shell. Fish uses a config file in the immutable part of the OS to define the alias. The file is `/usr/share/fish/vendor.conf.d/bluefin-fastfetch.fish`

### What did you expect to happen?

I expected fastfetch to rotate through logos like bash & zsh. I also expect to be able to customize fastfetch to mu liking. I suggest you move the aforementioned `bluefin-fastfetch.fish` from its current location in the immutable bits to `/etc/skel/.config/fish/functions` so it gets copied to the user's home folder and can be modified. You may optionally want to do the same with the .jsonc file as well.

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1h 20min ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:d9a9e3f8d958087122f3d72e153cfdfe04029e2aaa2ca8986c9297f1370ca453
                  Version: 40.20240927.0 (2024-09-28T10:59:58Z)
                     Diff: 3 upgraded, 4 downgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:daa0c9f1dce00944e0811a9d91a0af44ea243bc1ad5388cf08dec13dd106f07b
                  Version: 40.20240926.0 (2024-09-27T21:05:27Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:6930bff60edccf0cd90624066f020c7eed3da104d6561f1d44701fff7c4ff17a
                  Version: 40.20240926.0 (2024-09-27T04:50:52Z)
```

### Output of `groups`

```shell
❯ groups
guru wheel
```

**Comment by m2Giles** [comment]
Since it's in the vendor function it can be overridden either at the system level in /etc/fish/ or at a user level in ~/.config/fish.

The reason it doesn't rotate right now is that it is simply unimplemented. PRs are welcome for matching the behavior on bash. I personally do not use fish so when I wrote this function I only implemented the static image.

**Comment by etrigan63** [comment]
It's not a simple override. You have to delete the existing alias before writing the new one. Once I get the fish file corrected I will submit a PR but I still think moving that stuff out of the immutable side is a good idea.

**Comment by m2Giles** [comment]
We could move it to /etc/fish/config.fish or something like that. The idea is that the default should be at system level so there is a copy of the original in /usr somewhere

**Comment by etrigan63** [comment]
It took me a week to track this down because they were located in the immutable part of the system. All of the references I found were for the bash/zsh version.
