### ISSUE TITLE
Switch latest back to vanilla Fedora kernel

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1717]
Bazzite needs this more than we do and some kernel developers have advised me to just keep it all stock. 

sched ext is coming in 6.12 anyway, let's go ahead and commit to ungated upstream kernel on latest. No change to stable/gts since those are on gated fedora kernels already.

**Comment by p5** [comment]
Didn't we gain something from this kernel for Framework or Surface machines?

**Comment by m2Giles** [comment]
We will still have to carry those images for the additional packages and firmware. They would share the same kernel, but CI usage would still be the same.

**Comment by bigpod98** [comment]
good that it goes back as i had to switch to stable specifically and only because of the kernel becuase FSync Kernel broke my audio

something i already talked with kyle about
