### ISSUE TITLE
Newer topgrade package

### ISSUE THREAD

**Issue by returntrip** [ublue-os/bluefin#1718]
### Describe the package

I see that you install `topgrade` from [pip](https://github.com/ublue-os/bluefin/blob/7b8091e7e882f21f8d1a9ad2847c5633a696cf48/build_files/fetch-install.sh#L16). The version provided by pip is 14.0.1 whilst the latest `topgrade` release is [15.0.0](https://github.com/topgrade-rs/topgrade/releases/tag/v15.0.0). It would be nice to get the latest and greatest as it includes a nice few things like [mise support](https://github.com/topgrade-rs/topgrade/pull/757)

### Image

All Images

**Comment by castrojo** [comment]
Good catch, this should line us back up with bazzite, thanks!

**Comment by castrojo** [comment]
This seems to have landed without the world exploding so closing for now.
