### ISSUE TITLE
Enable a `stable-daily` channel

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1736]
Benjamin and I love the coreos gated kernel but miss being up to date with everything else. But we want weekly builds for `bluefin:stable` to remain the default.

So we're thinking of an opt-in `bluefin:stable-daily` that's just built daily. Then when zstd:chunked lands we can take a look at the update cadence in general and make adjustments when necessary. Then we just add it to the selector widget in `ujust rebase-helper`. 

We could either do it in another workflow or do it logically in the existing one, whatever makes the most amount of sense. No ISOs.

**Comment by m2Giles** [comment]
We can have this be built daily and then do a check for tagging with stable weekly or if rebuild.

**Comment by castrojo** [comment]
Also might be a good time to just line up the weeklies with gts, I think it would be easier cognitive load if we knew all the weeklies fired off at once, merging things on Sundays and Mondays feel "weird" since gts and stable get skewed, announcements need to mention this, etc.

**Comment by m2Giles** [comment]
> Also might be a good time to just line up the weeklies with gts, I think it would be easier cognitive load if we knew all the weeklies fired off at once, merging things on Sundays and Mondays feel "weird" since gts and stable get skewed, announcements need to mention this, etc. 

We should definitely line everything up now. I'm okay with Monday UTC so it builds Sunday night in the US

**Comment by castrojo** [comment]
Ok once the open PR adding the new workflow lands I'll reline everything up in a fresh PR.
