### ISSUE TITLE
`ujust devmode` tries to put the user in a group that doesn't exist yet

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1755]
![Image](https://github.com/user-attachments/assets/e4dad7c3-2a92-477d-a02c-4defcc3634b9)

Just tries to add you to the dx-group when doing `ujust devmode` but this fails because you haven't rebooted yet. It should recommend to run that next step, not try to run it right away.

**Comment by m2Giles** [comment]
We need to have it copy the groups from /usr/lib/groups to /etc/groups first then add to the groups.

/usr/lib/groups are part of the read/only image so cannot append group membership there
