### ISSUE TITLE
Bluefin (and probably other Fedora-based distros) not giving correct OS name to Steam

### ISSUE THREAD

**Issue by ominoussage** [ublue-os/bluefin#1768]
### Describe the bug

Discovered it while trying to fetch my system info from Steam and pasting it into ProtonDB for contributing. Steam recognizes Bluefin as "Freedesktop SDK 23.08 (Flatpak runtime)" which is very misleading. Other distros show their names just fine, and neofetch also shows Bluefin correctly.

What's shocking is that upon looking at the Steam Hardware Survey, "Freedesktop SDK 23.08 (Flatpak runtime)" is there at the 3rd spot, which makes me realize that it's actually Fedora/Fedora-based distros on that spot.

### What did you expect to happen?

It should be the same as neofetch's second entry; in my case it's "Bluefin Archaeopteryx 39 (Silverblue) x86_64".

### Output of `rpm-ostree status`

State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1h 28min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:gts
                   Digest: sha256:5204141ff3b3b6f2230d67cefcb6100defe51cead380987a57fc5b2ed70b854b
                  Version: 39.20241006.0 (2024-10-07T17:46:11Z)
          LayeredPackages: unrar

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:gts
                   Digest: sha256:7918fda1b69b51800897dc353d50faae5afe1392e4df2324346511ace6600377
                  Version: 39.20241006.0 (2024-10-07T12:32:32Z)
          LayeredPackages: unrar

### Output of `groups`

ominoussage wheel

**Comment by Raindrac** [comment]
At the moment, Flatpak installations of Steam reporting the Flatpak runtime as the operating system is normal behavior that affects all distros. It just happens to be the case that atomic Fedora spins tend to encourage users to install Steam as a Flatpak, reducing their presence on the Steam hardware survey.

**Comment by ominoussage** [comment]
> At the moment, Flatpak installations of Steam reporting the Flatpak runtime as the operating system is normal behavior that affects all distros. It just happens to be the case that atomic Fedora spins tend to encourage users to install Steam as a Flatpak, reducing their presence on the Steam hardware survey.

Thank you for the clarification! But it being normal is just not sitting right with me. Since this seems to be more of a Steam Flatpak issue, then I'll close this issue now. I did check in the Flatpak Steam's Github and there doesn't seem to be anyone that sees it as a problem. Maybe just me?
