### ISSUE TITLE
Rebasing from `bluefin-dx-nvidia:stable` to `bluefin-dx-nvidia:latest` doesn't change the kernel

### ISSUE THREAD

**Issue by DarkGhostHunter** [ublue-os/bluefin#1775]
### Describe the bug

As title. Rebasing the image _should_ change the kernel, or at least ask to do it somewhere if not.

The kernel stays at `Linux 6.10.7-200.fc40.x86_64`, so rebasing to latest defeats the purpose.

### What did you expect to happen?

To change the kernel

### Output of `rpm-ostree status`

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
                   Digest: sha256:79fe03796db8afa2817cdbc4884b139183a84ac146a309f462c04e00bd834931
                  Version: 40.20241007.0 (2024-10-08T05:44:22Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:541d688e32fd93d81fce6cdacfa710cc37fafeb9fb4b3487c0b87d1a2d3d9b1b
                  Version: 40.20241010.0 (2024-10-11T22:19:23Z)
```

### Output of `groups`

developer wheel

**Comment by castrojo** [comment]
You're currently booted onto your `:stable` image and not the `:latest` one, which is why you still see the old kernel. That's what the dot on the left means, it's the one you're booted into, booting into latest should get you what you need.

Though the fix with the dx-group you need is incoming and these should be done in the next few minutes, when these turn green then I would do the update: 

https://github.com/ublue-os/bluefin/actions/runs/11308213011/job/31450808227

**Comment by DarkGhostHunter** [comment]
I reverted back to stable since latest didn't yield the fsync kernel, that's why you see the (Actual) ostree being stable first and latest second.

**Comment by DarkGhostHunter** [comment]
I can confirm that installing `:latest` does use the fsync kernel, but doesn't bother to rebase to `:stable` and see if the kernel remained.

**Comment by m2Giles** [comment]
The kernel is apart of the image. If you want the more up to date kernel use latest. If you don't use stable.

**Comment by DarkGhostHunter** [comment]
> The kernel is apart of the image. If you want the more up to date kernel use latest. If you don't use stable.

Did you negated the same sentence?

If changing the image doesn't change the kernel, which sounds logical, then how I can change it through `ujust`?

**Comment by m2Giles** [comment]
I did not.

Bluefin/Aurora are image based. The stable tag has a build every week. If there is a kernel update it inside the new image. Stable and GTS are using the same kernel as CoreOS which is roughly a month behind the current fedora kernel. If you want the most up to date kernel you can use the latest tag. The latest tag is built daily and whenever there is a merge.

To use the newer image you reboot into it. By default when you reboot, the newer image is selected.

You do not update the kernel separately from the image.

**Comment by DarkGhostHunter** [comment]
> If you want the most up to date kernel you can use the latest tag. The latest tag is built daily and whenever there is a merge.

Yes. Then why rebasing didn't change the kernel? Do I need to reinstall Bluefin then?

**Comment by m2Giles** [comment]
Did you reboot into the new image after running the rebase command?

**Comment by DarkGhostHunter** [comment]
Yea, by `systemctl reboot`

**Comment by m2Giles** [comment]
Checking right now. They both have different version. Again, I think you are mistaken on what it means it doesn't change the kernel.

![Image](https://github.com/user-attachments/assets/6cff036a-53c2-4517-9b7a-18e5cc6c12d9)

**Comment by DarkGhostHunter** [comment]
Doesn't the latest releases use the fsync kernel? Documentation says so.

**Comment by m2Giles** [comment]
> Doesn't the latest releases use the fsync kernel? Documentation says so.

We stopped using the fsync kernel. Please review the documentation https://docs.projectbluefin.io/administration

**Comment by DarkGhostHunter** [comment]
Ah, found the PR #1722, where they moved from fsync to stock Fedora kernel.

Before closing this absolutely, what "ungated" means? What are the difference between that and the stable/gts kernels?

**Comment by castrojo** [comment]
The stable/gts images follow this kernel cadence: https://fedoraproject.org/coreos/release-notes?arch=x86_64&stream=stable

This means it's 6.10.12 on the stable and gts channels. 

`latest` has the exact kernel that F41 has, which is 6.11.4.
