### ISSUE TITLE
bluefin-dx: toolbox wants to use wrong Fedora version

### ISSUE THREAD

**Issue by otjura** [ublue-os/bluefin#1788]
### Describe the bug

I am running Bluefin based on F40:

```
❯ uname -a
Linux aurora 6.10.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024 x86_64 GNU/Linux
```

Then, when I want to create toolbox it wants F38:

```
❯ toolbox create
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:38 (317.6MB)? [y/N]: 
```

Debugging indicates it doesn't recognize host (note empty values it's supposed to resolve):
```
❯ toolbox --log-level debug
DEBU Setting up configuration                     
DEBU Resolving container and image names          
DEBU Container: ''                                
DEBU Distribution (CLI): ''                       
DEBU Image (CLI): ''                              
DEBU Release (CLI): ''                            
DEBU Resolved container and image names  
DEBU Container: 'fedora-toolbox-38'               
DEBU Image: 'fedora-toolbox:38'                   
DEBU Release: '38'   
```

### What did you expect to happen?

Expected it to use matching Fedora version.

### Output of `rpm-ostree status`

❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
                   Digest: sha256:1f66dca5b53f6e119a7ba91d1893bdf73e89a0be7899bdcc6c4da287afd82a23
                  Version: 40.20241014.0 (2024-10-15T05:43:52Z)

### Output of `groups`

❯ groups
otso wheel

### Extra information or context

distrobox may be confused too, it wants to default to ubuntu
```
❯ distrobox create -d
podman create
--env "CONTAINER_ID=ubuntu"
--entrypoint /usr/bin/entrypoint
ghcr.io/ublue-os/ubuntu-toolbox:latest
```

**Comment by castrojo** [comment]
This is in released builds now, thanks everyone!
