### ISSUE TITLE
Support for EurKEY

### ISSUE THREAD

**Issue by mmartinortiz** [ublue-os/bluefin#1793]
Hi,

I just arrived to Bluefin on a Framework 13. So far the experience is smooth and I'm glad with the whole system. While tuning the system to my needs, I need to adjust to some new concepts, but so far, so good.

One these adjustments I'm making to my system is [EurKEY](https://eurkey.steffen.bruentjen.eu/start.html). This is a keyboard layout that I find very handy, since I type in two different European languages.

The instructions for a manual install are meant for Debian based distros. Since Bluefin is based on Fedora, and the idea is that the system is immutable, I wonder how could I install this keymap locally.

I'm looking for help either for:

- Installing EurKEY on my system
- Making a PR to make EurKEY available on Bluefin for all users (since I guess it may be useful for others)

Cheers,

**Comment by Yunraze** [comment]
You can already do this with Gnome.

1. Open `Gnome Tweaks`. 
2. Navigate to `Keyboard`.
3. Toggle the `Show Extended Input Sources` to **On**.
4. Log out of your session and back again to commit the changes.
5. Open the `Settings` app.
6. Open the `Keyboard` category.
7. Add a new input source with `+`.
8. Click the three vertical dots button for "More..."
9. You can use the search box to type in "EurKEY".
10. There are only two to pick from, "English (United States)" and "Spanish (United States)". Pick one, probably "English (United States)" is what you want.
11. You get another sub-selection and can now pick "EurKEY (US)"

I admit it's fairly involved. Not sure if it could be made easier; probably should.

**Comment by mmartinortiz** [comment]
Thanks! I never thought that it was already installed but not visible. 

I think it would be worth to have your step-by-step guide added to the Bluefin documentation, so I made a pull request with your instructions.
