### ISSUE TITLE
No network option in Bluefin DX installer

### ISSUE THREAD

**Issue by DarkGhostHunter** [ublue-os/bluefin#1800]
### Describe the bug

When I try to install Bluefin DX, the installer doesn't show any option to adjust the network settings, like connecting to WiFi.

### What did you expect to happen?

To configure the network.

### Output of `rpm-ostree status`

N/A

### Output of `groups`

N/A

**Comment by castrojo** [comment]
The ISO is offline only at this time, network setup is done after first login.

**Comment by DarkGhostHunter** [comment]
Are there plans to add network configuration on installation?

**Comment by castrojo** [comment]
We don't write the installer that comes from Fedora so we're kind of stuck with what we have currently.
