### ISSUE TITLE
Simplify reusable build tagging section

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1804]
We're enabling F41 so we don't have time to clean this up so filing it in case someone wants to flex their tagging skills. 

M2 isn't happy with this tag section, too nested, too unreadable. A refactor here would be appreciated!

https://github.com/ublue-os/bluefin/blob/71a923264e334612d3d90dff3e2b196f560eacbc/.github/workflows/reusable-build.yml#L244

**Comment by tulilirockz** [comment]
#1910 should fix this

**Comment by tulilirockz** [comment]
Got fixed with that PR! This should be good now
