### ISSUE TITLE
Background looks washed out during fade

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1814]
https://universal-blue.discourse.group/t/weird-colours-with-latest-update/4638

p5 was able to replicate. My machines look fine but they're not fading so it's likely showing up when they're supposed to be fading: 

![Image](https://github.com/user-attachments/assets/ab7bb32f-124b-482e-8c57-a708e58bd4bc)

**Comment by castrojo** [comment]
This seems to be isolated to the spring wallpaper (with the Parasauralophus)

**Comment by karypid** [comment]
I have a metallic green Lenovo and this is my favorite wallpaper because it blends with the dark green tint of the laptop. Hope this gets fixed! :-)

**Comment by castrojo** [comment]
Ok set your time to 6:15pm and the effect is more apparent. Affects spring, summer, and new autumn. Old autumn and winter seem unaffected.

**Comment by Raindrac** [comment]
Looking into this now. It's being washed out because an image is failing to load, specifically the daytime images at the beginning of sunset for each wallpaper. All monthly wallpapers are being affected. Observable at 5:25pm for January, 5:45pm for April, 5:25pm for August, 4:45pm for October, and 4:30pm for November

**Comment by Raindrac** [comment]
Alrighty, further testing has revealed that it's occurring at sunrise as well, confirming that the nighttime images are failing to load as well. This narrows the issue down to an issue with how the jxl files are encoded. I'm going to try re-encoding them and if this resolves the issue

**Comment by castrojo** [comment]
Ok raindrac pushed a revert, which I've merged and confirmed that :latest works, pushing out new gts/stable builds nowish.
