### ISSUE TITLE
GNOME theme fonts and icons lost after reset

### ISSUE THREAD

**Issue by DarkGhostHunter** [ublue-os/bluefin#1840]
### Describe the bug

Fonts and icons are reset to default (or whatever is it) after rebooting the system. No changes to these were made.

![Image](https://github.com/user-attachments/assets/84991514-4143-4790-8eb4-9c433f4b2aa2)

![Image](https://github.com/user-attachments/assets/0ee2cc79-2868-4a93-86d4-127b8a8217cd)

This also affects GNOME Greeter (where you login for the first time)

### What did you expect to happen?

To keep them as is.

### Output of `rpm-ostree status`

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
                   Digest: sha256:75fe45926ca23fe63414bc42b22f40e650decc1eae8d6d4b621e7d8e6b3721d0
                  Version: 40.20241027.0 (2024-10-27T05:46:52Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable
                   Digest: sha256:6268e5ef31ce6e6bed0b07f0c46e8fadccbfa5b7f7594008d623db1ae72376a6
                  Version: 40.20241019.0 (2024-10-20T22:26:08Z)
```

### Output of `groups`

`awesomedev wheel`

### Extra information or context

This happened to me also on `bluefin-dx:latest` this week, and I thought I botched my Linux installation somewhere. I can confirm this bug also landed on `bluefin-dx:stable`.

This could be related to #1811, where KDE also lost theming.

**Comment by castrojo** [comment]
This is on purpose: https://github.com/ublue-os/bluefin/issues/1685?issue=ublue-os%7Cbluefin%7C1683

The announcement of the switch will go out on tuesday during the release.

**Comment by DarkGhostHunter** [comment]
That explains the default font, but not the icon set.

**Comment by castrojo** [comment]
We reverted the entire theme to stock, including the icons: https://github.com/ublue-os/bluefin/pull/1813/files

**Comment by DarkGhostHunter** [comment]
I get it, you had to revert back to default since the icons don't support accent color on latest GNOME, am I right?

I was so accustomed to Ubuntu that I felt back in 2000 when I saw Inter on the greeter
