### ISSUE TITLE
broken fractional scaling

### ISSUE THREAD

**Issue by Malix-Labs** [ublue-os/bluefin#1843]
### Describe the bug

On bluefin-nvidia@40.20241027.0, the fractional scaling doesn't seem to be available and the toggle to enable it is not displayed either

![Image](https://github.com/user-attachments/assets/0f123ce6-9e29-467e-bb06-7ff8cd75b458)

### What did you expect to happen?

A working fractional scaling

Here is how it looked on the previous version

![Image](https://github.com/user-attachments/assets/f51def09-d854-48a9-9192-a3f55b5a9b32)

### Output of `rpm-ostree status`

```log
malix@malix-pc ~> rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
                   Digest: sha256:956f3bdc63735db2f34d6b77a9c82f58e8d4fdd379e2531f32d46bfcecb5baa1
                  Version: 40.20241027.0 (2024-10-27T05:46:49Z)
          LayeredPackages: google-chrome-beta

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
                   Digest: sha256:f733cc86d54895b239bb160465c8c7898bdaf4bd5fb7097d01fee6bd0c9658d4
                  Version: 40.20241019.0 (2024-10-20T22:26:03Z)
          LayeredPackages: google-chrome-beta
```

### Output of `groups`

```log
malix@malix-pc ~> groups
malix wheel docker incus-admin lxd libvirt
```

### Extra information or context

```log
malix@malix-pc ~> echo $XDG_SESSION_TYPE
wayland
```

Tried also reverting https://discussion.fedoraproject.org/t/gdk-message-error-71-protocol-error-dispatching-to-wayland-display/127927/42

By `rm -rf ~/.config/environment.d/` (`environment.d` was a directory)

Maybe something broke there ?

If I remember correctly, the `environment.d` directory didn't exist before doing the custom patch from https://discussion.fedoraproject.org/t/gdk-message-error-71-protocol-error-dispatching-to-wayland-display/127927/32

Rollbacking for now

**Comment by m2Giles** [comment]
Normally when the integer scaling options are only shown you are on an X11
session. Fractional Scaling patch is only on Wayland

**Comment by Malix-Labs** [comment]
@m2Giles 

```log
malix@malix-pc ~> echo $XDG_SESSION_TYPE
wayland
```

**Comment by BrodyB** [comment]
I also booted up Bluefin (latest branch) today on my Framework 13 to find that fractional scaling (which has always been on) was now disabled and unavailable.

![Image](https://github.com/user-attachments/assets/29857c34-edb1-42eb-bdbe-52c6484efd65)

**Comment by m2Giles** [comment]
Will take a look to see what's changed in commits.

@BrodyB when was your previous image from?

**Comment by jfturcot** [comment]
Running the following and rebooting fixed it for me:
```bash
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
```

**Comment by BrodyB** [comment]
> Will take a look to see what's changed in commits.
> 
> [@BrodyB](https://github.com/BrodyB) when was your previous image from?

I believe my previous image, when it worked fine, was from the 25th.

**Comment by Malix-Labs** [comment]
> Running the following and rebooting fixed it for me:
> 
> gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

Great!

It might be a problem with this argument not being included or escaped for some reason

Needs to be fixed upstream for sure

**Comment by mmartinortiz** [comment]
In case it is of any value, it is also happening in Framework 13 running `gts`

```bash
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:726b9cadec6c9c0cf05a0fec83cf5647e41e37e07726a31989f928e1d2af8af1
                  Version: 39.20241027.0 (2024-10-27T05:44:35Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:35148d883fbd3b07e7eed946860307cbbb44623781c5d37d032feece97aeb43e
                  Version: 39.20241019.0 (2024-10-20T22:26:25Z)

❯ echo $XDG_SESSION_TYPE
wayland

```

**Comment by Malix-Labs** [comment]
I wonder if it's also happening on vanilla Fedora Silverblue, or even Fedora Workstation

**Comment by castrojo** [comment]
Ok pushed a fix to latest but pretty sure befanyt's is probably the way to go, I could use a hand testing if you've got the hardware!

**Comment by castrojo** [comment]
Ok had a pow wow with the others, my fix for sure won't work since we have GNOME versions, so we're going with https://github.com/ublue-os/bluefin/pull/1847

When this goes greens and lands (about 30m from this post), we'll need another round of testing if people have time!

**Comment by Malix-Labs** [comment]
I will, ofc

**Comment by castrojo** [comment]
Any changes?

**Comment by Malix-Labs** [comment]
Pulling https://github.com/ublue-os/bluefin/pkgs/container/bluefin-dx-nvidia/296027933?tag=stable-daily-20241028 as I type

**Comment by Malix-Labs** [comment]
Yes, it works

**Comment by eXsoR65** [comment]
I'm facing the same but with bluefin-dx:stable
![Image](https://github.com/user-attachments/assets/2cf08414-d2ca-46c5-a728-113bb798d2cc)

**Comment by fiftydinar** [comment]
@eXsoR65 Update your system, it should be fixed

**Comment by eXsoR65** [comment]
Yeah yeah there is no update for stable (weekly) yet. So I guess it will see it on Sunday. 

![Image](https://github.com/user-attachments/assets/050e5fb3-583a-49f9-a223-f6b4c3b0aa1e)

**Comment by fiftydinar** [comment]
Ah, forgot about the Bluefin scheduled releases, I apologize

**Comment by castrojo** [comment]
We rebuilt gts with this fix on tuesday as part of the release but we were focusing on gts/latest so we didn't touch stable. 

This will rebuild tomorrow night, sorry about that, that's annoying. (Or hop onto `stable-daily` for a day.)

Next time we'll either rebuild everything on release day or just post the release announcement the same time the cron fires off.
