### ISSUE TITLE
Add tags that differentiate between update channels (stable, gts, latest) when specifying a fedora version

### ISSUE THREAD

**Issue by noahdotpy** [ublue-os/bluefin#1856]
### Describe the bug

Currently, when wanting to specify a specific fedora version it is impossible to specify also which update channel that you want. This is because stable and latest will usually use the same version and gts is currently the same version as stable is.

### What did you expect to happen?

I expect these tags to exist:
- stable-40
- gts-40
- latest-41

with the following structure being used:
- {channel}-{fedora_version}

**Comment by castrojo** [comment]
Couldn't you use the existing `40` and `41` tags in your build and then update those accordingly?

**Comment by noahdotpy** [comment]
How could we differentiate between stable and latest if we only use fedora version tags?

**Comment by castrojo** [comment]
I am confused as what you're trying to do, you mentioned that you want to use a specific fedora version until "I feel I am ready to update". When you feel you are ready to update you would increment the version. Am I misunderstanding?

**Comment by noahdotpy** [comment]
I am trying to add the following tags:
- stable-40
- latest-41
- gts-40

I am proposing to add these tags so that we can differentiate between the channels on the same fedora version but still allow the end user of the image to specifically stay on the version they want without automatically updating. This is especially a problem with `stable` and `latest` because they will usually be on the same fedora version.

**Comment by noahdotpy** [comment]
> When you feel you are ready to update you would increment the version. Am I misunderstanding?

Yes, I would increment the version in the tag (ex: 39 -> 40)


Basically what I would want is a tag that differentiates between the channels and specifies which version to use:

- latest-41
- stable-40
- gts-40

**Comment by m2Giles** [comment]
Stable explicitly isn't tied to a fedora version. It is matching the rolling model of CoreOS stable channel.

If you want to stay on a lower version use GTS or use an explicit Fedora version like 40.
