### ISSUE TITLE
Cant update stable-daily: A signature was required, but no signature exists

### ISSUE THREAD

**Issue by befanyt** [ublue-os/bluefin#1885]
### Describe the bug

Ran `rpm-ostree update` and was greeted with the following error:
```
~ ❯ rpm-ostree update
note: automatic updates (stage) are enabled
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable-daily
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists
```

### What did you expect to happen?

Update to the fresh stable-daily build

### Output of `rpm-ostree status`

```
~ ❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable-daily
                   Digest: sha256:03e4d16f0ba4c60c9ea9a4bc622a078bf369dda1b7e7ab44b2dbedeb14576997
                  Version: 40.20241103.0 (2024-11-04T05:46:57Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:stable-daily
                   Digest: sha256:aeed0b2bf408b1c706a94a53dff609a4c29421b4d6477ec0cf70edbd8a93aaf4
                  Version: 40.20241102.0 (2024-11-03T17:56:19Z)
```

### Output of `groups`

`user wheel incus-admin docker lxd libvirt`

### Extra information or context

To my limited knowledge I did some digging. Because this is the first build after the big refactor. I compared signing of the previous stable-daily and the new one.

In the [new build](
https://github.com/ublue-os/bluefin/actions/runs/11678333515/job/32517618247#step:27:13) the `DEFAULT_TAG` seems to be `stable` where in the [previous build](https://github.com/ublue-os/bluefin/actions/runs/11658759483/job/32458272921#step:29:14) that tag was `stable-daily` 

```
~ ❯ cosign verify --key https://raw.githubusercontent.com/ublue-os/bluefin/refs/heads/main/cosign.pub ghcr.io/ublue-os/bluefin-dx:stable-daily
Error: no signatures found
main.go:69: error during command execution: no signatures found
```

**Comment by herobrauni** [comment]
Can confirm, the current stable-daily throws the same error for me.
Yesterdays build installed just fine.

**Comment by m2Giles** [comment]
#1888 will also make sure that it is run with merge_group.

**Comment by m2Giles** [comment]
I can confirm that this has been resolved with those to PRs.
