### ISSUE TITLE
System Upgrade fails due to signature error

### ISSUE THREAD

**Issue by ru-fraim** [ublue-os/bluefin#1892]
### Describe the bug

On running ujust upgrade:

```
── 23:56:55 - System update ────────────────────────────────────────────────────
note: automatic updates (stage) are enabled
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-asus-nvidia:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:232
```

### What did you expect to happen?

for the system to upgrade

### Output of `rpm-ostree status`

rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-asus-nvidia:latest
                   Digest: sha256:71ee6b299efc225a2491c4f1bb512cce1ef5b44502fbb35b4425baca0047b0fb
                  Version: 40.20241028.0 (2024-10-29T04:44:21Z)
          LayeredPackages: 1password 1password-cli

  ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-asus-nvidia:latest
                   Digest: sha256:71ee6b299efc225a2491c4f1bb512cce1ef5b44502fbb35b4425baca0047b0fb
                  Version: 40.20241028.0 (2024-10-29T04:44:21Z)

### Output of `groups`

❯ groups
clint wheel incus-admin lxd docker libvirt

### Extra information or context

󱋩  aurora-dx-asus-nvidia:latest 🔐
󰣛  Aurora-dx 40 (FROM Fedora Kinoite)
  Linux 6.11.4-666.rog.fc40.x86_64
󰅐  5 mins
󰔠  Forged on Oct 27 2024
󰾰  ROG Zephyrus M16 GU604VY_GU604VY (1.0)
󰻠  13th Gen Intel(R) Core(TM) i9-13900H (20) @ 5.40 GHz
󰍛  NVIDIA GeForce RTX 4090 Laptop GPU
󰍛  Intel Iris Xe Graphics @ 1.50 GHz [Integrated]
󰧑  5.52 GiB / 30.96 GiB (18%)
  412.37 GiB / 1.86 TiB (22%) - btrfs [Read-only]
󰍹  2560x1600 @ 240 Hz (as 1706x1066) in 16" [Built-in]
󰕮  KDE Plasma 6.2.2
  KWin (Wayland)
  bash 5.2.26
  Ptyxis 46.7
  2632 (rpm), 50 (flatpak-system), 20 (flatpak-user), 33 (brew)

**Comment by castrojo** [comment]
I can confirm this as of the latest built image:

```
❯ rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-asus-nvidia:latest
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-asus-nvidia:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: A signature was required, but no signature exists
```

**Comment by ru-fraim** [comment]
Saw in another thread it was a straightford issue, should be resolved tomorrow

**Comment by castrojo** [comment]
Yeah for some reason this specific image wasn't rebuilt, we're investigating, sorry for the inconvenience!

**Comment by castrojo** [comment]
Working here after the new image was pushed.
