### ISSUE TITLE
Extra spacey text in terminal when moving to budgie

### ISSUE THREAD

**Issue by sammypanda** [ublue-os/bluefin#191]
"Ubuntu font is now missing". The UI elements and fonts used in other places on the system besides the terminal appear to be fine :) and enabling custom font works to solve it.

here is the image showing how it looks: 
![image of budgie desktop with terminal open, the font shows lots of kerning](https://user-images.githubusercontent.com/38725335/233818939-151bace2-0b26-4ad2-a3af-7e1a98cf50d5.png)

**Comment by castrojo** [comment]
This is due to us putting the ubuntu font in the image and then when you rebase to something without it this happens. We need to find a cleaner way to do the font. 

Workaround: set a new font in the terminal settings and it'll fix it.
