### ISSUE TITLE
Switch rollback-helper to bootc switch

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1913]
https://github.com/ublue-os/bluefin/blob/main/system_files/shared/usr/bin/ublue-rollback-helper

This should be using `sudo bootc switch ghcr.io/ublue-os/blah --enforce-container-sigpolicy` instead.

**Comment by DarkGhostHunter** [comment]
Does `bootc` works only when the image has no layered software? Because I wouldn't be able to rebase if the latter is true and I have layered something.

**Comment by p5** [comment]
> Does `bootc` works only when the image has no layered software? Because I wouldn't be able to rebase if the latter is true and I have layered something.

If we did this, I'd imagine there would be logic to say "if the image has no layered packages, use Bootc. Otherwise rpm-ostree"

**Comment by malte-schmidt** [comment]
I tried to implement the change and got an odd result testing it. If the command is run inside the `ublue-rollback-helper` script, I get the following error message: `ERROR Switching: Pulling: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: Requesting bearer token: invalid status code from registry 403 (Forbidden)`.

However if I just do the same on the console, i.e. run `sudo bootc switch ghcr.io/ublue-os/bluefin:41-20241109` myself it starts fetching the image...

Any ideas why this is the case?

**Comment by m2Giles** [comment]
Likely you have some mangling of the tag or image.

**Comment by malte-schmidt** [comment]
Yes you are correct. I found the issue.

**Comment by castrojo** [comment]
> If we did this, I'd imagine there would be logic to say "if the image has no layered packages, use Bootc. Otherwise rpm-ostree"

bootc also tells the user what to do if you try to switch with layers.
