### ISSUE TITLE
reusable-build.yml generates tags wrong, Bluefin/Aurora - Stable image isn't updated in GHCR

### ISSUE THREAD

**Issue by tobiasmicheler** [ublue-os/bluefin#1918]
Hi,
I have noticed, that in the action https://github.com/ublue-os/bluefin/actions/runs/11762641102 only stable-daily was published, but "standard" stable was not. 
The "standard" version should have been published though, as this run was on schedule and on a Sunday.
I looked in the "Generate tags" job of one of the runs, and only the stable-daily tags have been generated.

It seems to me that the bug is in this line: https://github.com/ublue-os/bluefin/blob/81fa6622a8658fca2df7add302095ca3e88feaee/.github/workflows/reusable-build.yml#L192

**Comment by m2Giles** [comment]
Yes, in each place in the workflows `scheduled` was used instead of `schedule`

**Comment by m2Giles** [comment]
Update is running now.
