### ISSUE TITLE
X11 login loop after update to F41

### ISSUE THREAD

**Issue by axel-kaliff** [ublue-os/bluefin#1927]
### Describe the bug

After running `ujust update` and upgrading to F41 (branch stable-daily), I can't use X11. 

I have installed the package `gnome-session-xsession` to be able to run a X11 session. 

After rebooting and trying to log in to the X11 session, it just brings me back to the locked screen and loops like that.

I checked $USER/.local/share/xorg/Xorg.0.log, and the first issue seems to be this line: 

`Failed to load module "nouveau" (module does not exist, 0)`

After which it tries to load `fbdev` and `vesa` with the same results. 

The final error message is: `(EE) failed to create screen resources(EE)`

Since Bluefin uses the proprietary NVIDIA driver, I assume Nouveau isn't installed and X11 isn't looking for the proprietary one.

The same problem happens on my ASUS laptop running the `latest` branch, so I assume I'm not the only one with this problem.

Suggestions and help would be greatly appreciated! 😊

### What did you expect to happen?

To be able to log into an X11 session.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable-daily
                   Digest: sha256:809a8d2f1a15261e769476643c02027ec253a50570b4dfd7e14c87efd48a6407
                  Version: 41.20241113 (2024-11-13T06:12:52Z)
          LayeredPackages: gnome-session-xsession gnome-shell-extension-pop-shell

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable-daily
                   Digest: sha256:809a8d2f1a15261e769476643c02027ec253a50570b4dfd7e14c87efd48a6407
                  Version: 41.20241113 (2024-11-13T06:12:52Z)
          LayeredPackages: gnome-shell-extension-pop-shell
```

### Output of `groups`

```shell
axelkaliff wheel docker incus-admin lxd libvirt
```

**Comment by tulilirockz** [comment]
X11 isnt supported by Fedora anymore (and ideally not by us anymore either). Try removing the kargs that disable nouveau with `rpm-ostree kargs --editor`.
