### ISSUE TITLE
Enable Fedora 40 builds for Aurora GTS

### ISSUE THREAD

**Issue by noahdotpy** [ublue-os/bluefin#1930]
### Describe the bug

Since bluefin is now on fedora 40 for the gts stream, aurora gts builds should now be enabled to fedora 40.

### What did you expect to happen?

I expected this to be done immediately alongside bluefin (gnome) switched over to fedora 40.

### Output of `rpm-ostree status`

```shell

```

### Output of `groups`

```shell

```

**Comment by tulilirockz** [comment]
Aurora doesnt have a GTS build tho. Maybe you are confusing it for the `:stable` builds? - They should be on F41 w/ the latest KDE

**Comment by noahdotpy** [comment]
Oh ok, I thought that Aurora had a GTS build still. I know it had one at point which was disabled due to some specific issue with that fedora version.
