### ISSUE TITLE
Include `xhost` in bluefin:stable

### ISSUE THREAD

**Issue by mmartinortiz** [ublue-os/bluefin#1932]
### Describe the package

I'd like to request the package `xhost` in `bluefin:stable` because it is required for development with software that does not support Wayland yet.

Longer story: For developing an application that still requires X support I use a devcontainer. The devcontainer uses the `initializeCommand` command to run `xhost +local:docker` and forward X with the application being developed.

The command `xhost` is present in the current `gts` running Fedora 40 but not in `stable` running Fedora 41. The package `xhost` is included with the workstation image of Fedora 41.

### Image

All Images

**Comment by tulilirockz** [comment]
Bluefin/Aurora are based on Fedora, and Fedora doesnt support X11 by default anymore, you probably can layer the xhost package yourself or run it in a distrobox, both should work fine for what you want to do

**Comment by mmartinortiz** [comment]
> Fedora doesnt support X11 by default anymore

I read that in the release notes, that it does not come preinstalled anymore. However, after I created a fresh virtual machine, I checked that the package `xhost` is preinstalled.

> you probably can layer the xhost package yourself

Since [local layering will be disabled by default next sprint](https://docs.projectbluefin.io/administration#enabling-local-layering) I prefer not to do it. Besides, if I want to feel comfortable within the Bluefin paradigm, I prefer to mess with the system as little as possible

> run it in a distrobox

What do you exactly mean? The integration between [vscode and distrobox](https://distrobox.it/posts/integrate_vscode_distrobox/) or something else?

If I still need to use distrobox to provide a development environment for a project, I'm not sure about the entire point of using [devcontainers](https://containers.dev/) as a way to provide a reusable development environment across different platforms. But this could be that I'm still too new into the Bluefin experience, distrobox and devcontainers. Any advice to get me out of my ignorance is greatly appreciated :-)

**Comment by castrojo** [comment]
In your case I would recommend explicitly allowing local layering and layering xhost. Your computer isn't going to explode, it just means that the upgrade to F42 might need manual intervention. 

Worse case you `rpm-ostree reset` and do the upgrade. I'm unsure on how long the xhost package will remain in fedora.

**Comment by hanthor** [comment]
I've already done rpm-ostree reset twice on my machine with no issue I went from Silverblue 40 --> Bluefin 40 --> Silverblue Rawhide --> Bluefin:latest --> bluefin:stable. Isn't most of the fun of all this being able to image hop?
