### ISSUE TITLE
Unable to authenticate wireless network after upgrade to 41.20241117.3

### ISSUE THREAD

**Issue by drogo35** [ublue-os/bluefin#1943]
### Describe the bug

After upgrading my Aurora system from 41.20241112.1 to 41.20241117.3, my existing wireless connection failed to connect. The supplied password (stored for current user only) did not work. Deleting and re-creating the password did not resolve the issue. I rolled back to 41.20241112.1 and was prompted for wifi password, and it then connected. Allowing the system to upgrade to 41.20241117.3 saw the inability to connect to wifi return (the system prompts for a password, but still fails to connect). 

### What did you expect to happen?

I expected the new system to use the existing wireless profile or accept the password successfully.

### Output of `bootc status`

```shell
Current booted image: ghcr.io/ublue-os/aurora-dx:stable
    Image version: 41.20241112.1 (2024-11-12 21:12:10 UTC)
    Image digest: sha256:f942d18322746e1135741bde40ef00d84c05b8ecbd39871e94260274b786b39c
Current rollback image: ghcr.io/ublue-os/aurora-dx:stable
    Image version: 41.20241117.3 (2024-11-17 15:52:27 UTC)
    Image digest: sha256:e78b70e68f068ad8e4331e636f4a488ff820fa5bbcdfa39a6643f0749414e790
```

### Output of `groups`

```shell
drogo 35wheel lxd incus-admin docker libvirt
```

### Extra information or context

The wifi connection is WPA2 Enterprise using free radius for authentication and with a certificate stored locally in ~/drogo35/documents/. The profile

**Comment by castrojo** [comment]
We need the hardware info, `lshw -c network` and paste in the appropriate wireless stanza, thanks!

**Comment by drogo35** [comment]
sudo lshw -c network
[sudo] password for drogo35: 
  *-network                 
       description: Wireless interface
       product: Wireless 8260
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: wlp1s0
       version: 3a
       serial: f2:3a:c6:b5:ce:55
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=6.11.3-300.fc41.x86_64 firmware=36.ca7b901d.0 8000C-36.ucode ip=10.0.1.34 latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:137 memory:e1200000-e1201fff


Thank you!

**Comment by Japsert123** [comment]
This might be related to this discussion: https://discussion.fedoraproject.org/t/unable-to-connect-to-wpa2-enterprise-after-upgrading-to-fedora-41/134889. There's already a bug filed for fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2326839. Hope it gets fixed soon!

**Comment by lethedata** [comment]
Definitely related to the bugzilla report @Japsert123 pointed out.

Two other ways I've found to let the connection go through are:
A) Enable `pkcs11-module-load-behavior = early` in the `/etc/pki/tls/openssl.d/pkcs11-provider.conf`
B) Enable legacy providers in `/etc/ssl/openssl.cnf`

**Comment by ash0x1b** [comment]
Enabling `pkcs11-module-load-behavior = early`  in `/etc/pki/tls/openssl.d/pkcs11-provider.conf` is probably the right way to do it.

I can confirm it works for our WPA2 Enterprise + Radius authentication.

**Comment by drogo35** [comment]
I just tested both removing pkcs11-provider.conf and setting the module load behavior value. Both allowed for a successful WiFi connection.

**Comment by castrojo** [comment]
If someone can confirm the working version we can pin it in the images: 

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/QA5NBNAOKCHXYM4BCXPLPB23FI6LQILN/#XBMSEYX5XJXNYZIAQEGCAKWT4YWEE2PE

**Comment by lethedata** [comment]
> If someone can confirm the working version we can pin it in the images:
> 

Working with or without a proper `pkcs11-provider.conf` file? I'm assuming you mean the former

**Comment by castrojo** [comment]
Yeah I think we want the one from before the change.

**Comment by castrojo** [comment]
Ok this is pinned in F41, let's see if it helps.

**Comment by lethedata** [comment]
> Yeah I think we want the one from before the change. 

Yeah, the rollback should fix things. Didn't include that config that enabled pkcs11 in OpenSSL.

**Comment by lethedata** [comment]
FYI: Per the upstream bug @Japsert123 posted (2326839), looks like they'll be updating the package to disable things until they figure out how it's going to be fixed.

https://bodhi.fedoraproject.org/updates/FEDORA-2024-fbf9ccda7b

**Comment by castrojo** [comment]
We'll hold the pin for one more week (since it's the holidays in the US).

**Comment by castrojo** [comment]
OK this is resolved for now on our end.

**Comment by ash0x1b** [comment]
Just a heads-up.

Recent `bind9` utils will start core dumping with `free(): invalid pointer`
if `pkcs11-module-load-behavior = early` was enabled in `/etc/pki/tls/openssl.d/pkcs11-provider.conf` to mitigate the issue.
