### ISSUE TITLE
Remove AI service units and functionality

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#1945]
These are poorly documented and we haven't maintained them in a while, let's just remove it all and let the user set this up how they prefer. We can basically remove everything in here: https://docs.projectbluefin.io/ai

**Comment by tulilirockz** [comment]
You mean you want to rip out the `ujust ollama` stuff? Honestly Alpaca is just such a good program that I haven't had the need to use that... Makes sense imo!
