### ISSUE TITLE
latest-41.20241113.1 not available for aurora-dx

### ISSUE THREAD

**Issue by phirestalker** [ublue-os/bluefin#1967]
### Describe the bug

I tried using the commands in the release notes to rebase to this version as I need a newer kernel.
 I ran
```
IMAGE_NAME=$(jq -r '.["image-name"]' < /usr/share/ublue-os/image-info.json)
sudo bootc switch --enforce-container-sigpolicy ghcr.io/ublue-os/$IMAGE_NAME:latest-41.20241113.1
```
and I got this error
```
ERROR Switching: Pulling: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: reading manifest latest-41.20241113.1 in ghcr.io/ublue-os/aurora-dx: manifest unknown
```

### What did you expect to happen?

I expected to use the image

### Output of `bootc status`

```shell
No staged image present
Current booted image: ghcr.io/ublue-os/aurora-dx:stable
    Image version: 41.20241117.3 (2024-11-17 15:52:27 UTC)
    Image digest: sha256:e78b70e68f068ad8e4331e636f4a488ff820fa5bbcdfa39a6643f0749414e790
Current rollback state is native ostree
```

### Output of `groups`

```shell
phire wheel docker incus-admin libvirt
```

**Comment by m2Giles** [comment]
Remove the date afterwards.

The date pins to that specific image.

**Comment by castrojo** [comment]
This specific date was a partial build, there's no aurora-dx here (just looked), I'd grab another day or just choose one from the `ujust rebase` helper to get you on the latest channel.

**Comment by phirestalker** [comment]
Thanks, I thought I was on latest. It has a new enough kernel. Unfortunately it did not fix the underlying issue. This issue is solved though.
