### ISSUE TITLE
`ujust dx-group` does not add user to dev groups

### ISSUE THREAD

**Issue by poulsky** [ublue-os/bluefin#1972]
### Describe the bug

When running the command `ujust dx-group` my user is not added the the dev groups even after a restart.

> ❯ ujust dx-group
Appending 1000 to /etc/group
[sudo] password for user: 
Appending 10 to /etc/group
Reboot system and log back in to use docker, incus-admin, lxd, libvirt.

After restart

> ❯ groups
user wheel

### What did you expect to happen?

I expected that my user was added to the dev groups.

### Output of `bootc status`

```shell
❯ sudo bootc status
No staged image present
Current booted image: ghcr.io/ublue-os/bluefin-dx:stable
    Image version: 41.20241124.2 (2024-11-24 06:01:50 UTC)
    Image digest: sha256:b89a7d095116dbc7eefaf9caf248e3e620539fb12d96fd932254364241ddd065
Current rollback image: ghcr.io/ublue-os/bluefin-dx:stable
    Image version: 41.20241124.2 (2024-11-24 06:01:50 UTC)
    Image digest: sha256:b89a7d095116dbc7eefaf9caf248e3e620539fb12d96fd932254364241ddd065
```

### Output of `groups`

```shell
user wheel
```

### Extra information or context

I have just today (24-11-2024) installed `bluefin-dx:stable` via the installation image (iso). 

Ran `ujust update` after installation.  

Initially  I only did a logout/login after running a `ujust dx-group`. I know the terminal message says to reboot, however the the docs only mentions logout/login so I went with that.

**Comment by castrojo** [comment]
This worked for me with a reboot with gts, does it work after rebooting? 

![Image](https://github.com/user-attachments/assets/8f3933b8-ed32-40b2-9207-a45d02a9e8a0)

**Comment by tulilirockz** [comment]
This seems to be a bug with the recipe itself, but logging out/logging back in does not apply/remove the groups, we probably should update the docs to mention that. This is most likely because of some lingering setting in systemd-logind being set - Stuff like `zellij` sessions don't seem to get killed on log out in my system

**Comment by poulsky** [comment]
I can confirm it now works. Thanks!
