### ISSUE TITLE
Outdated supergfxd is not compatible with ROG control center

### ISSUE THREAD

**Issue by FrantaNautilus** [ublue-os/bluefin#1976]
### Describe the bug

Upon opening `rog-control-center` from terminal, the following error is presented and ROG control center will not be able to work with supergfxd:
[WARN  rog_control_center::tray] supergfxd version = 5.1.1
[WARN  rog_control_center::tray] supergfxd found but is too old to use

### What did you expect to happen?

Expected result is opening of `rog-control-center` and being able to control power profiles, etc.

### Output of `bootc status`

```shell
Current booted image: ghcr.io/ublue-os/bluefin-dx-asus-nvidia:latest
    Image version: latest-41.20241123.4 (2024-11-23 05:12:48 UTC)
    Image digest: sha256:d2dfbd8a244a9d75767e2e9d55db0676441c395038166cd979655a86c41569fc
Current rollback image: ghcr.io/ublue-os/bluefin-dx-asus-nvidia:latest
    Image version: latest-41.20241122.3 (2024-11-22 04:59:13 UTC)
    Image digest: sha256:ea6dee9743ff337a9688a73c695d76145759c01b833cd27e56d50799d9d239ee
```

### Output of `groups`

```shell
myuser wheel docker lxd incus-admin libvirt
```

### Extra information or context

The latest version of `supergfxd` is 5.2.4, per AUR. The version of `supergfxd` Bluefin uses is sourced from COPR:
[https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/packages/](https://copr.fedorainfracloud.org/coprs/eyecantcu/supergfxctl/packages/)
where the latest version is 5.1.1. The version of `rog-control-center` in Bluefin is:
```
App and daemon versions:
      rog-gui v6.0.12
        asusd v6.0.12

Component crate versions:
    rog-anime v6.0.12
     rog-aura v6.0.12
     rog-dbus v6.0.12
 rog-profiles v6.0.12
rog-platform v6.0.12
```

**Comment by castrojo** [comment]
Ok RJ's moved this over to the staging repo, we just need to wire it up: https://copr.fedorainfracloud.org/coprs/ublue-os/staging/package/supergfxctl/

**Comment by castrojo** [comment]
https://github.com/ublue-os/akmods/pull/276

**Comment by castrojo** [comment]
This should be updated now. LMK.

**Comment by FrantaNautilus** [comment]
Thank you for such a quick response. The `supergfxd` is indeed updated and `rog-control-center` now works without problems.
```
$ rog-control-center -v

App and daemon versions:
      rog-gui v6.0.12
        asusd v6.0.12

Component crate versions:
    rog-anime v6.0.12
     rog-aura v6.0.12
     rog-dbus v6.0.12
 rog-profiles v6.0.12
rog-platform v6.0.12

[WARN  rog_control_center::tray] supergfxd version = 5.2.1
```
