### ISSUE TITLE
Docker daemon not accessible within Docker container ("Docker-in-Docker") on Bluefin DX

### ISSUE THREAD

**Issue by bennothommo** [ublue-os/bluefin#1982]
### Describe the bug

On my Bluefin DX install, I use the [Docker-in-Docker](https://github.com/devcontainers/features/tree/main/src/docker-in-docker) feature in  a VSCode devcontainer for my development environment. I have noticed that in a recent Bluefin update, the Docker daemon is no longer accessible within this devcontainer, thus I'm unable to use the Docker setup inside my development environment. 

The error message I get within the devcontainer whenever running any sort of Docker command (such as `docker images`) is:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### What did you expect to happen?

Normally, I am able to use Docker commands within the devcontainer without issue.

### Output of `bootc status`

```shell
Current booted image: ghcr.io/ublue-os/bluefin-dx:41-20241120.2
    Image version: latest-41.20241120.2 (2024-11-20 21:37:16 UTC)
    Image digest: sha256:126ea0e28210bf22f6c38a1bfd178511d9bda84f5b3548e45b5098a24ae83af8
Current rollback image: ghcr.io/ublue-os/bluefin-dx:41-20241124.5
    Image version: latest-41.20241124.5 (2024-11-24 21:24:26 UTC)
    Image digest: sha256:d0dd42ec9d6f0d1f21ea6e13c588a71de5785f8fed671b6568f9ceb5b8c4c399
```

### Output of `groups`

```shell
[my group] wheel incus-admin lxd docker libvirt
```

### Extra information or context

I ruled out all other things I can think of beforehand:

- I've run `ujust dx-group`
- I've re-built my Devcontainers in VSCode
- I've deleted the Docker containers, images and volumes and started completely from scratch.
- I've requested an older version of Docker in the devcontainer config

The only thing that has worked so far is rolling back Bluefin. In this case, I was originally on `ghcr.io/ublue-os/bluefin-dx:41-20241124.5` and it started working again when rolled back to `ghcr.io/ublue-os/bluefin-dx:41-20241120.2`,  so I can only assume that perhaps some permission or configuration for Docker that's included in Bluefin DX within those 4 days is preventing it from being used inside a container context.

**Comment by castrojo** [comment]
Not sure what's happening with this one, hopefully more eyes can help though!

**Comment by sanj2sanj** [comment]
I'm seeing the same error on aurora-dx-hwe-nvidia:

- `41.20241121` works okay.
- `41.20241122.2` - works with workaround below

```failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to register "bridge" driver: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded```



I've managed to workaround the issue by:

1. Run `sudo update-alternatives --config iptables` in the devcontainer.
2. Container was using "/usr/sbin/iptables-legacy "
3. Change to use "/usr/sbin/iptables-nft"
4. Close vscode, stop the devcontainer with  'docker stop <devcontainer name>'
5. Reopen vscode/devcontainer and run docker ps and docker run hello-world to confirm it works.

If I update-alternatives to the iptable-legacy and restart the devcontainer, the problem reoccurs.

I'm not sure what has changed in the stack but hopefully this can provide some pointers.

**Comment by bennothommo** [comment]
@sanj2sanj I can confirm that workaround works even on the most recent `latest` release. Unfortunately, I don't know much about the mechanics of iptables and/or firewalld, so I can't really help dig into it further.

**Comment by sanj2sanj** [comment]
@bennothommo no worries, thanks for confirming the workaround. 

The docker-in-docker feature explicitly [swaps to legacy iptables for compatibility](https://github.com/devcontainers/features/blob/f8e7e275b7ba2808e14a035afd753b83be68e2d9/src/docker-in-docker/install.sh#L218).

If I run `rpm-ostree install iptables-legacy`  on latest-41.20241205.1, the original devcontainer works with no workaround.

So it looks like this is just an unfortunate consequence of a legacy package being removed.

**Comment by bennothommo** [comment]
I ended up creating a custom image that installs `iptables-legacy` as well and everything works, so it's likely not an issue directly with Bluefin. Happy to close this off.
