### ISSUE TITLE
sddm using default theme on aurora:latest

### ISSUE THREAD

**Issue by RealVishy** [ublue-os/bluefin#1988]
### Describe the bug

Rebased over to aurora-dx:latest to test plasma 6.2.4 and found that it was using the default sddm theme. When looking in the SDDM settings in system settings, no sddm theme is selected.

![Image](https://github.com/user-attachments/assets/f2123b0b-9fd3-4523-a845-2b105d89980f)

### What did you expect to happen?

Expected it to use the Breeze Fedora sddm theme

### Output of `bootc status`

```shell
No staged image present
Current booted image: ghcr.io/ublue-os/aurora-dx:latest
    Image version: latest-41.20241130 (2024-11-30 05:00:43 UTC)
    Image digest: sha256:39bdacaf5e2caf7b39c5cebcaaa1ff8fffdf0b95d339c8c945a2c4b5449028f5
Current rollback image: ghcr.io/ublue-os/aurora-dx:stable
    Image version: 41.20241124.5 (2024-11-24 20:39:02 UTC)
    Image digest: sha256:36b157a6c68b6ce4aedb70f7cec5efc43372157f1f20658182c7bce2a52ac580
```

### Output of `groups`

```shell
vishwas wheel incus-admin lxd docker libvirt
```

**Comment by inffy** [comment]
Did a fresh install of aurora today with the newest -latest iso (20241124.2) and then updated to a newest image. After booting to the newest image sddm theme was gone

I did another reboot and with that the theme is back (actually added a kernel arg with rpm-ostree kargs --editor and then rebooted)

**Comment by m2Giles** [comment]
#1990 - Removing sddm workaround.

There appears to be a race condition for the mount. If a user wants to implement this themself, they can.
