### ISSUE TITLE
Include podman-compose

### ISSUE THREAD

**Issue by lehmanju** [ublue-os/bluefin#2004]
### Describe the package

I'd like to request the package `podman-compose` because it allows starting `docker-compose.yml` files directly from the host. It's cleaner/easier to do than through distrobox.

### Image

All Images

**Comment by hanthor** [comment]
Are you one the -dx image? `podman compose` is there. or is `podmand-compose` something different?

**Comment by hanthor** [comment]
https://github.com/ublue-os/bluefin/blob/4b7abfb5edfc140eaa772d80d8e90d577261a8df/packages.json#L137 it is added here

**Comment by tulilirockz** [comment]
Move to bluefin-dx, we already have podman-compose installed there
