### ISSUE TITLE
can't add user to cdrom group

### ISSUE THREAD

**Issue by fichusalon** [ublue-os/bluefin#2005]
### Describe the bug

When I execute the command : 
`sudo usermod -aG cdrom user`

The user is not added to the group cdrom even after a reboot

### What did you expect to happen?

I expected to have the user added to the group cdrom

### Output of `bootc status`

```shell
bootc status
No staged image present
Current booted state is native ostree
Current rollback state is native ostree
```

### Output of `groups`

```shell
kodi wheel lxd incus-admin docker libvirt
```

**Comment by tulilirockz** [comment]
Create the group first then add yourself to it -> `groupadd cdrom`, then `sudo usermod -aG cdrom $USER`

**Comment by fichusalon** [comment]
It looks like I can't :
`root in ~ 
❯ LANG=C groupadd cdrom
groupadd: group 'cdrom' already exists
`

**Comment by fichusalon** [comment]
Got it : https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_unable_to_add_user_to_group
