### ISSUE TITLE
Consider moving to Resources for the "Task Manager"

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/bluefin#2009]
I believe both are great applications, but specifically Resources is on the GNOME Circle, which means it is more supported by the GNOME Team and is expected to recieve updates, documentation, and whatever else they do on the GNOME Circle. It seems to have pretty much the same features as Mission Center, but it does not have the System Services view (which imo I dont think anyone uses?)

https://apps.gnome.org/Resources/

**Comment by tulilirockz** [comment]
![Image](https://github.com/user-attachments/assets/a37247ba-d1a7-4942-97df-c628def5ff46)

**Comment by tulilirockz** [comment]
Seems to also have a ton of config options

**Comment by castrojo** [comment]
I don't see a reason to change it, it's been working well for us for a long time. If people have an opinion about the task manager thing they can install it from flathub.
