### ISSUE TITLE
Shell history sometimes doesn't save into Atuin

### ISSUE THREAD

**Issue by x0ba** [ublue-os/bluefin#2010]
### Describe the bug

Sometimes when I issue commands in Bash, they don't get saved into the Atuin history menu. No changes have been made to the `.bashrc` but the initial `ujust bluefin-cli` command.

### What did you expect to happen?

Every command is saved into the Atuin history menu.

### Output of `bootc status`

```shell
No staged image present
Current booted image: ghcr.io/ublue-os/bluefin-dx:stable-daily
    Image version: 41.20241206 (2024-12-06 01:12:52 UTC)
    Image digest: sha256:94330c20b298846e910da50362e592a55502d80565c649b333e8c1d9a45780d8
Current rollback state is native ostree
```

### Output of `groups`

```shell
daniel wheel docker incus-admin libvirt
```

**Comment by hanthor** [comment]
I'm wondering if the starship prompt is clobbering the bash history. Kind like when you put a space before the command it doesn't save to history

**Comment by castrojo** [comment]
This is horribly annoying but I don't have time to investigate. This doesn't happen ootb just the people that opt into bluefin-cli, but it would be nice to figure out what's going on here.

**Comment by hanthor** [comment]
I'll try to get to bottom of it.

I'll compare what get put in the bashrc from.

https://github.com/ublue-os/bluefin/blob/main/system_files%2Fshared%2Fusr%2Fshare%2Fublue-os%2Fbluefin-cli%2Fbling.sh#L24

**Comment by x0ba** [comment]
This seems to be a problem solely with the bash implementation for atuin, as this issue doesn't happen when I'm using zsh

**Comment by phroi** [comment]
Hello Bluefin folks, thank you all for your hard work!! 🤗 

[As I was saying on Discord](https://discord.com/channels/1072614816579063828/1087140903031943178/1318505969621401610), I have the very same issue with bluefin-cli's atuin: atuin history is finnicky as it doesn't record all the commands in its own history. The same was happening before when I was trying out BlueFin in brand new VM installations. No sync account set up. Sometimes it worked, but most of the times it was finicky. To me seems that if history is recalled even one time with Ctrl+R, then it starts working properly (🤔?)

I looked a bit online and it may be some interference between atuin and  pre-exec:  https://github.com/atuinsh/atuin/issues/380

I also noticed that some changes are gonna happen to how pre-exec enter the system: https://github.com/ublue-os/bluefin/issues/2039#issuecomment-2541701630

So you may want to take a look at this while touching that part 🎯

Love & Peace, Phroi

**Comment by tulilirockz** [comment]
I've noticed [this comment](https://github.com/atuinsh/atuin/issues/380#issuecomment-1594014644) on the mentioned issue on the Atuin sources, I made a PR that forces bling.sh to be only sourced a single time, this should fix these problems, but I am not super sure if it works yet. Anyone mind testing this out? https://github.com/ublue-os/bluefin/pull/2072

**Comment by castrojo** [comment]
This seems to have fixed it for me! To test, `rpm-ostree usroverlay` to turn on write, copy the file over from the PR, then close terminal and test.

(Rebooting will put you back into "production mode".

**Comment by x0ba** [comment]
Yeah, this seems to have fixed the problem for me as well. I see the PR's already been merged, so I'll go ahead and close this issue.

**Comment by phroi** [comment]
@tulilirockz until six hours ago ATUIN was saving so nicely the shell history, right now it's broken again for me. I'm on GTS and this is the content of `bling.sh`:

```
❯ cat /usr/share/ublue-os/bluefin-cli/bling.sh
#!/usr/bin/env sh

# Check if bling has already been sourced so that we dont break atuin. https://github.com/atuinsh/atuin/issues/380#issuecomment-1594014644
[ "${BLING_SOURCED:-0}" -eq 1 ] && return 
BLING_SOURCED=1
...
```

Love & Peace, Phroi

**Comment by tulilirockz** [comment]
@phroi I believe bash-preexec is not installed by default anymore on the Bluefin image - Try running `brew install bash-preexec`, bling.sh should source it properly after that

**Comment by phroi** [comment]
Thank youuu @tulilirockz, that indeed seems to solve the issue 😁
