### ISSUE TITLE
Request to include `ddcutil` in bluefin (non -dx edition)

### ISSUE THREAD

**Issue by RVSmooth** [ublue-os/bluefin#2011]
### Describe the package

I would like to request for the package `ddcutil`

Brightness control is a crucial necessity in any devices with a screen. Fortunately KDE Plasma's [implementation of brightness control ](https://blogs.kde.org/2024/09/04/brightness-controls-for-all-your-displays/) serves the purpose of controlling external monitor brightness as well as laptop display  in KDE.

However in GNOME, there is nothing available for external monitors. Thus I want to recommend the addition of `ddcutil` to the bluefin image, by virtue of which we shall be able to control every external monitor with DDC/CI support. 

Also with [this particular extension](https://extensions.gnome.org/extension/6325/control-monitor-brightness-and-volume-with-ddcutil/) it integrates with the UI very well. or [this extension](https://extensions.gnome.org/extension/2645/brightness-control-using-ddcutil/) for multiple monitors.

![Image](https://github.com/user-attachments/assets/4552b1f8-521d-476f-8e03-7a79f8efe835)

### Image

Silverblue

**Comment by castrojo** [comment]
That does look nice! The last time we messed around and found out 😄 :  https://github.com/ublue-os/bluefin/issues/663

Are there ramifications for hardware compatibility issues?

**Comment by RVSmooth** [comment]
> That does look nice! The last time we messed around and found out 😄 : [#663](https://github.com/ublue-os/bluefin/issues/663)
> 
> Are there ramifications for hardware compatibility issues?

I do not know, but without setting up anything and just by having the ddcutil package via brew or rpm-ostree layering it just works.

**Comment by RVSmooth** [comment]
Btw `ddcutil` lays idle unless used via an extension or use it via cli. If you change your monitor's brightness using ddcutil for once, e.g., `ddcutil setvcp 10 10` it sets the brightness to 10% and physically the monitor is now at 10% brightness no daemons to always set it to the provided value.

So it shouldn't cause any issues, no?

However I think it is better to let those who got issues with `ddccontrol`  test `ddcutil` for once.

**Comment by hanthor** [comment]
I had a different extension working fine to manage monitor brightness with any package

**Comment by RVSmooth** [comment]
> Are you on Silverblue?
I am on bluefin (custom image with added ddcutil). Altho installing ddcutil via brew works as well

**Comment by hanthor** [comment]
```
~ on ☁️   
❯ which ddcutil
╭───┬─────────┬──────────────────┬──────────╮
│ # │ command │       path       │   type   │
├───┼─────────┼──────────────────┼──────────┤
│ 0 │ ddcutil │ /usr/bin/ddcutil │ external │
╰───┴─────────┴──────────────────┴──────────╯

~ on ☁️   
❯ sudo rpm-ostree status
State: busy
AutomaticUpdates: stage; rpm-ostreed-automatic.service: running
Transaction: automatic (stage)
  Initiator: client(id:cli dbus:1.10435 unit:rpm-ostreed-automatic.service uid:0)
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:96d18769cfa6759e1ce105082f0d2e7087fbdc16672cceff45037e4c1629b85d
                  Version: latest-41.20241206 (2024-12-06T01:13:02Z)
                     Diff: 2 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:5411ae2463b75eab9c1b11bee450a01be5424bd51928dd47a5d3dcb8abb2e130
                  Version: latest-41.20241205 (2024-12-05T04:58:48Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:39d51160e777ccd5faac76a23b8f23064b4ebb6c99d65d14155cd4a4a35a5483
                  Version: latest-41.20241204 (2024-12-04T04:59:25Z)

~ on ☁️   
❯ 

```

**Comment by RVSmooth** [comment]
Ahh.. then it should work finely well on non-dx edition as well

**Comment by hanthor** [comment]
Ok the request would be to explicitly add the `ddcutil` package to the base non `-dx` bluefin image

**Comment by RVSmooth** [comment]
> Ok the request would be to explicitly add the `ddcutil` package to the base non `-dx` bluefin image

updated the title

**Comment by castrojo** [comment]
Ok it's small, 1.1MB. If someone wants to PR it into packages.json I'd ack it.

**Comment by RVSmooth** [comment]
done

**Comment by RVSmooth** [comment]
Thank you @castrojo for adding this
