### ISSUE TITLE
Light/Dark theme for ublue-motd acting funky 

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/bluefin#2017]
The light/dark detection method used by ublue-motd is not working too good on environments where gsettings is misreporting light/dark color schemes, like ssh sessions, distroboxes and so on. It also does not detect it properly on KDE (but given that Aurora is splitting that is not as much of a problem anymore). 

I believe that by sending a patch upstream that allows configurable light/dark theme selection this might be resolved, but for now, what do you guys think should be done?

I believe we should just disable it for now or make it force dark mode

**Comment by fiftydinar** [comment]
I already proposed my solution for this:

```
# Default fallback theme color
THEME="'slate'"

# Accent theme color if available
if command -v gsettings > /dev/null; then
 if gsettings get org.gnome.desktop.interface accent-color > /dev/null 2>&1; then
   THEME="$(gsettings get org.gnome.desktop.interface accent-color)"
 fi
fi
```

You can add some more robust checks additionally to this if you wish

**Comment by bsherman** [comment]
I'm not sure if it's light/dark related, but I was noticing that the motd matching the accent color of GNOME... it feels a bit overdone...

The default (slate? ) is the only one which doesn't go quite as overboard, maybe?

![Image](https://github.com/user-attachments/assets/a43e5211-bc8b-4810-bc89-8502d5f7a4d5)
![Image](https://github.com/user-attachments/assets/143635df-bc53-440b-a0dc-102198ac2e0a)
![Image](https://github.com/user-attachments/assets/ccbc785e-32f7-4bb6-98fe-ef5f2f29b635)
![Image](https://github.com/user-attachments/assets/42200cbc-6bcc-425d-b0a0-949f69dc672e)

**Comment by castrojo** [comment]
Ok now that I've played with it a bit I agree it's a bit over the top. I would color the top line, because that looks good, then color the vertical/horizontal bar cross thing, and then the icons for the bullet points. And that's it.

Then leave everything else white, including the ujust section. Monochrome with the highlight box will be fine for the example commands, no need for color there.

**Comment by tulilirockz** [comment]
What you guys think about setting a lighter gray for the `code_highlight` box and using the same color for white and dark theme? - I believe that would look nice and fix the funkiness about having either a light or dark theme

**Comment by castrojo** [comment]
Sure, whatever looks awesome, dealer's choice!

**Comment by tulilirockz** [comment]
But I do agree that the accent colors on everything is quite over the top LOL - I LOVED it at first but as jorge said, after playing around with it a bit I believe it is a bit much indeed

**Comment by tulilirockz** [comment]
Hello everyone! After a bit of discussion and testing, we ended up changing the theme to this and it should work good on light/dark color schemes now since there wont be such a big difference!

![Image](https://github.com/user-attachments/assets/7636c86d-0fd8-41f8-946f-bcc139794068)
![Image](https://github.com/user-attachments/assets/88d017fb-71e9-454e-bda6-2a73f5cfd114)

**Comment by mfkp** [comment]
After pulling in the latest updates, now I'm getting this error upon opening any new terminals:

`Error: Specified style does not exist: /usr/share/ublue-os/motd/themes/\slate\.json`

Is it related to this change?

**Comment by tulilirockz** [comment]
Nope! This got fixed recently, after updating you should get this fixed
