### ISSUE TITLE
Fastfetch gives accent-color error on F40

### ISSUE THREAD

**Issue by Danar435** [ublue-os/bluefin#2055]
### Describe the bug

Executing Fastfetch on Bluefin GTS results in an error right before the output: No such key “accent-color”
![Image](https://github.com/user-attachments/assets/0ae2d020-850a-4f99-a765-198443f20ae9)

### What did you expect to happen?

There should be no error

### Output of `bootc status`

```shell
No staged image present
Current booted state is native ostree
Current rollback state is native ostree

State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:6736870a710fd6b14af5d5fe020155a40bf05cb83ac41f662862beea468ce40a
                  Version: gts-40.20241216.1 (2024-12-16T13:20:52Z)
          LayeredPackages: waydroid

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
                   Digest: sha256:c6b01cd449234fddc32720fc1bec03e95474a878d1ffacdfd85a2a43f0715aa3
                  Version: gts-40.20241208 (2024-12-08T06:12:52Z)
          LayeredPackages: waydroid
```

### Output of `groups`

```shell
kristiyan wheel audio lxd incus-admin docker libvirt
```

### Extra information or context

This should not be an issue in the next major Fedora release

**Comment by castrojo** [comment]
This is likely because there's no accent colors in the version of gnome in gts. Ideally we should skip the value if we're on F40.

**Comment by Danar435** [comment]
https://github.com/ublue-os/bluefin/blob/8512e3cccc62177fe1a9e406748237214e59ec6e/system_files/shared/usr/libexec/ublue-bling-fastfetch#L3

There is a fallback for when the gsettings command fails, but the output is printed to the users whenever that happens. This also happens with motd. I can hide it by redirecting the output to /dev/null. Should I open a PR?

**Comment by castrojo** [comment]
Yeah a PR would be lovely!
