### ISSUE TITLE
Graphical Ublue artwork on ublue fastfetch

### ISSUE THREAD

**Issue by rvsmooth** [ublue-os/bluefin#2078]
As the title says, if we use pngs to render ublue mascot images on fastfetch it will look something like this..

https://github.com/user-attachments/assets/ff81aa46-888d-4eaa-8dc8-c3a6334bd5bb

I tried this in kitty terminal (built-in image rendering support)

so if somehow image rendering can be added to ptyxis (I am unsure how) this would be nice.

[fastfetch config and function](http://bin.christitus.com/vakavukumo.rb)

**Comment by m2Giles** [comment]
Ptyxis does not have any inbuilt image viewer.

Sixels are provided for those using an alternate terminal (VSCode, kitty, foot, Konsole, etc...)

**Comment by castrojo** [comment]
Yeah our terminal doesn't support this, but even if it did we'd keep the ansi/ascii look anyway.
