### ISSUE TITLE
Epiphany Desktop File

### ISSUE THREAD

**Issue by travankor** [ublue-os/bluefin#2085]
### Describe the bug

Bluefin ships epiphany (Web) as part of the base install but the desktop file does not appear while searching for it on the desktop.

### What did you expect to happen?

Desktop file is selectable on search, dock, etc. Or remove Web from the base install.

### Output of `bootc status`

```shell

```

### Output of `groups`

```shell

```

**Comment by tulilirockz** [comment]
Bluefin does not ship epiphany by default, you can even check out the package list here. If you want to install epiphany you can install it through the flatpak

**Comment by travankor** [comment]
I installed a fresh Bluefin stable and  running `epiphany`  on the terminal starts the epiphany browser despite there being no desktop file. Maybe this shouldn't be part of the base install?
