### ISSUE TITLE
Add the ability to generate a developer image

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#225]
I like the pattern of being able to make your own desktop but then have a heavier version for yourself when making the thing. I basically wanted a Bluefin Developer Edition. 

My personal usage of this is having virt-manager and a bunch of other stuff on my main development machine but keeping my other machines with a general purpose image. I've made this here as a seperate image that derives FROM bluefin: https://github.com/castrojo/bluefin-dx

However it'd be nice to just have that pattern here so it can be cloned. Ideally it'd be nice to logically separate this image in a way that let's you have the extras and then spit that out in a bluefin-dx image. I'm looking for ideas on how to implement this as it's beyond my current skill level and would like to understand the approaches involved.

Things to consider:

- A separate package list.
- A separate containerfile or section of the containerfile where those specific changes can be included.
- A space in the repo for payloads specific to that image. For example I'd like to include more fonts for this but can't collide with the existing usr/share/fonts for the base image, that sort of thing.

**Comment by bigpod98** [comment]
usage of args is kinda what you want when it comes to many stuff. Basically seperate package list you can have a default package.json set but then if you want another one just have an arg in command(of course this makes build command more complicated).

i would go for section but if you have well written workflow a seperate containerfile works just fine as well.

with third one again i would go for an arg for defining alternative location prefix

**Comment by castrojo** [comment]
Marco fixed this, thanks! They're `bluefin-dx` and `bluefin-dx-nvidia`!
