### ISSUE TITLE
dx image needs fonts

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#235]
I'd like to get a few nice fonts in the developer experience image, 

[ ] Source Code Pro
[ ] Intel Mono

And a few others, feel free to suggest and PR them. I'm thinking something like top 10 of our favorite mono fonts

**Comment by bsherman** [comment]
[ ] Hack - `source-foundry-hack-fonts`
[ ] Fira Code - `fira-code-fonts`

**Comment by castrojo** [comment]
For the non-packaged ones we should make sure we're pulling from an upstream so they can stay up to date without us having to manually do it.

**Comment by bsherman** [comment]
> For the non-packaged ones we should make sure we're pulling from an upstream so they can stay up to date without us having to manually do it.

That's just Intel Mono at this point, right?

`adobe-source-code-pro-fonts` exists.

**Comment by 190n** [comment]
It would be lovely to include Nerd Font variants, but that might be trickier due to packaging. There seems to be a third-party repository "Terra" [which contains many of them](https://fedora.pkgs.org/38/terra/nerd-fonts-0:3.0.1-1.fc38.noarch.rpm.html), but I haven't heard of that before so I'm not sure if it is a commonly-used repository or anything. As for font recommendations:

[ ] Iosevka
[ ] JetBrains Mono - `jetbrains-mono-fonts` (but that package is not the nerd variant, see above)

**Comment by castrojo** [comment]
Great idea! We've used the terra repo before here and I've chatted with some of them so I'll take a look, our nerd font game needs to be top notch!

IBM Plex Mono is already included. I should have included what it's in there already, which is:

cascadia-code-fonts 
google-droid-sans-mono-fonts
google-go-mono-fonts
ibm-plex-mono-fonts
mozilla-fira-mono-fonts

**Comment by bsherman** [comment]
My only concern with terra repo is some intermittent reliability. I've added and removed it from my custom image twice. 

I really like what they have going on though, so maybe we could figure out why and it would be better for everyone.

**Comment by castrojo** [comment]
Yeah I've done the same thing, there's good stuff in here though so I'm going to give it a shot. Inprogress here: https://github.com/ublue-os/bluefin/pull/239

**Comment by castrojo** [comment]
OK what do people think now? The font list in my terminal looks busy and I can see that some of these are renamed versions. Sauce Code Pro? 🙄 

I'm kind of leaning towards official versions for that reason and then punting the rest to the user (we include a font downloader in the core apps).

**Comment by bsherman** [comment]
I tend towards official fonts, from official repos. If IntelMono is a need, find a good way to add it, but it's still "official".  

Need Fonts are cool, but even for developers, I think we tend to just need the one nerd font for the terminal, and only in specific cases, so I support leaving those to a font downloader.

**Comment by castrojo** [comment]
Ok enough of these are in where I'm going to close this, if anyone has any other requests then open an issue!
