### ISSUE TITLE
dx should have a Fedora userspace distrobox preloaded

### ISSUE THREAD

**Issue by marrusl** [ublue-os/bluefin#265]
It would be useful to have ctrl-alt-f bring up a Fedora userspace.

**Comment by castrojo** [comment]
Or if someone wants to PR this before me feel free, I'll try to get to it tonight Mark, but you know ... Diablo IV.

**Comment by castrojo** [comment]
Ok so right now desktop settings are shipped in this file: https://github.com/ublue-os/bluefin/blob/main/etc/dconf/db/local.d/01-ublue

I think if we did a `dx/etc/dconf/db/local.d/02-ublue-dx` with additional settings then that _should_ inherit the settings from bluefin but allow us additionally add UX things to the dx image, which is a cool idea. I'll see if this can work.

**Comment by castrojo** [comment]
Alright Mark, give it a whirl, thanks Robert!
