### ISSUE TITLE
Decouple bluefin-main from silverblue-main

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#270]
I don't think it's worth depending on rpmfusion for non-nvidia machines since we're going all in on flathub anyway. I'd like to find a way to build `bluefin-main` from upstream silverblue and also spit out the nvidia versions of images from the same repo. 

In the meantime I've prototyped an upstream-only version of bluefin here: https://github.com/projectbluefin/bluefin

**Comment by bigpod98** [comment]
Afaik main isnt dependant on rpmfusion only nvidia is
