### ISSUE TITLE
Provide out of the box fleet management

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#271]
https://cockpit-project.org/blog/cockpit-294.html

This might be a nice svelte way to manage your clients without having a bunch of extra services installed on each one.

**Comment by castrojo** [comment]
https://www.youtube.com/watch?v=LYLiblQ0hcI&t=3263s

If someone wants to look at this to help solve the fleet management use case it'd be a nice problem to solve!

**Comment by castrojo** [comment]
https://fedoramagazine.org/using-cockpit-to-graphically-manage-systems-without-installing-cockpit-on-them/

**Comment by m2Giles** [comment]
Cockpit client let's an admin have a graphical interface to a box that they can ssh into.

Is this solved just by making sure we have the necessary components for cockpit to hook into such as libvirt-dbus and cockpit-selinux?

Cockpit is a reasonable solution for a small number of installs or a lab. We also have tailscale for remote administration.

**Comment by bam80** [comment]
Cockpit still requires the machines are accessible from internet, right?
What is if they are behind a firewalls the user can't configure?

**Comment by That1LinuxGuy** [comment]
I am interested in updating Cockpit Documentation on the Universal Blue Administrator's Guide page. 
However, I am still very new to github and will likely need some guidance to start
