### ISSUE TITLE
Make a Developer mode toggle

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#274]
aka. turbo button. I think a gui app that just let's you toggle it would be awesome but we could start with a quick set of just aliases, something like:

- `just devmode-on`
- `just devmode-off`

Then just switch between the images. If someone wants to work on this I think it'd be great!

**Comment by ashish9719** [comment]
I would like to work on it. Could you please provide some details

**Comment by EyeCantCU** [comment]
> I would like to work on it. Could you please provide some details

It sounds like the goal is to add two just scripts to the justfile that switch between the normal and dx image. So essentially, to switch to dx it would just be the same command that it is in the README:

`sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin-dx:38`

And then having a script that takes you back to the regular image

Personally, I really like this idea... I might have to implement something similar in my image

**Comment by EyeCantCU** [comment]
You're also going to need to account for whether or not it's an Nvidia image

**Comment by ashish9719** [comment]
yes, I think running "lspci -vnn" while grepping for "VGA" will help in that.

Or if we check current image name contains "nvidia" or not (I think not so good).

Any comment @EyeCantCU

**Comment by EyeCantCU** [comment]
> yes, I think running "lspci -vnn" while grepping for "VGA" will help in that.
> 
> Or if we check current image name contains "nvidia" or not (I think not so good).
> 
> Any comment @EyeCantCU ??

So, here's the problem... Using lspci isn't going to work with systems using Nvidia PRIME offload. For a bit, I thought we could use glxinfo like this:
```
 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia glxinfo |grep "OpenGL render" 
````
Store the output, and look for NVIDIA as a substring, but we can't and here's why - some people may have opted through supergfxctl to disable the NVIDIA GPU altogether and go with integrated graphics... in which case that command above is useless

So... We need something set somewhere that tells us we are using an NVIDIA image. I was thinking, maybe, this might be in /etc/os-release, but it's not. Looking for solutions now

**Comment by EyeCantCU** [comment]
@ashish9719 I have a solution, but I hate it. Use `rpm-ostree kargs` and look for nvidia as a substring

**Comment by EyeCantCU** [comment]
Something like:
```
devmode-on:
  #!/usr/bin/env bash
  kargs=$(rpm-ostree kargs)
  if grep -q 'nvidia' <<< ${kargs}; then
    sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin-nvidia-dx:38
  else
    sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin-dx:38
  fi

devmode-off:
  #!/usr/bin/env bash
  kargs=$(rpm-ostree kargs)
  if grep -q 'nvidia' <<< ${kargs} ; then
    sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin-nvidia:38
  else
    sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin:38
  fi
```

**Comment by castrojo** [comment]
I have complicated this by adding a -framework image so we might want to think about a generic solution that might apply to other patterns people will use. 

For figuring out if you're on the nvidia image already, wouldn't just seeing if the nvidia kernel module was loaded be easier than digging in the kargs? Thanks everyone for taking a look, this is dope!

**Comment by EyeCantCU** [comment]
> I have complicated this by adding a -framework image so we might want to think about a generic solution that might apply to other patterns people will use.
> 
> For figuring out if you're on the nvidia image already, wouldn't just seeing if the nvidia kernel module was loaded be easier than digging in the kargs? Thanks everyone for taking a look, this is dope!

I can certainly look into that. Unfortunately, using lsmod to retrieve whether the Nvidia kernel modules have loaded won't work if someone opted to use integrated graphics via supergfxctl. This is because the modules are unloaded. So if someone has an Nvidia system, opted into using integrated graphics without hybrid functionality, and then switches images, they'd also be switched over to the main image instead of the Nvidia one. That's why I opted to outright check for kargs
