### ISSUE TITLE
VSCode defaults to investigate

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/bluefin#285]
VSCode:

For settings, ship a default config that can be overriden by user choices. 

Window > Title Bar Style (custom)
Extension: Dev Containers 

What we want:

- https://github.com/ublue-os/bluefin/pull/503

There's an issue with throwing you the container in as root but we know how to fix that.

**Comment by j1mc** [comment]
I'd recommend checking out VS Code 'profiles': https://code.visualstudio.com/docs/editor/profiles

Per the docs, a profile can include:

- Settings - In a profile-specific settings.json file.
- Extensions - The list of extensions included in the current profile.
- UI state - View layout (positions), visible views and actions.
- Keybindings - In a profile-specific keybindings.json file.
- Snippets - In a profile-specific {language}.json files.
- User Tasks - In a profile-specific tasks.json file.

**Comment by bigpod98** [comment]
config is at ~/.config/Code/User/settings.json so put that path into skel its a json file which can be edited inside vscode with json or UI
