### ISSUE TITLE
Remove the 3 Releases from this repo

### ISSUE THREAD

**Issue by alexsch01** [ublue-os/bluefin#359]
### Describe the package

It confused me when I was looking into how to install Bluefin

---

Specifically
- v1.1.0
- v1.0.0
- Test ISOs

**Comment by castrojo** [comment]
Yeah I haven't had time to test the ISO, I can geneerate a new release if you want to give it a shot?

**Comment by alexsch01** [comment]
I meant that seeing Releases in this repo confused me because the main images are the ones to use to actually install it

https://github.com/orgs/ublue-os/discussions/199

**Comment by alexsch01** [comment]
I think if would be better to hide these "Releases" for new users

**Comment by castrojo** [comment]
I removed the Test ISO one, and the current release ISOs also work, which is why we keep them there. We're hoping to get offline ISOs done at some point so hopefully it won't be so confusing!

**Comment by castrojo** [comment]
Alright new offline iso is up, this should be way less confusing.
