### ISSUE TITLE
Opening an ubuntu terminal uses fedora instead

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#383]
When we switched to `distrobox assemble` it means the box isn't built until you assemble it first. Since ctrl-alt-u runs blackbox with `distrobox enter ubuntu` it gets confused and tried to make a fedora box named ubuntu. 

Running `just assemble` before hand creates it and does the right thing. Maybe we should add this setup to yafti or something? open to ideas.

**Comment by bobslept** [comment]
I would like to investigate this further. The curent fix was setting the default container to ubuntu. I now currently experience this behavior the other way around. So my `distrobox enter fedora` creates a ubuntu box.

**Comment by bketelsen** [comment]
nice

**Comment by bobslept** [comment]
Well upstream only liked part of the PR, but unfortunately not the part that would fix our problem. So the merged PR above will not help us in this situation.

**Comment by castrojo** [comment]
Maybe a wrapper script or something that would let us template it out?

**Comment by bobslept** [comment]
I will try and see if I can work something out.
