### ISSUE TITLE
Find a common place for distrobox.ini files

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#384]
Someone showed us a nice "mlbox" distrobox they had made that setups up the official nvidia image to work just right. I'd love to ship examples like this. 

Currently we have one in `/etc/distrobox/distrobox.ini`. I'm wondering if it makes sense to move all of them to `/usr/share/distrobox` or something similar so that we can have some immutable examples that are community maintained, and that would allow us to ship a bunch of convenience distroboxes for not a lot of disk space, but give people the flexibility to copy it over to their ~ and then modify to their needs. Thoughts?

**Comment by KyleGospo** [comment]
We put ours in `/usr/share/ublue-os/distrobox/`

**Comment by castrojo** [comment]
Convention wins! Thanks!

**Comment by bketelsen** [comment]
yeah that's a win. let's follow suit in the 'Fin
