### ISSUE TITLE
Build nvidia `530` and `470` images

### ISSUE THREAD

**Issue by AdamIsrael** [ublue-os/bluefin#394]
Could we add the two older nvidia drivers to the image build? I am running an older video card and need the 470 driver.

Thanks!

**Comment by castrojo** [comment]
Adam is this all set? Not sure of the status here.

**Comment by AdamIsrael** [comment]
I'm not sure if this was ever landed or not. Bigpod had been working on it, but I ended up buying an AMD card for that machine.

**Comment by castrojo** [comment]
Well then we don't need this unless someone asks, heh.
