### ISSUE TITLE
VSCode Dev Containers asks for docker

### ISSUE THREAD

**Issue by bobslept** [ublue-os/bluefin#425]
After the remove of `podman-docker` in #407 I get a message from vscode to install docker when wanting to use `Dev Containers` extention. Which leads to `https://docs.docker.com/desktop/install/linux-install/` 
![image](https://github.com/ublue-os/bluefin/assets/38557801/ded86301-a0f3-4123-b746-9b3181eeba4a)

After layering the package myself it seems to work fine again.  Maybe reconsider adding this back in by default?

**Comment by bketelsen** [comment]
`just code-profile` adds a vs-code profile with all of this configured already!

**Comment by bobslept** [comment]
> `just code-profile` adds a vs-code profile with all of this configured already!

Ooh that is just awesome! I have seen this line 100 times but totally missed it. Nice! :smile:

**Comment by bketelsen** [comment]
can we close this issue @bobslept - and if current documentation isn't sufficient open a new one for docs?

**Comment by bobslept** [comment]
yes
