### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#43]
Browsers probably need their own section in yafti so let's just do that, and then additionally for each one fix their PWA thing like so: 

    flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.microsoft.Edge

Then we should make a preset list of "Google Workspace", "Microsoft Office Stuff" set of .desktop files and put them in there too so that people can have their cloud calendars, office, mail just ootb and it's just .desktop files so no disk space issues.

**Comment by castrojo** [comment]
![image](https://user-images.githubusercontent.com/1264109/225815429-8cf49178-0c45-4621-8c60-982ebb64d4ad.png)

They also look great! Edge can just generate these, I just need to generalize the files themselves a bit and all yafti needs to do is copy them to ~/.local/share/applications.

**Comment by EinoHR** [comment]
Shouldn't this be in ublue-os/config? Also, atleast having an optional override for something other than Edge would be cool, since there are very likely Linux users who *do not* want the microsoft-reskinned chrome.

**Comment by castrojo** [comment]
People who believe that are not the target audience for this image.

**Comment by castrojo** [comment]
https://github.com/linuxmint/webapp-manager has logic for generating PWAs for flatpakked browsers, we should template that out on generation depending on the one the user is using.

**Comment by EinoHR** [comment]
> People who believe that are not the target audience for this image.

I know I'm not, but I'll just leave this random article here
https://thomask.sdf.org/blog/2023/03/18/the-dark-defaults-of-microsoft-edge.html

**Comment by castrojo** [comment]
Ok this should be the way forward, EndlessOS has nailed the UX, this is what we should investigate: https://mastodon.blaede.family/@cassidy/110159920076176643

**Comment by castrojo** [comment]
Grabbed this from my endless install: 

```
endless:~$ gsettings get org.gnome.software external-appstream-urls
['https://appstream.endlessos.org/app-info/eos-extra.xml.gz']
```

**Comment by castrojo** [comment]
More background info: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1553

**Comment by castrojo** [comment]
Alright this is in the `ublue-os/beyond` image, I'm playing with it there and then I'll bring it over to here once we familiarize ourselves with it.

**Comment by orowith2os** [comment]
> --filesystem=~/.local/share/applications

There's a better solution here, although I don't think everyone implements it: the [DynamicLauncher](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.DynamicLauncher) portal. 

GNOME has this implemented since March of last year: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/27

KDE: https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/commit/d5f958e149705e27bbba9f3bbec659ff5bed1d80

Is there an upstream bug report for DynamicLauncher support in Chromium and Firefox yet? Epiphany (GNOME Web) already supports this portal.

**Comment by aadilayub** [comment]
Doesn't bluefin already have PWA support? I've been able to install PWAs from the store for a couple months.

![image](https://github.com/ublue-os/bluefin/assets/31581044/9f096408-2caa-43a6-bc9d-9bf06e3995e0)

**Comment by castrojo** [comment]
How's it working out for you? They're still a bit jank for me. Most of the apps people use (like Office 365) still kinda don't work right, I'm debating just setting these up by hand and then having a section in yafti that just pulls in edge when you select them.

**Comment by aadilayub** [comment]
TBH I don't use them that much. A bunch of the PWAs I need aren't in there, and they all run in Epiphany, which doesn't have the best performance. Still nice to have them discoverable in the store, though. I just wish the selection was larger.

**Comment by m2Giles** [comment]
> https://github.com/linuxmint/webapp-manager has logic for generating PWAs for flatpaked browsers, we should template that out on generation depending on the one the user is using. 

I think we should consider adding this. We now have the chrome flatpak override for PWAs and Edge has them out of the box. We are also currently packaging this but do not install on bluefin/Aurora.

This could be a solution for a bit better integration compared to the current export app button.
