### ISSUE TITLE
Wrong grub parameters for Framework 13 laptop on bluefin-dx-framework

### ISSUE THREAD

**Issue by bmp** [ublue-os/bluefin#444]
Hello, 

I am have a Framework 13 laptop, and it comes with an Integrated GPU (mine is the 11th Generation Intel model), i.e Iris Xe Graphics as indicated Frame.work's [website](https://frame.work/products/laptop-diy-11-gen-intel?tab=specs). However, the `bluefin-dx-framework` edition has the following parameters for GRUB,

`GRUB_CMDLINE_LINUX="rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 rd.luks.options=discard rhgb quiet"`

As posted in the [discussion](https://github.com/orgs/ublue-os/discussions/207), is this intentional? If not, can this be removed in newer builds?

**Comment by bmp** [comment]
As suggested, I have removed the noveau and nvidia portion using `rpm-ostree kargs --editor`, the new file reads,

`rd.luks.options=discard rhgb quiet root=UUID=035cb8ce-3f98-450c-b408-067ed085279b rootflags=subvol=root rw module_blacklist=hid_sensor_hub nvme.noacpi=1 tpm_tis.interrupts=0 rd.luks.options=discard`

Here is the output of `cat /proc/cmdline`,
```
BOOT_IMAGE=(hd0,gpt2)/ostree/default-89803050ac8cf78abe750ba86d4766e074e393d73b36c1fa9e0188f6ea09f05c/vmlinuz-6.4.12-200.fc38.x86_64 rd.luks.options=discard rhgb quiet root=UUID=035cb8ce-3f98-450c-b408-067ed085279b rootflags=subvol=root rw module_blacklist=hid_sensor_hub nvme.noacpi=1 tpm_tis.interrupts=0 rd.luks.options=discard ostree=/ostree/boot.1/default/89803050ac8cf78abe750ba86d4766e074e393d73b36c1fa9e0188f6ea09f05c/0
```


However, I see the following (duplicate entries and maybe wrongly timestamped) in the Grub when I boot,
```
Fedora Linux 38.20230827.0 (Bluefin) (ostree:0)
Fedora Linux 38. 20230827.0 (Bluefin) Costree:1)
Fedora Linux 38.20230827.0 (Bluefin) (astree:0)
Fedora Linux 38.20230827.0 (Bluefin) Castree:1)
UEFI Firnware Settings

```

While I had installed Bluefin for the first time yesterday and only layered neofetch, today I ran `rpm-ostree kargs --editor`, shouldn't the new entry reflect today's date? Or does running kargs option only change previous entry and not produce a new image?

**Comment by bobslept** [comment]
We currently not set those kargs automaticly. Even for the nvidia where they are for we ask the user to set them manually in the installation [guide](https://universal-blue.org/images/nvidia/#2-set-kargs-after-rebasing). 

Good to hear you were able to remove them. They should not change automaticly, until you do it yourself. By hand via `rpm-ostree kargs` or maybe by `just someaction`. So they will stay as you have them at this moment.

Then on the grub menu. The duplicate lines are a bug, which they are [working](https://github.com/fedora-silverblue/issue-tracker/issues/120#issuecomment-1684920408) on. That is the two times `ostree: 1` and `ostree: 0` you see in your menu. I think it will be fixed in F39, but don't take my word on it. 

Last but not least, the timestamp. We are base our main image on another image provided by fedora from [overhere](https://quay.io/repository/fedora-ostree-desktops/silverblue) and build an image from that every 24h. So it could be that timestamp, that represent the build date of the image upstream is a day off. An example. 

```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 8min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:38 (index: 0)
                   Digest: sha256:52a0216618333074a64ebb64e284da6ec03cf03195adb7a5aa15d4957113a440
                  Version: 38.20230828.0 (2023-08-28T10:09:48Z)
                   Commit: b30f0870805e7e0d9985f71df0d653835acc93c03dca6d481836d419ec69f8f2
                   Staged: no
                StateRoot: fedora

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:38 (index: 1)
                   Digest: sha256:d42fd6c5b7fdb8d774433de39fb8d23fc90f96ea2147bc8418225ef6af326aed
                  Version: 38.20230827.0 (2023-08-28T01:05:20Z)
                   Commit: d21b5c1c79b1b8862f80b5d0788b4a8071aadca4ca6e6478d9be4970951131c2
                StateRoot: fedora
```

The ostree index 1 I build this night on the 28 but has a version of 27 of august (which you see in grub). Index 0 was build on the regular scheduled rebuild this morning and there we see the timestamp matching with the day. I hope that makes a little sense all together.

**Comment by bmp** [comment]
@bobslept, thank you for the detailed explanation!

1. I have followed the [guide](https://universal-blue.org/images/bluefin/framework/) provided to run `just framework-13`. Based on the [Just page](https://universal-blue.org/guide/just/), I checked the [repo](https://github.com/ublue-os/config/tree/main/build/ublue-os-just), to check for the framework-13 command and couldn't find it! Is there another place for me to look at?

2. For the duplicate entries in GRUB, the issue you have [linked](https://github.com/fedora-silverblue/issue-tracker/issues/120#issuecomment-1684920408) to actually states,
```
This is still planned to be included in F39 but not there yet due to https://pagure.io/workstation-ostree-config/pull-request/330#comment-190406 (the PR has been reverted).

The test images ([gitlab.com/fedora/ostree/ci-test](https://gitlab.com/fedora/ostree/ci-test)) include this already. The Universal Blue images should as well.
```
This would mean Universal Blue images should not have duplicate entries right? Or are they referening to Universal Blue images for F39?

3. The timestamp makes sense now :-). However, when I do an `rpm-ostree install <package>`, it rebuilds an image now on my machine right? As an example, here is my output from `rpm-ostree status`,
```
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx-framework:38
                   Digest: sha256:0222a22f6479f6e51d5f77d024783b0ba4c9b2bfe4a62be95be8010728b04f71
                  Version: 38.20230828.0 (2023-08-28T10:12:40Z)
          LayeredPackages: neofetch

  ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx-framework:38
                   Digest: sha256:1715fa05ad1684a49f091b338964521f577d2ae089cb19bee5b60b04c0b81ece
                  Version: 38.20230827.0 (2023-08-28T01:07:18Z)
          LayeredPackages: neofetch
```

Now here is the output of `rpm-ostree status` after I install some packages with `rpm-ostree install`,

```
  ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx-framework:38
                   Digest: sha256:0222a22f6479f6e51d5f77d024783b0ba4c9b2bfe4a62be95be8010728b04f71
                  Version: 38.20230828.0 (2023-08-28T10:12:40Z)
                     Diff: 6 added
          LayeredPackages: libdwarf libserf neofetch patch patchutils utf8proc

● ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx-framework:38
                   Digest: sha256:0222a22f6479f6e51d5f77d024783b0ba4c9b2bfe4a62be95be8010728b04f71
                  Version: 38.20230828.0 (2023-08-28T10:12:40Z)
          LayeredPackages: neofetch

  ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx-framework:38
                   Digest: sha256:1715fa05ad1684a49f091b338964521f577d2ae089cb19bee5b60b04c0b81ece
                  Version: 38.20230827.0 (2023-08-28T01:07:18Z)
          LayeredPackages: neofetch
```

But in GRUB I still see them as images from yesterday!

**Comment by bobslept** [comment]
Yeah I have no clue where those kargs came from. The only other place I can find them are in the [just file](https://github.com/ublue-os/config/blob/70634bf0d9fa9d506052cc764de45d0eac59d3c0/build/ublue-os-just/nvidia.just) for nvidia. I have rebased to a `bluefin-dx-framework` image and it didn't set those kargs for me. The `just set-kargs-nvidia` which sets these kargs is available so if that would be run by the user, it ends up with those kargs. Maybe you can look for it in your bash history like `history | grep nvidia` to see if that has been run by accident?

I have rebased to the `silverblue:38` from upstream I mentioned and it still had the double entries in grub. That's were we are building of currently. And also rebased also to `silverblue:39` which also has the double grub lines. So I am not sure.

**Comment by bmp** [comment]
An uptade: I am on `bluefin-framework` and see no problem when I run `just framework-13`.

Where can I read what the `bluefin-dx-framework` adds in addition?

**Comment by bobslept** [comment]
The dx stands for developer experience. Like  `bluefin-framework` what will stands for bluefin + framework addons. Bluefin-dx-framework wil give you bluefin + developer experience + framework addons. You can read more about bluefin-dx ships and what it's all about over [here](https://universal-blue.org/images/bluefin/developer-experience/). It adds things like VScode, virt-manager and lots more.

**Comment by bmp** [comment]
@bobslept  thank you!
