### ISSUE TITLE
Codecs for Firefox

### ISSUE THREAD

**Issue by bmp** [ublue-os/bluefin#445]
I am on ` bluefin-dx-framework` currently and have followed the instructions in the [documentation](https://universal-blue.org/guide/codecs/), but I do not get the codecs as listed in the guide. 

Here are the relevant outputs,
1. `flatpak list --runtime | grep ffmpeg-full`
```
ffmpeg-full	org.freedesktop.Platform.ffmpeg-full		22.08	system
ffmpeg-full	org.freedesktop.Platform.ffmpeg-full		22.08	user
```
2. `about:support` screenshot of the media section from Firefox,

![image](https://github.com/ublue-os/bluefin/assets/1095177/f92d37b6-badc-4c58-9537-79f9c4cf8273)

3. The screenshot of `about:config` from Firefox for `media.ffmpeg.vaapi.enable`

![image](https://github.com/ublue-os/bluefin/assets/1095177/db36efd4-080e-4009-a6fa-6d378a0c8e84)

4. And a screenshot of the version of Firefox,

![image](https://github.com/ublue-os/bluefin/assets/1095177/a0bf4c2a-c907-4250-894f-980ea41a9a92)

Please do let me know if I am doing something wrong.

**Comment by castrojo** [comment]
Mine looks like yours now but my support looks correct when I do `vainfo`. What's yours look like? I wonder if it's a UI change in the update because it used to look like that but doesn't anymore.

**Comment by bmp** [comment]
Here is the output of `vainfo`,

```
Trying display: wayland
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.2)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

**Comment by bmp** [comment]
This gets stranger! I installed `wl-clipboard` for another package, `espanso`, which I need, and here is the new screenshot on Firefox,

![image](https://github.com/ublue-os/bluefin/assets/1095177/00892b73-73f2-4b6b-a9e8-3c52af6df10b)

And here is the output of `sudo rpm-ostree status`,
```
● ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-framework:38
                   Digest: sha256:9aa8c8aaf9422237160bcdfac4f7a71577e47c027c3efacbe728b944411bd281
                  Version: 38.20230828.0 (2023-08-28T21:25:50Z)
          LayeredPackages: wl-clipboard

  ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-framework:38
                   Digest: sha256:1858e9b96abd23f7b90284b1fa07350dd9b5c0c911c5a8b141501632d40022bc
                  Version: 38.20230828.0 (2023-08-28T15:19:05Z)
```

**Comment by castrojo** [comment]
Huh. I have no idea what is happening here.

**Comment by bmp** [comment]
Can anyone else check if having `wl-clipboard` layered makes this change in firefox `about:support` page?

**Comment by bobslept** [comment]
My laptop with AMD 4800u cpu with integrated graphics shows this after only changing `media.ffmpeg.vaapi.enabled=true` and having `org.freedesktop.Platform.ffmpeg-full` installed. 

![image](https://github.com/ublue-os/bluefin/assets/38557801/335e60ed-c1b5-4e9f-9b26-c19316228860)

I've reset the flatpak permissions via flatseal to be sure it's all default. The picture above does only show this after playing a media file otherwise I get this first:

![image](https://github.com/ublue-os/bluefin/assets/38557801/59b3d239-9816-4100-bcee-8c074bcc554f)

On my dekstop with AMD Raden RX 6600 graphics card
![image](https://github.com/ublue-os/bluefin/assets/38557801/ec310e08-dd4f-434a-af40-fa7388be88fb)

This is on `bluefin-dx` without any layered packages.

**Comment by bmp** [comment]
> Semi-related since you mentioned the clipboard, should we ship this? https://github.com/Slackadays/Clipboard
> 
> Let's split that off in an issue (if you agree) because I'd like to just fix that as a whole.

Seems really impressive, hadn't come across it before, I think it might be useful.

**Comment by castrojo** [comment]
This all appears to be working.
