### ISSUE TITLE
Requesting Solaar

### ISSUE THREAD

**Issue by bmp** [ublue-os/bluefin#453]
### Describe the package

[Solaar](https://pwr-solaar.github.io/Solaar/) is Linux manager for many Logitech devices that connect wirelessly to a USB/Bluetooth,/Unifying Receiver/etc. It is also available on the Fedora [repos](https://src.fedoraproject.org/rpms/solaar). As someone who uses and ergonomic mouse, this would be really useful for me. They don't have a flatpak at this point and it seems like it isn't going to be done [soon](https://github.com/pwr-Solaar/Solaar/issues/1859).

### Image

All Images

**Comment by bmp** [comment]
Thank you for adding Solaar, makes a big difference for people like me :-)

**Comment by castrojo** [comment]
I have like 5 of these dongles and had forgotten about this tool entirely so I'm glad we got this sorted!
