### ISSUE TITLE
How to handle disabled application in yafti, but expected by bluefin

### ISSUE THREAD

**Issue by bobslept** [ublue-os/bluefin#471]
It could happen for example that a user disables `Blackbox terminal` on first run, because why do I need another terminal? Which is totally understandable. But can lead to unexptected behavior.

The problem may occur that we inside `bluefin` point shortcuts to blackbox because we expect it to be installed, which then would not work anymore. Is this something we need to fix? And if so, what would be the best way?

**Comment by castrojo** [comment]
Maybe in the description we could mention that it's necessary for development or something? We could also just switch to the RPM?

**Comment by bobslept** [comment]
Oh that would be an easy solution indeed. Just add `(Expected)` or something after the package name. And say in the description. That expected package by bluefin are marked with `(Expected)` in the description.

**Comment by bobslept** [comment]
How about moving the core applications to a seperate screen like this:
![image](https://github.com/ublue-os/bluefin/assets/38557801/48843ef8-f2ae-4dbc-a2d9-10bb827beb2d)
And after this configure the other applications:
![image](https://github.com/ublue-os/bluefin/assets/38557801/5faa6bdc-8be4-423b-94c0-2728fcdbf136)

**Comment by castrojo** [comment]
Yeah sounds good to me!
