### ISSUE TITLE
Steam flatpak lost NTFS compatibility

### ISSUE THREAD

**Issue by GenieDev101** [ublue-os/bluefin#482]
After the latest bluefin update, Steam can no longer successfully launch while having mounted a secondary HDD with an NTFS partition.
The steam flatpak can be launched successfully without the NTFS partition. mounted

Let me know if I can provide any additional information to help resolve this issue.

**Comment by castrojo** [comment]
Not sure how to help you with this, sorry.

**Comment by KyleGospo** [comment]
NTFS is not recommended by Valve.
