### ISSUE TITLE
Ship Docker 

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#483]
We're going to end up special casing every tool people want in order to make them work with Podman when they expect Docker. 

So let's just save ourselves a bunch of time and ship it on the -dx image. 

https://docs.docker.com/engine/install/fedora/

And then if we need to do post-config `just docker` to do the other stuff then we can do that. But ideally the least amount of friction. I think @bketelsen has some other setup things we might want to add.

**Comment by bketelsen** [comment]
from my notes:

## sysctl - net.ipv4_forwarding 1

before moby engine! otherwise docker installs ipfilter chains that discard all traffic not bound for docker interfaces.

## Docker

```
sudo rpm-ostree install moby-engine

```

### bring docker group into /etc/

```
grep -E '^docker:' /usr/lib/group | sudo tee -a /etc/group
```

**Comment by bketelsen** [comment]
some or all of those notes may be irrelevant for the docker-ce repo, but I'm betting the ipv4_forwarding one is still relevant

**Comment by castrojo** [comment]
Let's keep this open for a bit in case there's follow up discussion after we play with it.

**Comment by p5** [comment]
Would be awesome if we can check with the new contacts at Docker to see when they may be publishing Docker in the Fedora 39 test or nightly repos (see [here](https://download.docker.com/linux/fedora/))

Fedora 38 builds seemed to be quite late if I remember correctly

Would be great to get some nightly or test builds soon so we can trial stuff out on the newer versions of Fedora 😄

**Comment by aadilayub** [comment]
Are there any gotchas when using docker and podman on the same machine?  

If I have a distrobox running using podman, and I run a docker-compose file using docker, would that cause confilcts?

**Comment by castrojo** [comment]
It hasn't conflicted yet for me with distroboxes.

**Comment by bketelsen** [comment]
Same. No issues for several months.

**Comment by aadilayub** [comment]
That's great to hear! I tested it out for some of my work today and didn't run into any issues 💯

**Comment by castrojo** [comment]
This is working, only issue we've seen so far is if you had docker layered you'll get an error, the solution is to just remove the package since it's on the image now.
