### ISSUE TITLE
Invesitigate powertop auto tune

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#488]
https://wiki.archlinux.org/title/Powertop#Apply_settings

I'm currently on the vanilla -dx image (not framework) but found some significant savings after running powertop. I'm wondering if we should investigate an --auto-tune unit service unit, but there's likely other things we need to investigate so just filing this now.

**Comment by m2Giles** [comment]
Powertop can make some pretty aggressive recommendations.

For specific devices like the framework we can ship the vendors suggestions. But to generically run powertop will result in behavior that will be a bit overturned.

Additionally the new gnome-power-profiles has been merged and we already ship the patch.

**Comment by castrojo** [comment]
Yeah and future Fedora is looking at `tuned` anyway so let's skip this.
