### ISSUE TITLE
Package and ship Incus

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#489]
https://stgraber.org/2023/09/13/initial-daily-packages-for-incus/

Debian can't have all the fun. 😊 We should see if someone in fedora is already working on this.

I wonder if we can just use the existing lxc lxd spec files?

**Comment by bigpod98** [comment]
this would be cool

**Comment by bigpod98** [comment]
i would love to do this but my rpm packaging foo isnt up for that challange at least for it to be used by public

**Comment by castrojo** [comment]
Look like this is inprogress in the COPR we're using for lxc/lxd: 

https://copr.fedorainfracloud.org/coprs/ganto/lxc4/package/incus/

**Comment by bketelsen** [comment]
this makes my day
