### ISSUE TITLE
just assemble recipe points to nonexistent distrobox manifest

### ISSUE THREAD

**Issue by bpbeatty** [ublue-os/bluefin#491]
Since moving config files from `/etc` to `/usr/etc` the just assemble recipe is broken. I assume the recipe needs to be updated to point to `/usr/etc/distrobox/distrobox.ini`.

https://github.com/ublue-os/bluefin/blob/cedcfee407578a0fa91580b33cf9ed7ba6d959c6/usr/share/ublue-os/just/custom.just#L9

**Comment by bobslept** [comment]
I understand the confusion. It's the way things are working. We deploy from `/usr/etc/` but it will end up in your `/etc/`. You can just do `cat /etc/distrobox/distrobox.ini` and see the contents. 

You can read more about this process [here](https://ostreedev.github.io/ostree/deployment/#contents-of-a-deployment).

> The deployment should not have a traditional UNIX /etc; instead, it should include /usr/etc. This is the “default configuration”. When OSTree creates a deployment, it performs a 3-way merge using the old default configuration, the active system’s /etc, and the new default configuration. In the final filesystem tree for a deployment then, /etc is a regular writable directory.

**Comment by castrojo** [comment]
Is this still a problem?

**Comment by bpbeatty** [comment]
I haven't had a chance to test this but I do not believe it to be a problem. Thank you!

**Comment by bobslept** [comment]
Alright thank you, then I will close this one.
