### ISSUE TITLE
Waydroid out of the box

### ISSUE THREAD

**Issue by aadilayub** [ublue-os/bluefin#499]
### Describe the package

Could we have waydroid set up out of the box like in [Bazzite](https://github.com/ublue-os/bazzite/blob/main/Containerfile#L138)? 👀 

I haven't dug into it much, but it looks like it would just involve adding these lines to the containerfile:

```
# Install ROCM and Waydroid on non-Nvidia images
# Install distrobox-git on Nvidia images (while needed)
RUN if grep -qv "nvidia" <<< "${IMAGE_NAME}"; then \
    rpm-ostree install \
        rocm-hip \
        rocm-opencl \
        waydroid \
        lzip \
        weston \
; else \
    rpm-ostree override remove \
        distrobox && \
    rpm-ostree install \
        distrobox-git \
; fi
```

EDIT: Also, some [justfile](https://github.com/ublue-os/bazzite/blob/d76de8a3246dcc3ce7a7c687e1b69bc09e01e049/system_files/deck/shared/usr/share/ublue-os/just/custom.just#L66) additions:

```
# Quickly initialize a waydroid image
init-waydroid:
  sudo waydroid init -c 'https://ota.waydro.id/system' -v 'https://ota.waydro.id/vendor'

# Launch Waydroid configuration helper
configure-waydroid:
  #!/usr/bin/env bash
  git clone https://github.com/casualsnek/waydroid_script.git --depth 1 /tmp/waydroid_script
  python -m venv /tmp/waydroid_script/venv
  source /tmp/waydroid_script/venv/bin/activate
  sudo pip install -r /tmp/waydroid_script/requirements.txt
  sudo /tmp/waydroid_script/main.py
  deactivate
  sudo rm -rf /tmp/waydroid_script
 ```

**Comment by castrojo** [comment]
I'm not too keen on adding waydroid to bluefin, I'd rather save the builder space for something more integrated, people can add it via the pull app if they really want it. 

However if we can find a way to run it containerized or something then that'd be an easy +1.

**Comment by aadilayub** [comment]
That's fair! 

I also realized waydroid has [instructions for automatically setting up waydroid in a distrobox](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#automated-installation), thanks to an image from the Vanilla OS team. Using that makes more sense than modifying the base image.

**Comment by tulilirockz** [comment]
We could add those instructions as justfiles steps then!

**Comment by castrojo** [comment]
Great idea, cc @KyleGospo @EyeCantCU

**Comment by KyleGospo** [comment]
We definitely want to do this, the only stopper is that SELinux has to be disabled which we want to avoid. @akdev1l mentioned a solution to that a while ago, but it's gonna require some dev time to implement.

**Comment by KyleGospo** [comment]
> That's fair! 
> 
> I also realized waydroid has [instructions for automatically setting up waydroid in a distrobox](https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#automated-installation), thanks to an image from the Vanilla OS team. Using that makes more sense than modifying the base image.

This is awesome, we'll definitely do this!

**Comment by tulilirockz** [comment]
> We definitely want to do this, the only stopper is that SELinux has to be disabled which we want to avoid. @akdev1l mentioned a solution to that a while ago, but it's gonna require some dev time to implement.

It really doesn't need to be disabled tho, I've been using waydroid in my custom image for a while without changing anything about SELinux

**Comment by KyleGospo** [comment]
Gave it a first pass, if anyone wants to try it:
[Image Repo](https://github.com/ublue-os/waydroid-distrobox)
`distrobox create --root --init --unshare-netns --image ghcr.io/ublue-os/waydroid-distrobox --name waydroid`

**Comment by KyleGospo** [comment]
> > We definitely want to do this, the only stopper is that SELinux has to be disabled which we want to avoid. @akdev1l mentioned a solution to that a while ago, but it's gonna require some dev time to implement.
> 
> It really doesn't need to be disabled tho, I've been using waydroid in my custom image for a while without changing anything about SELinux

How recent? We still have to disable selinux at bazzite to get it to launch because SELinux file descriptors aren't supported in OCI images yet, unless you mean the distrobox version.

**Comment by KyleGospo** [comment]
@tulilirockz 
![image](https://github.com/ublue-os/bluefin/assets/10704358/cd1cd0cc-ad0e-42b9-adb4-ad350deed78d)
Just reproduced this to confirm, works fine only if SELinux is disabled.

**Comment by tulilirockz** [comment]
Sent you some stuff on discord :( Sadly this is quite inconsistent
