### ISSUE TITLE
Switch to COPR tailscale-status

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#508]
Kyle setup COPRs for these so that we can have them packaged and installed by default instead of being an extra just step.

**Comment by DocKDE** [comment]
You could always download the files manually at build time and chuck them into `/usr/share/gnome-shell/extensions/`. What's the advantage of a COPR?

**Comment by bobslept** [comment]
I think the idea is that you don't have to run a `just gnome-extensions` to install them. Which is currently done here
https://github.com/ublue-os/bluefin/blob/079ad2112e591c34704b37c6bc4526a190357b72/usr/share/ublue-os/just/custom.just#L115-L120

**Comment by castrojo** [comment]
Yeah that's basically it, we've got the COPR stuff mostly automated now so it's nice to lock those in.

**Comment by DocKDE** [comment]
Yes, I get that using a `just` command after installation is less preferable but you could also just download the extension and put them alongside the system extensions during the image build step and thus eliminate the need for an additional COPR, no? At least that's what I did for the tailscale-status extension.

**Comment by castrojo** [comment]
Yeah I agree, but we have the COPRs already set up and Bazzite will probably use them anyway so it made sense to just follow what they're doing.

**Comment by DocKDE** [comment]
Fair enough.

**Comment by castrojo** [comment]
Ok Kyle's got this building in the staging COPR: https://github.com/ublue-os/gnome-shell-extension-tailscale-status

Pretty sure the user will need to turn it on but at least it's in there by default.
