### ISSUE TITLE
Issues after bluefin 38-20230930 upgrade to latest 38-20231004

### ISSUE THREAD

**Issue by Cyber-Oto** [ublue-os/bluefin#564]
Greetings Team,

I have upgraded today 3 of my devices (2 desktop PC and one VM) from bluefin 38-20230930 to latest 38-20231004 and all of them had the same issue - I cannot use special keys and some GNOME shortcuts do not work.

e.g. 
- on my keyboard I have mute and volume up/down - not working after the upgrade
- some Super key shortcuts are not working, e.g. Super+L, Super+F1, ALT+Super+8, etc.
- navigation to GNOME Settings > View and Customize settings crashes with core dump each time

```
> gnome-control-center 
15:48:31.0610             GLib-GIO[ 9663]:CRITICAL: g_settings_new_with_path: assertion 'path_is_valid (path)' failed
15:48:31.0612             GLib-GIO[ 9663]:CRITICAL: g_settings_is_writable: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0612             GLib-GIO[ 9663]:CRITICAL: g_settings_is_writable: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0613             GLib-GIO[ 9663]:CRITICAL: g_settings_is_writable: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0613             GLib-GIO[ 9663]:CRITICAL: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0613                 GLib[ 9663]:CRITICAL: g_variant_get_type: assertion 'value != NULL' failed
15:48:31.0613                 GLib[ 9663]:CRITICAL: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
15:48:31.0613             GLib-GIO[ 9663]:CRITICAL: g_settings_bind_with_mapping: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0613             GLib-GIO[ 9663]:CRITICAL: g_settings_bind_with_mapping: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0613             GLib-GIO[ 9663]:CRITICAL: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
15:48:31.0614                 GLib[ 9663]:CRITICAL: g_variant_get_type: assertion 'value != NULL' failed
15:48:31.0614                 GLib[ 9663]:CRITICAL: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
15:48:31.0614                 GLib[ 9663]:CRITICAL: g_variant_get_type: assertion 'value != NULL' failed
15:48:31.0614                 GLib[ 9663]:CRITICAL: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
Segmentation fault (core dumped)
```

Looking further in the logs, I found references to `gsd-media-keys` core dumps, e.g. `Oct 04 14:53:51 ryzen5 systemd-coredump[2679]: Process 2657 (gsd-media-keys) of user 1000 dumped core.` and `Oct 04 16:35:12 ryzen5 systemd[1096]: Failed to start org.gnome.SettingsDaemon.MediaKeys.service - GNOME keyboard shortcuts service.`

Has anyone else had this problem?

**Update:**
Went to pin to specific version - tested 38-20231003, 38-20231002 and latest working for me is 38-20231001,

Went also on Fedora 39 branch - same thing as above.

**Update 2**
Same problem, for me, also with 38.20231005

**Comment by HeavenVolkoff** [comment]
Can confirm, I am on 38.20231005 and Super+L and Media keys stopped working

**Comment by Cyber-Oto** [comment]
I have also tested Bazzite GNOME – same issue as with Bluefin.

Switched to Beyond and all is OK.

**Comment by bobslept** [comment]
Thank you very much for your report. It took me some time, but I was able to reproduce the issue.

I've installed a fresh vm with `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin:38-20231001`

Indeed the shortcuts are working.

After that i have rebased with `rpm-ostree rebase ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin:38-20231005`
Shortcuts are not working anymore and I see the segfaults reported in the issue.

**Comment by bobslept** [comment]
I have made PR that should fix the issue. After its merged you should have functional keyboard shortcuts again. This issue will close automatic. Feel free to re-open this issue if it did not fix the problem for you.

Thanks again for the reports.
