### ISSUE TITLE
Recommend homebrew as the default

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#576]
Ok so the distrobox workflow isn't working out until we get a new terminal program. I'm continually seeing people struggling with containers so I'm thinking we should just declare this as our default:

- System image: solved
- Developer workflow: devcontainers as the default (either natively in vscode or devpod), distroboxes, devbox/fleek for nix, and homebrew. (No change here) 
- CLI: Let's just use homebrew

This solves a few issues:

- It lets people install packages who don't care about containers. "I just wanted to install neotopfetch!" 
- It's self contained in `/home/linuxbrew/.linuxbrew` and can easily be blown away - doesn't interfere with the system
- It has just about everything people could want in there
  - [There are lots of linux users](https://formulae.brew.sh/analytics/os-version/90d/), not even close to the number of macos users but that's more than enough.
- It's mostly github native, there's lots of automation. [Here's dysk](https://github.com/Homebrew/homebrew-core/commit/9f836e32f53594e2d6661d300036f16425359e41) being upgraded. You can observe the packages being built in github actions and being pushed to the registry. 
- The packages are just OCI blobs stored on ghcr.io, same place the OS is, making caching locally awesome and avoiding distro mirrors entirely. [Here's the neovim](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fneovim) package.  
- Precursory scanning of homebrew's analytics show massive usage, so we'd be using the same thing MacOS people have been using, so that's fine. 
- The downside is no ARM for linux binaries

@bketelsen's been prototyping a fleek backend so we could totally ship a default Brewfile with cool tools to supplement the starship setup, etc.

Also, getting Brew to work on silverblue was work started in this repo!

- https://github.com/ublue-os/bluefin/issues/252

But more seriously, I switched all my machines over a month ago and this is going to be what people coming from normal Linux will want: get the latest cool thing they read about on HN without caring about distro delays.

**Comment by alxlg** [comment]
What does a new terminal app need for the distrobox workflow?

**Comment by bigpod98** [comment]
Maybe its time i revive my old oci based package manager(never thought it could work real life but here we are)

**Comment by castrojo** [comment]
> What does a new terminal app need for the distrobox workflow?

https://github.com/orgs/ublue-os/discussions/156

**Comment by castrojo** [comment]
Thinking out loud here, I like the idea of shipping a nice set of CLI tools by default in a fleek profile with a bunch of cool stuff. And I love that we can use a `Brewfile` for this, but we're still missing a declarative way to do Flatpaks so I was thinking about a homebrew plugin:  

    brew "automake"
    cask "blah"

I wonder if we could do a thing like:

   flatpak "com.valvesoftware.Steam"

And then similarly on the CLI it's like with cask: `brew install --flatpak steam" or whatever. 

- https://github.com/Homebrew/homebrew-cask

cc @osalbahr @bketelsen

**Comment by osalbahr** [comment]
Related:
- https://github.com/Homebrew/brew/issues/15808

**Comment by osalbahr** [comment]
I don’t think Homebrew would officially support being a frontend to `flatpak`. The idea of having one file that can be generated (`brew bundle dump`) or used (`brew bundle`). Is interesting, though.

An alternative I can think of is to use a wrapper that is able to create and use a `Brewfile`-like file and delegates to either `brew` or `flatpak` accordingly (for both creating an using).

**Comment by rohanssrao** [comment]
Could I ask why Homebrew is a better default than Nix?

**Comment by castrojo** [comment]
Nix isn't a default and is already included.

**Comment by bketelsen** [comment]
I have a nice start to a fleek+brew setup at https://getfleek.dev/docs/homebrew
It needs more configuration and some good tool recommendations from the community.

**Comment by nikodunk** [comment]
I'm looking for a zero-maintenance Linux development system, and I've have been pleased with (non-immutable) Fedora Workstation for a while.

I have never however kept Atomic/Silverblue systems until today, mainly due to the mental overhead of "layering" CLI systems onto the core, or Toolbx/Distroboxing and then dealing with all the "specialities" of my Linux system vs. my coworkers' Mac systems. Desktop apps like VSCode, etc have worked great for a while, but today, I discovered on Silverblue that node, rails and psql install and run seamlessly with Homebrew, similarly easy to the DX I would have on macOS. No googling of fast-deprecated guides. I think this is the way.

Thank you everyone for all your efforts and recommendations!

**Comment by castrojo** [comment]
Ok so let's scope this:

Right now we have `just brew` and `just brew-shell` and a fleek homebrew backend is here: https://github.com/bketelsen/fleekgenbrew

We can do this in two steps I think (more ideas welcome): 

## Initial Work

We add a banner telling people about the options available and then make `just brew` and `just brew-shell` one step: https://github.com/ublue-os/bluefin/issues/609

This is relatively easy and should be east to "backport" to gts/F38 once we shake things out.

## Add Profiles via Fleek

We take the fleekbrew stuff and "import" it into this repo so it lives here. Then we default to a few profiles. Each profile lives in this repo for centralized maintenance and so that we can customize them based on what we already include in -dx. Some decent default profiles might be: vanilla/off, low, medium, high. Vanilla is Fedora defaults basically, with high being super bling. 

We'd need to normalize what's in the profiles with what we have on the image. For example we don't need git in any profile because it's on the image, etc.

**Comment by castrojo** [comment]
We'll also need a robust `just` entry for uninstalling brew.

**Comment by osalbahr** [comment]
> We'll also need a robust `just` entry for uninstalling brew.

Are there issues with the official uninstall script or `sudo rm -rf /home/linuxbrew`?

**Comment by osalbahr** [comment]
> We'll also need a robust `just` entry for uninstalling brew.

Thoughts on using [the official uninstall script](https://docs.brew.sh/FAQ#how-do-i-uninstall-homebrew) or `sudo rm -rf /home/linuxbrew`?

**Comment by castrojo** [comment]
Yeah I think just (lol) having it aliased as a just command so people don't have to go look it up will be useful!

**Comment by castrojo** [comment]
> This would likely/ideally/eventually be support for both types.

This comment in the upstream bug report leads me to believe that a flatpak plugin might be possible?

**Comment by castrojo** [comment]
Just an FYI for completeness, due to path issues we're going to recommend brew in a container and not on the host:

https://github.com/ublue-os/bluefin/issues/687
https://github.com/ublue-os/bluefin/issues/701

**Comment by castrojo** [comment]
This is mostly complete in the `bluefin-cli` container, which will be wolfi + brew, just waiting on them to merge brew in upstream wolfi:

https://github.com/ublue-os/bluefin/blob/main/toolboxes/packages.bluefin-cli

**Comment by m2Giles** [comment]
Brew is now on the host and available via bluefin-cli container. Brew has been integrated into config (https://github.com/ublue-os/config/pull/235)
