### ISSUE TITLE
Switch to COPR for Pano extension

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#579]
Splitting this off into it's own issue.

**Comment by castrojo** [comment]
Ok we're not doing this for F38/1.0, F39 only. For F38 we'll keep the `just` snippet.

**Comment by m2Giles** [comment]
We never actually built this in the copr

https://copr.fedorainfracloud.org/coprs/ublue-os/staging/packages/

**Comment by castrojo** [comment]
Yeah, I backed off a bit because Pano was having login gnome-shell crashing reports and I was hesistant to include it by default because of that. We should reinvestigate at some point because it's a great tool!

**Comment by m2Giles** [comment]
We are still not building this. Unsure if we want to integrate this or not at this point. On 45 it has some odd bugs (login/unlock auto pasting whatever is currently in your clipboard)

**Comment by castrojo** [comment]
Agreed
