### ISSUE TITLE
Investigate a btrfs subvolume for nix

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#58]
I got a tip from someone who is mounting their nix subsystem in a dedicated btrfs subvolume instead of a bind mount, we should look at the implications of this. Service unit looks like this:

```
[Unit]
Description=Nix mount
After=nix-mkdir.service
Wants=nix-mkdir.service
Before=sockets.target
After=ostree-remount.service

[Mount]
What=/dev/nvme0n1p3
Where=/nix
Options=subvol=nix
Type=btrfs

[Install]
WantedBy=local-fs.target
```

**Comment by dnkmmr69420** [comment]
I prefer the bind mount so it stays in /var/lib

**Comment by t9999clint** [comment]
this could be neat, especially with dedupe and compression enabled.

**Comment by castrojo** [comment]
Out of scope unless someone wants to work on this.
