### ISSUE TITLE
Investigate tailscale extension

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#592]
https://github.com/joaophi/tailscale-gnome-qs

This one matches GNOMEs UX better, but appears to be missing the exit node functionality. We should keep an eye on it.

**Comment by KyleGospo** [comment]
[gnome-shell-extension-tailscale-gnome-qs](https://copr.fedorainfracloud.org/coprs/ublue-os/staging/package/gnome-shell-extension-tailscale-gnome-qs/)

**Comment by castrojo** [comment]
I was wrong, exit node functionality is included (though the list scrolls off the screen). I think we should switch to this. Working on it.

**Comment by bobslept** [comment]
In discord people seem to have problems with tailscale exension after the merge.
