### ISSUE TITLE
Ship a topical terminal banner 

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#609]
Right now by default when you open a terminal by default this script runs:

- https://github.com/containers/toolbox/blob/main/profile.d/toolbox.sh

It'd be nice if we could instead display something that makes sense for Bluefin, point out where to file bugs, that sort of thing. I think we should just `glow /somedir/blah.md` as a default or perhaps investigate dynamic motd or something.

**Comment by rothgar** [comment]
Where does this banner show up? I've never seen it when opening blackbox or entering an ubuntu distrobox container.

**Comment by castrojo** [comment]
It shows up on a clean install on the host terminal. I'm not sure how it runs. However I found the console-login set of packages, which appears to be the tools used for CoreOS:

https://github.com/coreos/console-login-helper-messages/blob/main/doc/manual.md

This looks like it might be the way to generate a dynamic motd.

**Comment by castrojo** [comment]
Ok the colors need adjusting but this could work:

![image](https://github.com/ublue-os/bluefin/assets/1264109/e3916182-8ae2-42e0-97c5-a9f9d6add14c)

**Comment by castrojo** [comment]
Alright here go. The glow dracula.json and some updates to the starship config:

![image](https://github.com/ublue-os/bluefin/assets/1264109/660e22b5-e874-46ff-b4c0-d871cd69e92e)

**Comment by castrojo** [comment]
![image](https://github.com/ublue-os/bluefin/assets/1264109/f25cd785-bab4-4a4b-8cb6-f1910864d556)

This is from a discussion in discord which I failed to capture, moving here:

- The first command will just set up the distroboxes (we'll have a common generic name)
- `just banner` should toggle it on and off (bluefin-banner doesn't make sense, ignore that part). Once a user turns it off we should never bother them again.  
- We spit out the image name, major version, kernel, and date. 

Then for tips I think what we should do is keep a `tips.txt` or something in the repo. Then we add some common FAQs in there and then just randomly pick one during the build process to put in the markdown file. And then if we have major announcements or something we can hardcode an important message if we need to. 

For implementation we were thinking just tack the glow command at the end of the user's /etc/skel.d/basrc so it's there during user creation.
