### ISSUE TITLE
Temporarily publish a `gts` tag for F38

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#616]
Ok so F39 is pushed to 7 November - we were hoping to use the offline ISO that defaults to `gts`.

We need to launch everything (not just the ISO, there's associated website, docs stuff) before 4 November since that's Kubecon.

- Shipping the ISO with :latest as F39 is the least desirable
- Shipping a `:38` is also not desirable because people will have to remember to rebase. 
- Ideally some kind of temporary tag solution so we can generate an ISO with `gts` that points to `38`, and then when F39 comes out we transparently set it up "normal".

**Comment by castrojo** [comment]
Oh also, would we need to touch any of the other images? (hoping for a no!)

**Comment by bobslept** [comment]
- https://github.com/ublue-os/bluefin/pull/617
 
![image](https://github.com/ublue-os/bluefin/assets/38557801/95f60715-5639-44fc-9cba-7899cb5f9a7d)
