### ISSUE TITLE
Configure distrobox to mount /home/linuxbrew/.linuxbrew

### ISSUE THREAD

**Issue by rothgar** [ublue-os/bluefin#623]
### Describe the package

Should be mounted by default so `brew` and brew installed applications work inside distrobox.

```
volume=/home/linuxbrew/.linuxbrew:/home/linuxbrew/.linuxbrew
```

### Image

All Images

**Comment by m2Giles** [comment]
We are currently recommending that brew be installed inside a container.

If you want to use brew on the host and have it accessible inside a distrobox container: you can use the --volume flag with distrobox create.

Additionally if you want to use distrobox assemble, the assemble file has the volume key.

Use your standard /source:/target for podman/docker.

**Comment by m2Giles** [comment]
If you are using bluefin-cli container, it will now store the /home/linuxbrew inside of $XDG_DATA_HOME/bluefin-cli.

This can be volume mounted in another distrobox by using the --volume flag.

**Comment by m2Giles** [comment]
Distrobox has the entire host under /run/host. Volume flag symlinks it into place. You can add Homebrew to $PATH inside of distrobox to give you access.
