### ISSUE TITLE
Investigating evdi support

### ISSUE THREAD

**Issue by aaronhuggins** [ublue-os/bluefin#626]
### Describe the package

I'd like to request evdi to be included OOTB because my work hardware depends on DisplayLink docks. I've been experimenting with getting evdi working on Fedora *in general*, and it seems to work fine on Bazzite.

What I'm noticing is that evdi is supported in Bluefin for Fedora 38 and below, but is excluded from images based on Fedora 39 and above. I wasn't able to understand from the commits why exactly.

Could you share the reason? I'd be interested in helping to get evdi consistently included, if it makes sense.

### Image

All Images

**Comment by KyleGospo** [comment]
We have this working in Bazzite, but F39 support is pending. @castrojo let me know if you want it PR'd here.

**Comment by castrojo** [comment]
Let's do it!

**Comment by KyleGospo** [comment]
Still waiting on support for it from Negativo17, hopefully soon given the imminent launch of F39.

**Comment by KyleGospo** [comment]
https://github.com/negativo17/libevdi/issues/1

**Comment by KyleGospo** [comment]
Restored in F39, be sure to watch the builds for the image you're using.
