### ISSUE TITLE
Add Podman Desktop flatpak

### ISSUE THREAD

**Issue by marrusl** [ublue-os/bluefin#635]
### Describe the package

I'd like to request the `podman-desktop` as a checked-on-by-default flatpak in bluefin-dx.

Podman Desktop is a graphical tool that seamlessly manages container images, containers, pods, and container storage across single container hosts and Kubernetes clusters. While Podman is in the name, it can also work with docker, kind, and kubernetes. 

It seems on theme with the mission of -dx, imho.

https://podman-desktop.io/ 
https://github.com/containers/podman-desktop

### Image

All Images

**Comment by castrojo** [comment]
Heya Mark, I'd love to add an entire section of podman tools, I'll PR in the desktop, if you have any other goodies please file them!

**Comment by slemeur** [comment]
Thank you @castrojo and @marrusl
