### ISSUE TITLE
Commit Mono overloads the GUI selection screen

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#639]
I like the font but it has a ton of variations. This feels a bit overboard to me lol: 

![image](https://github.com/ublue-os/bluefin/assets/1264109/11f17f05-1300-4085-91d1-42453c4eca8d)

Maybe we can trim down the list to be more manageable?

**Comment by hisergiorojas** [comment]
How many font sizes should we manage?

**Comment by hisergiorojas** [comment]
How about 4 font variations?

1. 400 italic
2. 400 regular
3. 700 italic
4. 700 regular

**Comment by castrojo** [comment]
Thanks for this!
