### ISSUE TITLE
A Bluefin build with Nvidia 470 drivers or guidance please

### ISSUE THREAD

**Issue by zooberi** [ublue-os/bluefin#648]
### Describe the package

Hi I'd like to request that a build with Nvidia 470 drivers be made available please or at least some guidance without needing to fork the project please like using rpm-ostree to include nvidia 470 which has not been successful for me.

### Image

All Images

**Comment by bobslept** [comment]
Duplicate of #394

**Comment by castrojo** [comment]
If someone else in @ublue-os/member @ublue-os/approver has any insight on how we could do this it'd be appreciated!

**Comment by m2Giles** [comment]
Nvidia 470 is no longer being provided by RPMFusion for kernel 6.8.
