### ISSUE TITLE
Include `MOZ_ENABLE_WAYLAND=1` override for Firefox to enable wayland support

### ISSUE THREAD

**Issue by Georift** [ublue-os/bluefin#653]
I noticed on a fresh install of Bluefin Firefox was a little fuzzy in it's rendering. Which turned out to be due to [Wayland support still being opt-in in firefox](https://wiki.archlinux.org/title/Firefox#Wayland).

This can be fixed by running:
```
sudo flatpak override --env MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox
```

Would this be something we'd have appetite in including by default? I feel like this would be a safe addition to any of the Fedora images running Gnome (as I believe they're all wayland by default?).

[tentative support :laughing:](https://hachyderm.io/@jorge/111404027223137186)

**Comment by Georift** [comment]
I'm not super familiar with how the build process is structured, but it seems like after the `rpm-ostree install`'s in build.sh we could slot in the flatpak override?

https://github.com/ublue-os/bluefin/blob/main/build.sh#L53

I wonder if it's then still possible for users to remove this override after install.

**Comment by tunix** [comment]
Looks like current way of doing it is to add such things in an appropriate justfile.

**Comment by Georift** [comment]
Ah yep I do remember seeing a firefox nvidia just file task somewhere. I do wonder though if something like `just fix-firefox-scaling` should just be always applied in this case.

I would love to see it be applied automatically, without me having to hunt down just command docs when I noticed Firefox looking fuzzy.

**Comment by castrojo** [comment]
This will be on by default soon: https://hg.mozilla.org/mozilla-central/rev/5ea5f3e31d58

**Comment by Georift** [comment]
> Let wayland ride the trains to release

🚂 🦊 

Two days ago, nice spot! Probably safe to ignore this fix here.
