### ISSUE TITLE
Add monaspace font

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#660]
Let's add the variable ones to -dx so it's only 4 files: 

https://github.com/githubnext/monaspace

**Comment by rothgar** [comment]
I just installed this font on my system after it was announced but haven't figured out how to make it my blackbox font. It doesn't show up in the font picker in preferences. It shows up fine in gnome tweaks fonts.

**Comment by stoeps13** [comment]
There is an issue https://github.com/githubnext/monaspace/issues/15#issuecomment-1806775814 about Monaspaced fonts that `pango_font_family_is_monospace()` needs to return `true` to show up in the terminal preference font list.

Gnome fonts does show the fonts after copy them to `/usr/share/fonts` and running `fc-cache -f`
