### ISSUE TITLE
Include hplip

### ISSUE THREAD

**Issue by rothgar** [ublue-os/bluefin#677]
### Describe the package

hplip requires write access to some directories that are read only. They don't provide an rpm installer though so I don't think we can use rpm os-tree.

https://developers.hp.com/hp-linux-imaging-and-printing/gethplip

Is there a method to install packages like this? We can extract the drivers, but I wanted to ask if this is even something we should consider.

### Image

All Images

**Comment by castrojo** [comment]
Not sure if this will pull in `libsane-hpaio` but we can pull that in if we need it.
