### ISSUE TITLE
Set the keyboard to colemak sets it to US

### ISSUE THREAD

**Issue by muhdsalm** [ublue-os/bluefin#680]
### Describe the bug

When I told it to use the English (Colemak) keyboard in the installer (anaconda), it instead installed the English (US) keyboard. Now my muscle memory is useless!

If it's just variants, it's an annoyance and can easily be changed on the desktop, but it cannot be changed in the login screen (GDM) due to the immutable nature of the distro (I think). If it changes all keyboard to English US, then it can be a real issue as, for example, a password can be set in a different language only for the keyboard to be English, making it impossible to login.

### What did you expect to happen?

I expected setting the keyboard to Colemak to give me Colemak, but instead it gave me English US!

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-unverified-image:oci:/var/ublue-os/image
                   Digest: sha256:e36a0548e12a9f22560cd1c1234e279c98d6af6c3088b798b4959b1c8e3c191f
                  Version: 38.20231027.0 (2023-11-26T10:25:13Z)

  ostree-unverified-image:oci:/var/ublue-os/image
                   Digest: sha256:e36a0548e12a9f22560cd1c1234e279c98d6af6c3088b798b4959b1c8e3c191f
                  Version: 38.20231027.0 (2023-11-26T10:25:13Z)
```

### Extra information or context

The output of rpm-ostree status is, imo, irrelevant.

**Comment by bobslept** [comment]
Yes our installer doesn't seem to like it. The only way I got it working is using the official silverblue to install, and rebase afterwards to bluefin from that installation. 

I've used the silverblue iso found here https://fedoraproject.org/silverblue/download 

After the install you can rebase using a terminal with the following command:
`rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/bluefin:39`

Sorry for the inconvenience.

**Comment by muhdsalm** [comment]
I'm just testing in a VM, so it's not an inconvenience to me. It's just I wanted to inform you that this bug exists.
