### ISSUE TITLE
Dash to Dock's intelligent autohide is turned off

### ISSUE THREAD

**Issue by muhdsalm** [ublue-os/bluefin#681]
### Describe the bug

On a fresh install, the Dash to Dock's intelligent autohide is turned off.

### What did you expect to happen?

I expected Dash to Dock's intelligent autohide to be turned on

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-unverified-image:oci:/var/ublue-os/image
                   Digest: sha256:e36a0548e12a9f22560cd1c1234e279c98d6af6c3088b798b4959b1c8e3c191f
                  Version: 38.20231027.0 (2023-11-26T10:25:13Z)

  ostree-unverified-image:oci:/var/ublue-os/image
                   Digest: sha256:e36a0548e12a9f22560cd1c1234e279c98d6af6c3088b798b4959b1c8e3c191f
                  Version: 38.20231027.0 (2023-11-26T10:25:13Z)
```

### Extra information or context

It's possible that this is just the default expected behavior, but in that case it should be easy to turn it on, as opposed to right clicking the grid icon then going to Dash to Dock settings then turning it on. The setting is hard to find and if I didn't know it was there, I probably would have had no idea, especially as there's no option to do this in the settings app.

**Comment by castrojo** [comment]
Yeah that is the default, I could document it in the docs though if that helps? 

Also not related, I see you're still on the `/var/ublue-os/image` - you should do a `just update` to get on an updated image (or you could just wait until the automatic update kicks in, just thought I'd let you know!)
