### ISSUE TITLE
Adding devbox global init to `.bashrc` clobbers `$PATH` 

### ISSUE THREAD

**Issue by worldofgeese** [ublue-os/bluefin#693]
### Describe the bug

Bluefin comes with a convenient `just` command to install `devbox global`. On install, `devbox global` has a user add `eval "$(devbox global shellenv)"` to their `.bashrc`, which clobbers my `$PATH`.

Here's a healthy `$PATH`:
```bash
/home/worldofgeese/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/worldofgeese/.local/bin:/home/worldofgeese/bin:/home/worldofgeese/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

After adding  `eval "$(devbox global shellenv)"` to my `.bashrc`: 
```bash
/home/worldofgeese/.local/bin:/home/worldofgeese/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

These changes take effect on a logout/login. I can eval "$(devbox global shellenv)" in any given terminal window and get an augmented `$PATH` but if I logout/login, my `$PATH` is clobbered.

### What did you expect to happen?

`devbox global` should add itself to a user's `$PATH` without clobbering a user's existing `$PATH`.

### Output of `rpm-ostree status`

```shell
My Bluefin is installed on a Framework Storage Card that has suffered from data loss :-(
```

### Extra information or context

Another user on the Universal Blue Discord ran into [a version of this issue](https://discord.com/channels/1072614816579063828/1087140903031943178/1174009826662170765).

@Lagoja over at Devbox tested this and it looks like the `PATH` issues which I and the mentioned user experienced may be a result of how Bluefin constructs a `PATH` in `/etc/bashrc`?

Quote from @Lagoja:

> So I tested the same lines in my /etc/zshrc on MacOS, and I'm seeing the Nix related variables get set. I even added a custom variable to the /etc/zshrc and it showed up when I spawned a new shell. 
> 
> I think this might be bluefin specific? One bit that looks a little suspicious is that pathmunge function -- I'm not sure if that's doing anything to the PATH that would throw off Devbox?

[Link to the conversation on Discord](https://discord.com/channels/903306922852245526/1174489601105211453/1174885083266695179).

**Comment by worldofgeese** [comment]
Mentioning @bketelsen because I think he's been the prime mover on the Devbox and Nix in Bluefin front.

**Comment by worldofgeese** [comment]
@bketelsen just checking in if you've had a chance to reproduce 🙂

**Comment by m2Giles** [comment]
devbox was removed due to issues with SELinux.
