### ISSUE TITLE
`just gnome-extensions` fails after switching to `zsh` shell

### ISSUE THREAD

**Issue by billyogat** [ublue-os/bluefin#697]
### Describe the bug

`just gnome-extensions` fails after switching to `zsh` shell.

---

```shell
~% just zsh
```
Restart the shell and go through the zsh setup (anything will do).
```shell
~% just gnome-extensions 
pip install --upgrade gnome-extensions-cli
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gnome-extensions-cli in ./.local/lib/python3.12/site-packages (0.9.5)
Requirement already satisfied: colorama<0.5.0,>=0.4.5 in ./.local/lib/python3.12/site-packages (from gnome-extensions-cli) (0.4.6)
Requirement already satisfied: more-itertools<10.0.0,>=9.0.0 in ./.local/lib/python3.12/site-packages (from gnome-extensions-cli) (9.1.0)
Requirement already satisfied: packaging<24.0,>=23.0 in /usr/lib/python3.12/site-packages (from gnome-extensions-cli) (23.1)
Requirement already satisfied: pydantic<2.0.0,>=1.10.4 in ./.local/lib/python3.12/site-packages (from gnome-extensions-cli) (1.10.13)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/lib/python3.12/site-packages (from gnome-extensions-cli) (2.28.2)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/lib/python3.12/site-packages (from pydantic<2.0.0,>=1.10.4->gnome-extensions-cli) (4.8.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->gnome-extensions-cli) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->gnome-extensions-cli) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.28.1->gnome-extensions-cli) (1.26.18)
gext install tailscale-status@maxgallup.github.com
sh: line 1: gext: command not found
```

### What did you expect to happen?

I expected the extensions to install.

### Output of `rpm-ostree status`

```shell
~% ostree admin status
* fedora 1f5f55a2d5dbcc93af64cd7bd98957f6c2304f1ac5165c28cc7b950508ba591b.0
    origin: <unknown origin type>
  fedora b05c80b401ac5fa80f7fa7fdc490f0b6bbbf0c56e2e26399a12340bbb9fd8063.0 (rollback)
    Pinned: yes
    origin: <unknown origin type>
  fedora 5c8f532dc2c0b82f6653ffba3d1f5967d267fae170b160d4f60a8f0bd5fa7f08.0
    Version: 39.20231128.0
    Pinned: yes
    origin refspec: fedora:fedora/39/x86_64/silverblue
    GPG: Signature made Mon 27 Nov 2023 07:51:47 PM EST using RSA key ID 75CF5AC418B8E74C
    GPG: Good signature from "Fedora <fedora-39-primary@fedoraproject.org>"
```

### Extra information or context

It seems that the `bash` setup is doing some `$PATH` setup that doesn't get applied to the `zsh` shell after switching.

`PATH` when in `zsh` 
```shell
~% echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

`.bashrc` `PATH` configuration.
```shell
~% grep -A1 PATH .bashrc
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
```
---
I can set this `PATH` config myself, but I would expect this to be supplied and working on a new install with minimal modifications.

I'd be happy to work on this issue and supply a sane set of `zsh` defaults if that is useful to the project.

**Comment by castrojo** [comment]
> I'd be happy to work on this issue and supply a sane set of zsh defaults if that is useful to the project.

This would be amazing! Feel free to dive in and fix it up!

**Comment by m2Giles** [comment]
By default from fedora, zsh is setting it's path in `~/.zprofile`. Meanwhile, bash will set it in `~/.bashrc`. So if we switch over to `zsh` in a `ujust` command we need to use `zsh --login` for that first shell.

**Comment by MuchHustle** [comment]
Any progress on this? I keep getting this repeating error lately but I don't know what it means as I don't know what the "universal variable file" is...

> error: Unable to open universal variable file '/': Permission denied
> error: Unable to open universal variable file '/': Permission denied
> error: Unable to open universal variable file '/': Permission denied
Any suggestions?
