### ISSUE TITLE
brew based bluefin-cli toolbox

### ISSUE THREAD

**Issue by bobslept** [ublue-os/bluefin#701]
With moving brew into a distrobox we encountered some issues. For example when you run a `just distrobox-brew` you have a working brew envorinment, but when it is removed you have to install all your packages again. 

Because of the default brew distrobox is lacking dependencies for distrobox it would already be a good idea to create a fresh one with the dependencies already installed for faster startup time. This opens up the possibilities to add some nice things that will help us overcome the issue of setting up your packages again when you re-create the brew-box from scratch.

I've did some quick testing and it seems to be working pretty good. Just a quick log of what I've done while testing.

We can create a box like so:
`distrobox-create --nvidia --image ghcr.io/homebrew/brew:latest -n brew -Y -a "--env BREW_PKGS=.brew_pkgs"`

Now when you enter the box `distrobox enter brew` we have the `$BREW_PKGS` to use. So inside the box I've added:
```
~ ❯ cat /etc/profile.d/brew_pkgs.sh 
if [ ! -f /home/linuxbrew/.firstrun ]; then
  echo "Touching firstrun"
  touch /home/linuxbrew/.firstrun
  xargs brew install < $HOME/$BREW_PKGS
else
  echo "already setup"
fi
```

In my home directory I have created a `.brew_pkgs` file with some packages:
```
~ ❯ cat ~/.brew_pkgs
dysk
jq
yq
neovim
neofetch
btop
cheat
```

Now when you enter the box again it will install the packages listed in `.brew_pkgs`. Create `.firstrun` file and will not do it again the second time. If we move this setup into our own `bluefin-cli` box we should be able to always have our packages back installed if it is a fresh box.

A `just bluefin-cli` can verify if `.brew_pkgs` already exists or write the packages we see as good default into there. This all is just a quick and dirty test but I think this proves that we can use this way to reach our end result.

cc @castrojo @bketelsen

**Comment by bketelsen** [comment]
this is really solid, I like it

**Comment by bketelsen** [comment]
let's add this to the bluefin-cli @castrojo just PRd

**Comment by bobslept** [comment]
> let's add this to the bluefin-cli @castrojo just PRd

Great idea! Some kind of magic. 
- https://github.com/ublue-os/bluefin/pull/700
- [bluefin-cli](https://github.com/ublue-os/bluefin/pkgs/container/bluefin-cli)

**Comment by castrojo** [comment]
Baller! Should we reuse the Brewfile for this?

**Comment by castrojo** [comment]
Thanks to the wolfi folks and @m2Giles we now have a working brew container!

    distrobox create -i ghcr.io/ublue-os/bluefin-cli

And then brew install to your heart's content! We still need to bling it up but it's functional, I'll work on updating the docs tonite.
