### ISSUE TITLE
Text bugs out in GNOME app view

### ISSUE THREAD

**Issue by Casserole97** [ublue-os/bluefin#718]
### Describe the bug

After opening the app view, scrolling to the next page, and then scrolling back, this happens to random app names:

![image](https://github.com/ublue-os/bluefin/assets/54863165/8108dada-dd61-4209-bff3-999d0a55af64)

It repeats every time I scroll between the pages, but only happens on the first page.

### What did you expect to happen?

No glitched out text

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:3397c1fddc516f876058983c07b7a8c3e199ad73dd19276ea2bf801a4a9b82e3
                  Version: 39.20231205.0 (2023-12-05T17:51:42Z)
          LayeredPackages: iosevka-fonts

  ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:f5350d6d6955699cc3382b366426b5da0d6fa1d5da0596a6205b31b66f07c28c
                  Version: 39.20231205.0 (2023-12-05T16:51:28Z)
          LayeredPackages: iosevka-fonts
```

### Extra information or context

Hovering over apps causes part of the glitched text to disappear.

The issue persists even with extensions disabled.

**Comment by m2Giles** [comment]
Are you still experiencing this issue? If so, what hardware and session are you using?

**Comment by Casserole97** [comment]
@m2Giles Yes, still experiencing it, here are the system details from gnome settings:

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad X280
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-8550U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (KBL GT2)
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            N20ET66W (1.51 )
- **OS Name:**                                     Fedora Linux 39.20240116.0 (Bluefin)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.3
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.9-200.fc39.x86_64

**Comment by m2Giles** [comment]
I've been unable to replicate this bug on either AMD (780m, 7900 xtx) or Intel Graphics (UHD 630, 750) inside of gnome. I may have an 7th gen intel device somewhere in the house to try and replicate but I'm unsure if anything we are setting besides fonts could be the cause of this (we do have the gnome-vrr patchset).

Have you changed the system fonts in gnome tweaks?

**Comment by Casserole97** [comment]
Haven't touched the fonts in gnome tweaks, and gnome-vrr is enabled.
![image](https://github.com/ublue-os/bluefin/assets/54863165/eef09278-f65b-4d83-a0c4-95571aeac1f4)
