### ISSUE TITLE
/etc/profile.d/ublue-os-just.sh pollution on .justfile

### ISSUE THREAD

**Issue by zebh** [ublue-os/bluefin#719]
### Describe the bug

Currently `/etc/profile.d/ublue-os-just.sh` adds `!include /usr/share/ublue-os/justfile` on every login.

### What did you expect to happen?

I replaced the `~/.justfile` with my own, ran `just` and saw the full list of ublue specific just-recipies. I expected this to be a `/etc/skel` style file where I had control of it.

Is it possible to change the ublue just command to `alias ujust=just --unstable -f /etc/ujustfile` or something similar? 

Or, to keep the current default; add an opt-out so that I can have control over my own justfile in my homefolder, and have the system respect that?

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: check; rpm-ostreed-automatic.timer: last run 18h ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:44987723c941cbd884b219cae7b8ed8b4dac27be509e309b3f67eb88dc78180b
                  Version: 39.20231205.0 (2023-12-05T19:04:10Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:eaa91bea8e16b280c22aceecdb1ce1a803fad9aac1fca9391cf8f51ad37d1279
                  Version: 39.20231204.0 (2023-12-05T00:35:57Z)
```

**Comment by castrojo** [comment]
Would deleting `/etc/profile.d/ublue-os-just.sh` do the trick?

**Comment by zebh** [comment]
I'm guessing it is trying to solve a problem, so that seems like a bit of a nuclear option?

The first 9 lines seem reasonable to me:
```
alias just="just --unstable"

# Add uBlue's justfiles to users with home directories which lack a justfile.

if [ ! -z "$HOME" ] && [ -d "$HOME" ] && [ ! -f "${HOME}/.justfile" ]; then
  cat > "${HOME}/.justfile" << EOF
!include /usr/share/ublue-os/justfile
EOF
fi
```

It's line 11-20 that is a bit of an issue:
```
if [ -f "${HOME}/.justfile" ]; then
  if ! grep -Fxq '!include /usr/share/ublue-os/justfile' "${HOME}/.justfile"; then
    # Remove any lines we may have added previously.
    sed -i '/!include \/usr\/share\/ublue-os\/just\/.*.just/d' "${HOME}/.justfile"

    # Point to the new main justfile, place it as the first line
    echo '# You can add your own commands here! For documentation, see: https://ublue.it/guide/just/' | tee -a "${HOME}/.justfile"
    echo '!include /usr/share/ublue-os/justfile' | tee -a "${HOME}/.justfile"
  fi
fi
```

**Comment by bobslept** [comment]
If I remember correct those lines 11-20 are from when we restructured our just files. So it would remove the old ones and add the new one. In a way that the user would keep their own commands if they where there. So it checks if the new `!include /usr/share/ublue-os/justfile` is found, if it is not we expect we are on a "old" version and it gets added.

So that is what we are trying to solve in that part. If you want to comment that part out in the script on your system, or like @castrojo suggested completely remove the script.  You will not get the ublue just commands anymore. Those are pointed via `!include /usr/share/ublue-os/justfile`.

**Comment by zebh** [comment]
> So that is what we are trying to solve in that part. If you want to comment that part out in the script on your system, or like @castrojo suggested completely remove the script. You will not get the ublue just commands anymore. Those are pointed via `!include /usr/share/ublue-os/justfile`.

Oh, fair enough. I misunderstood @castrojo then, I though he meant remove it from the package... Yeah, I can certainly remove that file, will that keep it away or will it be replaced on an update? RPM suggests it's part of a package:

```
$ rpm -qf /etc/profile.d/ublue-os-just.sh
ublue-os-just-0.9-1.fc39.noarch
```
Otherwise I can probably `chattr +i` a dummy file.

**Comment by bobslept** [comment]
> Oh, fair enough. I misunderstood @castrojo then, I though he meant remove it from the package... Yeah, I can certainly remove that file, will that keep it away or will it be replaced on an update? 

No it won't be restored after an upgrade. If you ever feel the need of restoring the file you can find a copy in `/usr/etc/profile.d/ublue-os-just.sh` on your system.

**Comment by zebh** [comment]
> > Oh, fair enough. I misunderstood @castrojo then, I though he meant remove it from the package... Yeah, I can certainly remove that file, will that keep it away or will it be replaced on an update?
> 
> No it won't be restored after an update. If you ever feel the need of restoring the file you can find a copy in `/usr/etc/profile.d/ublue-os-just.sh` on your system.

Oh, okay. 

Then my issue is resolved. I, wrongly, assumed it would be recreated on updates like in other distributions.
