### ISSUE TITLE
Add support for kcli

### ISSUE THREAD

**Issue by jmgilman** [ublue-os/bluefin#720]
### Describe the package

The [kcli](https://github.com/karmab/kcli) tool is an extremely versatile tool for working with virtual machines locally. It supports starting them from the CLI, using configuration files, layering profiles together, creating entire Kubernetes clusters, and more. It's an amazing resource for local development on VMs, and I've found the Kubernetes support is superior to things like KinD due to the ability to support much more complex setups. This seems to be in the CNCF spirit of this project :)

Luckily, `bluefin-dx` includes all of the pre-requisites already. If I understand things correctly, it should be as simple as [adding the package](https://kcli.readthedocs.io/en/latest/#package-install-method).

### Image

`bluefin-dx`

**Comment by castrojo** [comment]
This seems neat, I don't have time to get to this due to travel, so whoever wants this one can snag it!
