### ISSUE TITLE
Issue: make: binary command not found

### ISSUE THREAD

**Issue by Thijzer** [ublue-os/bluefin#729]
### Describe the bug

I can't seem to find the make binary on my system since version 39.
I just upgraded 2 days ago from 38 to 39 so is it possible that the make binary was excluded from the build?

```
❯ which make
/usr/bin/which: no make in (/var/home/XXX/.local/bin:/var/home/XXX/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/home/XXX/.local/share/JetBrains/Toolbox/scripts)
```

### What did you expect to happen?

In dx:38 I was able to run the make command inside Jetbrains PHPstorm, just like in Fedora workstation.

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1 day 5h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:39
                   Digest: sha256:e3a2e59b30ea326e2228a4b484483a666c96c52b9401405f6994cedbe63aa971
                  Version: 39.20231213.0 (2023-12-13T16:51:18Z)
                     Diff: 5 upgraded
          LayeredPackages: langpacks-nl

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:39
                   Digest: sha256:34f14cf150e00509fe6616b9212384c94c26bb1c382a751da97c4a8d4eb3d4ce
                  Version: 39.20231212.0 (2023-12-12T16:53:22Z)
          LayeredPackages: langpacks-nl

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:38
                   Digest: sha256:6b912cad12296d8d0073dd9f03649ac7fa04c32bf72e0e33d8a08dcba59e8319
                  Version: 38.20231211.0 (2023-12-11T16:52:47Z)
          LayeredPackages: langpacks-nl
```

**Comment by castrojo** [comment]
Yeah we had it on the image for brew dependencies but we're moving all that into distroboxes now so we won't be having development tools on the image itself. Last I checked in jetbrains you could pull in the dependencies you needed right from the toolbox tool itself but I need to go dig to double check.

**Comment by castrojo** [comment]
Adding make back doesn't pull in a bunch of extra stuff so we could add this back if we feel we need it on the image.

**Comment by castrojo** [comment]
Alright it'll be back when you update next!
