### ISSUE TITLE
Stick dev tools in a gnome folder

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#735]
https://developer-old.gnome.org/AppFolders/

Let's organize all the dx tools with .desktop files into a "Development" folder so we're not overloading the main menu. It'll also be a handy way for new users to see what goodies come with it vs. a stock image.

**Comment by jpmcb** [comment]
I'd love to snag this! Looks like it'd be a good introduction to doing dev on bluefin!

**Comment by castrojo** [comment]
Initial work here: https://github.com/ublue-os/bluefin/blob/b0703f95cb52c825aa0504b9bf497a57010ced62/usr/etc/dconf/db/local.d/01-ublue#L6
