### ISSUE TITLE
Lost keyboard shortcut to open host terminal

### ISSUE THREAD

**Issue by bobslept** [ublue-os/bluefin#743]
I just noticed on a system that the keyboard shortcut <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>t</kbd> no longer opens a terminal. Earlier it would have opened `gnome-terminal` which is now replaced in favor of `prompt`.  

The code below is removed from the code base. Can we bring that shortcut back so that it launches a terminal again, in this case probably `prompt`? 

https://github.com/ublue-os/bluefin/blob/94bb013a241e40c74d381100dc3b166c2e033c32/usr/etc/dconf/db/local.d/01-ublue#L55-L58

If its intended we can close this, otherwise its just as a reminder so that we can add it back in later

**Comment by KyleGospo** [comment]
The shortcut should now be offered by the new nautilus extension, looking into it
