### ISSUE TITLE
Suggestion: Automount hugepages with a pagesize of 1GB if the user has set the appropriate karg for use when running specialized VMs

### ISSUE THREAD

**Issue by HikariKnight** [ublue-os/bluefin#750]
By default systemd will mount hugepages if the user has reserved a number of them in memory.
However the default hugepages are 2MB in size, in some niche situations you would want to have a page size of 1GB (you can not use 2MB and 1GB page size at the same time)

This is sometimes used if you need a lower latency VM (this is often used for Gaming VMs but i am sure there are other VM workloads that will benefit too from hugepages), however this has to be configured for each individual VM because hugepages are reserved memory space.

[Bazzite already has a systemd mount unit](https://github.com/ublue-os/bazzite/pull/425) that triggers only if the user has set the karg `hugepagesz=1G` which tells the kernel to use a hugepages page size of 1GB and will then proceed to mount the 1GB hugepages whereas the default hugepages mount unit will ignore it.
If you were to use hugepages and guarantee they all get reserved, you would reserve them using a karg anyway, otherwise reserving all the pages might fail if the memory space you are trying to reserve has already been used for something else.

The original bazzite pull request linked has more information about it and the systemd mount unit file has links to the kernel documentation for hugepages.

This is purely a suggestion since bluefin-dx exists which comes with qemu, virt-manager, etc so i figured it might be a nice QOL for that niche usecase and skip the step of manually mounting the hugepages table each boot if you have that memory reserved anyway with a karg.

**Comment by m2Giles** [comment]
I don't see any issues with this. Would be helpful for VFIO users though we don't have the same convenience scripts.

**Comment by HikariKnight** [comment]
> I don't see any issues with this. Would be helpful for VFIO users though we don't have the same convenience scripts.

once i am done with the just reorg for both bluefin and bazzite (after config) i will look into porting the bazzite-hardware-setup to bluefin so that bluefin can take advantage of the vfio convenience scripts too (and the ability to do initramfs updates that do not clash with user set initramfs args).
Might look at making it into its own layer that people can just pull if we can make it generic enough?, but somehow i doubt that since the one in bazzite has checks for special hardware like ally, deck, legion go and others.

**Comment by m2Giles** [comment]
We don't have the need for the same hardware checks. I hesitate to make a ujust command for it simply because it can go quite wrong if people do not read. But I like the implementation of having 1G huge pages support which would be good for other VM workloads.

**Comment by m2Giles** [comment]
A way to have initramfs managed would be nice.

We don't have any specific need right now but it would be handy if we decide to have a ujust command for tpm2 unlock.
