### ISSUE TITLE
Add the default user to the docker group

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#771]
This is the last bit for finishing the vscode part of -dx. To summarize other discussions:

@p5 would like to make sure we only include users in the wheel group in here, which makes sense to me.
@jeefy was working on vscode but we wanted this as a follow on PR. 

Though if someone wants to claim this and finish it, by all means self assign!

![image](https://github.com/ublue-os/bluefin/assets/1264109/ff0c2822-b685-4239-bb1c-b58b701078c6)

**Comment by m2Giles** [comment]
This should be completed with #775
