### ISSUE TITLE
Add m2Giles as a maintainer

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#777]
@m2Giles has been fixing lots of things, I'd like to nominate for write in the bluefin repo.

**Comment by p5** [comment]
+1

**Comment by EyeCantCU** [comment]
They've made several valuable contributions. +1!

**Comment by KyleGospo** [comment]
+1

**Comment by bketelsen** [comment]
+1

**Comment by castrojo** [comment]
ALRIGHT, https://universal-blue.org/membership

![image](https://github.com/ublue-os/bluefin/assets/1264109/3b9e56da-ce29-4f35-99ca-ed339b700b17)
