### ISSUE TITLE
just is broken (error: The `!include` directive has been stabilized as `import`)

### ISSUE THREAD

**Issue by philcryer** [ublue-os/bluefin#783]
### Describe the bug

Using `just` version:

```
❯ just -V
just 1.21.0
```

I ran `just fleek-install` which completed successfully, then I followed the suggested steps to setup `fleek` by running `nix run "https://getfleek.dev/latest.tar.gz" -- init` followed by `nix run "https://getfleek.dev/latest.tar.gz" -- apply`, which also worked fine. However, after this, anytime I tried to run `just` I got the following error:

``` 
❯ just 
error: The `!include` directive has been stabilized as `import`
 ——▶ .justfile:1:1
  │
1 │ !include /usr/share/ublue-os/justfile
  │ ^
```

### What did you expect to happen?

I expected `just` to run successfully and give me the output of all the recipes it knew about.

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
Digest: sha256:3fc7ea66d1023ff577c3cdba5532aa92bbb5d58a6d91dea9e4afd3220e0a52d3
Version: 39.20240103.0 (2024-01-03T16:53:22Z)

ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
Digest: sha256:acb4579fd5778e7474d299e804cca6cb23018f2594e8e7bcc42c160e280527ee
Version: 39.20240102.0 (2024-01-03T00:19:42Z)

ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:gts
Digest: sha256:8cbc1c8b3c73eed6babd3526e2c12ca23c0c3a61bf488ee74c69196f0e58e586
Version: 38.20240102.0 (2024-01-03T00:17:27Z)
Pinned: yes
```

### Extra information or context

* I have tried `rpm-ostree rebase` to latest, 39, and 38, but the issue persists.
* I have modified my `~/.justfile` to use `import` instead of `!include`:

```shell
import '/usr/share/ublue-os/justfile'
```

While this got past the issue on that file it complains about the file it points to: `/usr/share/ublue-os/justfile` because it still uses the `!include` statement and not the `import` one. Since this part of the OS is read-only, I can't modify it.

```shell
❯ just
error: The `!include` directive has been stabilized as `import`
——▶ /usr/share/ublue-os/justfile:1:1
│
1 │ !include /usr/share/ublue-os/just/00-default.just
│ ^
```

**Comment by p5** [comment]
Thanks for raising this issue
This is an expected error, but should be resolved very soon.  Work has started fixing this [here](https://github.com/ublue-os/config/commit/de4e904989e7ef630a5f27ce37bd06dcad742f4c), and we are now running through and rebuilding all images

**Comment by castrojo** [comment]
Hi Phil, can you do an `rpm-ostree update`, reboot and give it a shot? This should be good now.

**Comment by philcryer** [comment]
Okay, I've done the `rpm-ostree update` and rebooted. Now I have:

```
❯ rpm-ostree status -b
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:5163b834b0743a5d72c5b798f03dbea9ef093baf68cc2857bd15030c61ab6fae
                  Version: 39.20240104.0 (2024-01-04T17:56:43Z)
```

My `~/.justfile` contains the correct `import`, and not the `!inlcude`, declaration:

```
❯ cat .justfile
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: .justfile
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ import "/usr/share/ublue-os/justfile"
───────┴─────────────────────────────────────────────────────────────────────────
```

However now `just` fails due to the pathing in the file `/usr/share/ublue-os/justfile`:

```
❯ just 
error: Could not find source file for import.
 ——▶ /usr/share/ublue-os/justfile:1:8
  │
1 │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
  │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It seems that the variables `$(basename ${justfile})` are not being expanded during runtime. The file `/usr/share/ublue-os/justfile` contains:

```
❯ cat /usr/share/ublue-os/justfile 
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: /usr/share/ublue-os/justfile
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   2   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   3   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   4   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   5   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   6   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   7   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
   8   │ import "/usr/share/ublue-os/just/$(basename ${justfile})"
───────┴─────────────────────────────────────────────────────────────────────────
```

Meanwhile the full directory `/usr/share/ublue-os/just/ contains:

```
❯ ls -al /usr/share/ublue-os/just/
total 44
drwxr-xr-x. 1 root root   224 Dec 31  1969 .
drwxr-xr-x. 1 root root   192 Dec 31  1969 ..
-rw-r--r--. 2 root root  2079 Dec 31  1969 00-default.just
-rw-r--r--. 4 root root  3391 Dec 31  1969 10-update.just
-rw-r--r--. 4 root root   285 Dec 31  1969 20-clean.just
-rw-r--r--. 4 root root  2573 Dec 31  1969 30-distrobox.just
-rw-r--r--. 4 root root  1879 Dec 31  1969 40-nvidia.just
-rw-r--r--. 4 root root  1065 Dec 31  1969 50-akmods.just
-rw-r--r--. 4 root root 12473 Dec 31  1969 60-custom.just
-rw-r--r--. 4 root root  3872 Dec 31  1969 70-nix.just
```

Since I think we want  `/usr/share/ublue-os/justfile` to point to those files, I did try hardcoding one of those paths in another `justfile` and pointing to that (without your variables `$(basename ${justfile})"` just to test it, but that fails: 

```
❯ cat justfile
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: justfile
───────┼─────────────────────────────────────────────────────────────────────────
   1   │ import "/usr/share/ublue-os/just/00-default.just"
───────┴─────────────────────────────────────────────────────────────────────────

~ 
❯ just -f justfile
error: Justfile contains no default recipe.
```

Not sure what to do next, I did chat with the developers of `just` in Discord, but since this is a specific issue to bluefin-dx, I wanted to work it here. Thanks for the help, happy to update and try again.

**Comment by castrojo** [comment]
Yeah this is for sure our issue where we're fixing up our justfiles due to the update. cc @ublue-os/approver

**Comment by castrojo** [comment]
Ok this should be set now and we've confirmed it with other people. One more update please. 😄  

Please reopen if there's another error, thanks! Here's the writeup: https://universal-blue.discourse.group/t/if-youre-having-problems-with-just-do-an-update/368

**Comment by philcryer** [comment]
This is fixed, thank you!
