### ISSUE TITLE
Missing icons in Prompt and Gnome Settings

### ISSUE THREAD

**Issue by andrewbaker-uk** [ublue-os/bluefin#784]
### Describe the bug

In certain places in the OS, I'm noticing that some icons are not appearing.

In below screenshot, new tab icon in Prompt is missing and the edit icon in Device Name in Gnome Settings is also missing

![image](https://github.com/ublue-os/bluefin/assets/10560135/b239d5db-44d3-4e5a-af18-0d7654798c30)

### What did you expect to happen?

Icons to correctly load

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: check; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:c2694ca8f5fce921551e4e5be066386f328367480f278d23e1af4b68389e00f1
                  Version: 39.20240104.0 (2024-01-04T17:53:07Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin:latest
                   Digest: sha256:0118861ce92a9b1b32eac0c7cf22f19009aa4f5d7eba3e4061854f943a54d096
                  Version: 39.20240104.0 (2024-01-04T16:48:30Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/kinoite-main:39
                   Digest: sha256:501c5edb50a72fe82b29f700be1a24c986207f0443c7b0456d06c2861fab64a1
                  Version: 39.20240104.0 (2024-01-04T15:07:25Z)
                   Pinned: yes
```

**Comment by andrewbaker-uk** [comment]
I've fixed the issue by creating a new user. I was originally running Fedora Kinoite and rebased to ublue-os/Kinoite-Main and then to bluefin.

**Comment by codegod100** [comment]
if you go into Tweaks and pick icon theme it should restore them in case anyone doesn't want to make a new user.
