### ISSUE TITLE
ublue-system-flatpak-manager uses the fedora repo instead of flathub

### ISSUE THREAD

**Issue by ispanos** [ublue-os/bluefin#788]
### Describe the bug

When someone populates the [flatpak/system/install](https://github.com/ublue-os/bluefin/blob/main/usr/etc/flatpak/system/install) list, flatpaks are installed using the fedora remote.

- [ublue-system-flatpak-manager](https://github.com/ispanos/bluefin/blob/main/usr/bin/ublue-system-flatpak-manager#L16) removes the fedora remote with `--user`
- L26 `flatpak install --system --noninteractive flathub ${INSTALL_LIST[@]}`
- L41 `flatpak remote-delete fedora --force`

The flathub remote is never installed, thus flatpaks are installed from the fedora remote. Then it gets removed, which disables updates for those packages.

### What did you expect to happen?

The expected behavior would either be to fail, since `flathub` is specified in [L26](https://github.com/ispanos/bluefin/blob/cb8951d332da3964f1a1d4d9244aaf9a84de16d5/usr/bin/ublue-system-flatpak-manager#L26) but it is not installed. This is probably a bug of the `flatpak install` command.

### Extra information or context

I can think of two solutions:

1. Install the flathub repo with `--system` and remove the fedora repo with `--system` before installing flatpaks.

  Unfortunately this causes all future flatpak installation to require `--user`, `--system` or user interaction for all installations in the terminal. If more that one remotes are installed, they need to be specified.

2. Switch to system-wide flatpak installations and install the flathub remote with `--user` only for non-wheel users, who I believe can't install flatpaks system-wide.

Installing the flathub remote, install the packages, and then remove the flathub remote will not fix the issue of not getting updates.

**Comment by castrojo** [comment]
Related: https://github.com/ublue-os/bluefin/issues/789

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/bluefin/pull/790
