### ISSUE TITLE
Consider switching to system flatpaks as default

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#789]
Mostly to match Bazzite so that if people rebase it doesn't turn into a mess. Originally I picked --user because that's what opensuse was doing and it made sense to me. Bazzite didn't really exist but people are running into this.

We need to sort this asap because if we're going to do it we should do it **before** the offline installer is done upstream. It's one PR away from being ready so we should decide.

**Comment by KyleGospo** [comment]
I'm using system as "flatpaks installed by the image", and leaving user for users to do whatever they please.

This should be fixable in bluefin by adding everything in install to uninstall, then adding them again to the system installer.

**Comment by ispanos** [comment]
System wide flatpaks save space in mutli-user systems. bluefin is replacing basic packages with their flatpak version and users can choose to add both user and system packages on their own.

If there are no special use-cases for --user flatpaks this change  will not break anything. Although there are downstream that my not like this change.

Maybe add the flathub remote to non-wheel users? Those who can't install packages system-wide will be ready to go.

**Comment by KyleGospo** [comment]
https://github.com/ublue-os/bluefin/pull/790
