### ISSUE TITLE
Just command reports error after bluefin update

### ISSUE THREAD

**Issue by doc-kildare** [ublue-os/bluefin#800]
### Describe the bug

Running "just" command by itself after bluefin-dx update results in following error. ❯ just
error: Justfile contains no default recipe.

### What did you expect to happen?

Expected to have a list of just options (this worked prior to update)

### Output of `rpm-ostree status`

```shell
❯ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:bfd2665257fdff0e5436a34f65aed4de03bd6ed6c512cc16dddb803cbbb12e7c
                  Version: 39.20240107.0 (2024-01-08T04:23:55Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:1c760c757dcff815b2b73c13b7c9e325a95981381c19d623b9061aab70919939
                  Version: 39.20231225.0 (2023-12-25T19:28:11Z)
```

### Extra information or context

My .justfile is default (not altered) and imports /usr/share/ublue-os/justfile
That file has an underscore just before the word default in the default recipe i.e. _default
Copying /usr/share/ublue-os/justfile to ~/.justfile and removing the offending underscore before default corrects the problem as a temporary workaround.

**Comment by castrojo** [comment]
Please see: https://universal-blue.discourse.group/t/if-youre-having-problems-with-just-do-an-update/368

`ujust` or `just -l` is the workaround, but might be the command moving forward.
