### ISSUE TITLE
[Bug] the nix installer fails because it is a read only system

### ISSUE THREAD

**Issue by dnkmmr69420** [ublue-os/bluefin#83]
Error: 
   0: Install failure
   1: Error executing action `configure_nix`
   2: Child action `configure_shell_profile`
   3: Child action `create_or_insert_into_file`
   4: Open path `/usr/share/fish/vendor_conf.d/nix-installer-tmp.4025512441`
   5: Read-only file system (os error 30)

I got this error

**Comment by dnkmmr69420** [comment]
This also has been tested on the ublue silverblue version but I don't think that will create a difference

**Comment by castrojo** [comment]
I can confirm this behavior on a clean VM, same error.

**Comment by bketelsen** [comment]
fixed by #87

**Comment by bketelsen** [comment]
for the record, I confirmed this on a clean install - worked great.
