### ISSUE TITLE
Ship newer fontconfig

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#830]
Kyle says we probably need this.

https://github.com/ublue-os/bazzite/commit/844f14abf235183b3f142efb2e38ebc000b89b02

**Comment by fiftydinar** [comment]
tn on Discord says that it's actually a distrobox problem, not the flatpak one.
Flatpak stores it's fontcache separately from the system one in app data.

Here's the issue he linked which relates to this:
https://github.com/89luca89/distrobox/issues/358
