### ISSUE TITLE
LibreOffice doesn't respect Dark Mode except for icons

### ISSUE THREAD

**Issue by Libretto7** [ublue-os/bluefin#834]
### Describe the bug

Fresh bluefin-dx install. Chose LibreOffice at the welcome wizard. Enabled GNOME dark mode. Opened LibreOffice apps, but all of them are light. Icons are also light so it looks broken.

![Screenshot from 2024-01-26 13-09-13](https://github.com/ublue-os/bluefin/assets/143698706/d341408e-698f-4c78-9ae8-219f99ff1a7f)

### What did you expect to happen?

Dark LibreOffice apps with matching icons

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1h 45min ago
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:b63ee00bb13ed24423bf4ea942d80793c9ef68815653ab897183738140747210
                  Version: 39.20240125.0 (2024-01-25T16:53:47Z)

  ostree-unverified-image:docker://ghcr.io/ublue-os/bluefin-dx:latest
                   Digest: sha256:b63ee00bb13ed24423bf4ea942d80793c9ef68815653ab897183738140747210
                  Version: 39.20240125.0 (2024-01-25T16:53:47Z)
```

### Extra information or context

In light mode the icons are normal.
Silverblue does not have this bug.

**Comment by m2Giles** [comment]
Please change your GTK Theme using Gnome Tweaks to something like Adwaita or adw3-gtk and make the sure the corresponding version is installed in flatpak.

It appears that flatpak did not install a corresponding dark theme automatically for you using the default Yaru-blue theme.

**Comment by Libretto7** [comment]
Yes, setting the theme for legacy applications to Adwaita fixes this (without installing anything). So it seems like yaru-blue simply doesn't provide a dark theme for LibreOffice.
