### ISSUE TITLE
Add devcontainers-cli

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#843]
We should have this on the host: 

https://github.com/devcontainers/cli

So that people can use emacs and others for devcontainers: https://happihacking.com/blog/posts/2023/dev-containers-emacs/

**Comment by m2Giles** [comment]
I'm trying to see what `devcontainers-cli` provides that `devpod` doesn't already.

While emacs cannot use ssh tramp for `devpod` they can still use docker tramp to access the containers the same way.

**Comment by castrojo** [comment]
My main line of reasoning is the tutorials for devcontainers upstream
mention this tool and have tutorials around it and it's also the reference
implementation.

**Comment by castrojo** [comment]
There's an entry in vscode that tosses it into .local/bin, good enough!

![image](https://github.com/ublue-os/bluefin/assets/1264109/8639b768-41e5-4e89-84a1-15cd6517fa4e)
