### ISSUE TITLE
Make Microsoft Teams for Linux (Electron) selectable as a chat client option

### ISSUE THREAD

**Issue by dylanmtaylor** [ublue-os/bluefin#890]
### Describe the package

I'd like to be able to install Teams with one click, just like Slack.

https://flathub.org/apps/com.github.IsmaelMartinez.teams_for_linux

### Image

All Images

**Comment by castrojo** [comment]
I've tried this app and just about all the others and none of them are as reliable as a browser/PWA. 

When we get a PWA solution we'll for sure add this in the initial install wizard though!

**Comment by dylanmtaylor** [comment]
> I've tried this app and just about all the others and none of them are as reliable as a browser/PWA.
> 
> When we get a PWA solution we'll for sure add this in the initial install wizard though!

This uses Chromium/Electron so should be indistinguishable from the PWA functionality-wise. How would it work with a PWA solution? Would an opinionated choice be made on what browser to launch it in or something?
