### ISSUE TITLE
DevPod container won't connect to VSCode.

### ISSUE THREAD

**Issue by dylanmtaylor** [ublue-os/bluefin#892]
### Describe the bug

When using DevPod, I can't use the non-browser version of VS code.

### What did you expect to happen?

The container should connect from VS code.

**Comment by m2Giles** [comment]
How are you attempting to connect to the Devpod?

**Comment by dylanmtaylor** [comment]
> How are you attempting to connect to the Devpod?

Container running in docker using the docker provider. The VS code interface opens and fails to connect to the docker container running locally.

**Comment by m2Giles** [comment]
Are you able to SSH to the Devpod?

**Comment by dylanmtaylor** [comment]
I don't think SSH is forwarded on the container. The error I get in VS code is "Could not establish connection to "vscode-remote-try-python.devpod": spawn ENAMETOOLONG."

**Comment by m2Giles** [comment]
Please refer to Devpod's documentation on connecting to a Devpod.

The default method to connect to the containers are via the remote ssh extension in VSCode and using ssh from the cmdline.

**Comment by FelipeCabelloE** [comment]
Hello,

Just wanted to add that I have the same problem on bluefin-dx-nvidia

**Comment by Arham4** [comment]
For me to resolve it:
1. Go on a VSCode instance that isn't in a container.
2. Go to Remote Explorer, make sure it is in Dev Containers mode. 
    - If there is nothing shown, and it says to install docker:
        1. Do `systemctl restart docker` in the terminal.
        2. Reload VSCode. 
        3. The DevPod instance will then show. 
3. Right click the container, click `Remove Container` 
4. Attempt to open the container again in DevPod. 

This then allows me to start the DevPod instance successfully again.

It would be really nice to not have to do this though, but this is how I get it working without sacrificing my source files.

**Comment by m2Giles** [comment]
There was some upstream work on this in DevPod repo.

We should get a fix for some observed issues

**Comment by Arham4** [comment]
Do you know where we could track this work?

**Comment by m2Giles** [comment]
https://github.com/loft-sh/devpod/issues
