### ISSUE TITLE
GNOME Boxes

### ISSUE THREAD

**Issue by dylanmtaylor** [ublue-os/bluefin#893]
### Describe the package

I'd like to request GNOME boxes, as it is visually and functionally more integrated into the desktop than the virtual machine manager that is available.

### Image

All Images

**Comment by m2Giles** [comment]
Gnome boxes is available as a flatpak.

**Comment by dylanmtaylor** [comment]
> Gnome boxes is available as a flatpak.

That's fair. It has such good UX for virtualization, I think it ought to be one of the out-of-the box suggestions.

**Comment by castrojo** [comment]
Yeah and since we use VMs to test bluefin itself we're kind of stuck with virt-manager since we need the advanced features.
