### ISSUE TITLE
Display Link

### ISSUE THREAD

**Issue by perfectdarkmode1** [ublue-os/bluefin#913]
### Describe the package

I'd like to request the package `Display Link' because I have a Docking station that needs it. 

### Image

Bluefin

**Comment by m2Giles** [comment]
We already have evdi. Does it not work with your dock?

**Comment by perfectdarkmode1** [comment]
I actually rebased to Bazzite, which has display link, and that did not work either. I may just try and get a usb-c dock. This one is only usb-a
