### ISSUE TITLE
Fingerprint not working after enrolling in GNOME settings

### ISSUE THREAD

**Issue by dylanmtaylor** [ublue-os/bluefin#919]
### Describe the bug

I enrolled my fingerprint in GNOME settings but it wasn't available as a method to unlock my laptop on the lock screen

### What did you expect to happen?

Prompt for fingerprint

### Output of `rpm-ostree status`

```shell
$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 19h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:b71f99a7612b62fe5b26f3447f53aafed853ffec308c157e95bd2b20fced4099
                  Version: 39.20240221.0 (2024-02-21T16:54:33Z)
                     Diff: 26 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:593e9a5a5c60c106321be70543b2d8744ef742025942dbb420347f6c89d5e66a
                  Version: 39.20240220.0 (2024-02-20T16:51:51Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:latest
                   Digest: sha256:c17efa48924bacbdd0ecee9292ebe9f5ea8d44b9b133639d8166f5615c13ab4c
                  Version: 39.20240219.0 (2024-02-19T16:52:47Z)
```

### Extra information or context

This fixed it:

❯ sudo authselect enable-feature with-fingerprint
Make sure that SSSD service is configured and enabled. See SSSD documentation for more information.
 
with-fingerprint is selected, make sure fprintd service is configured and enabled

❯ sudo authselect apply-changes
Changes were successfully applied.

**Comment by bsherman** [comment]
It would be really great if you could verify if this an upstream (Fedora Silverblue) bug vs Bluefin/Universal Blue. 

This is the kind of thing we would try to fix if we caused it but I would guess is actually an upstream issue. 

Reinstalling one's system is a big deal, but maybe do a test install on an external drive?
