### ISSUE TITLE
"Open Ptyxis Here" in file browser does not open at the correct location in Ptyxis

### ISSUE THREAD

**Issue by tepene** [ublue-os/bluefin#921]
### Describe the bug

In the file browser, my example under `$HOME/Downloads/TEST`, I click on the "..." menu and select "Open Ptyxis Here". Ptyxis opens up but at the wrong location. For met at `$HOME`

![image](https://github.com/ublue-os/bluefin/assets/54766327/66cfdfd0-db0d-42e2-a101-83fc72f150f6)

![image](https://github.com/ublue-os/bluefin/assets/54766327/c03b143a-da59-4e73-9f33-9d79aecb73fa)

### What did you expect to happen?

Ptyxis should have opened in the folder which was selected in my file browser.

### Output of `rpm-ostree status`

```shell
📦 $ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 9h ago
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:39
                   Digest: sha256:4cd8793c7bb65a207f6c874c6dbbdf5afa06504b1c55a942826f3c374f0fb9ac
                  Version: 39.20240221.0 (2024-02-22T03:19:08Z)
                     Diff: 5 upgraded, 2 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:39
                   Digest: sha256:05dc721cb6edb0224db801b5f40d0ce718fdd7b5055600bfe94213d07007ab1e
                  Version: 39.20240221.0 (2024-02-21T17:03:19Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx:39
                   Digest: sha256:6f6e3f6a05a189d419db1b72477e41b99ef7bc670e6cc9e0541fee4c498ba344
                  Version: 39.20240220.0 (2024-02-20T16:51:00Z)
```

### Extra information or context

this feature did work when **ptyxis** was called **prompt**. Might be related to https://github.com/ublue-os/bluefin/pull/916

**Comment by castrojo** [comment]
I can reproduce this on a fresh install.

**Comment by tepene** [comment]
I did some more testing. I found out that the feature works when i set "host" profile as my default

![image](https://github.com/ublue-os/bluefin/assets/54766327/032e2952-a348-43c1-a2c6-a06289d9f7fe)

When i set the "bluefin-cli" as default the "open here.." does not work
