### ISSUE TITLE
Add magic-wormhole-rs and netcat

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/bluefin#945]
### Describe the package

I'd like bluefin or bluefin-dx to have these packages by default because:

## Netcat

Allows the user to connect to a virtual machine through `virsh` without having a network connection by using the libvirt ssh socket. E.g. `virsh -c qemu+ssh://tulili@my-machine/system`

## Magic-Wormhole{-rs}

A very convenient way to share files without needing something like SSH, SCP, or SFTP, that might help out in use cases where the user has two Bluefin machines in a LAN network and wants to share files, that also would help out by making it easier to share files with a virtual machine.

### Image

Ubuntu

**Comment by bketelsen** [comment]
both of these are available in Homebrew. So they're available already to use :)

**Comment by tulilirockz** [comment]
Sweet! Didnt know that :>
