### ISSUE TITLE
ctrl-alt-f doesn't open a fedora terminal

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#971]
It opens an ubuntu one instead. The ubuntu one works fine.

**Comment by castrojo** [comment]
From Jonas: 

https://universal-blue.discourse.group/t/ptyxis-new-window-installs-ubuntu-toolbox-if-bluefin-cli-is-not-available/771/3?u=j0rge

**Comment by m2Giles** [comment]
https://github.com/ublue-os/bluefin/pull/1164

**Comment by m2Giles** [comment]
Users may have to update their key bindings but out of the box this is now fixed.

This is now also working on Aurora
