### ISSUE TITLE
/etc/profile.d/brew.sh won't overwrite on update

### ISSUE THREAD

**Issue by bketelsen** [ublue-os/bluefin#983]
### Describe the bug

brew.sh doesn't update

### What did you expect to happen?

it should

### Extra information or context

we need to add it to the ujust brew task to replace /etc/profile.d/brew.sh

**Comment by bronson** [comment]
Probably also add a warning inside the file: ### DO NOT EDIT, WILL BE REPLACED

**Comment by p5** [comment]
Would it work if we moved the script to /usr and symlinked the script to profile.d?

**Comment by bketelsen** [comment]
good question

**Comment by bronson** [comment]
Huh! Symlinking from /usr seems like it solves everything: 

- automatically updates
- doesn't silently throw away user changes
- file contents are immutable
- user can override if they really want

One question: what do you do when it's time to delete the file? Easiest thing would be to empty the file (0 lengnth) and leave the link in /etc untouched. But that's crufty. Probably still need a script to clean up.

Other than that, this seems like a solid idea.

**Comment by m2Giles** [comment]
Symlink would be the best bet.

I currently extend the brew stuff in my home directory to make sure bash completion is working. Need to get that stuff added to brew.sh as well.

**Comment by m2Giles** [comment]
Seeing the just command do a force overwrite of the file. We should do a symlink.

If there is a symlink it's still managed by system, if a file we can prompt to remove for the symlink or have it remain in place.

Symlink means we can update the file and not worry if the file in /etc is getting properly updated.

I think a lot of our customizations could move to this method.
