### ISSUE TITLE
Write Tests for Building ISOs

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/bluefin#986]
I would like tests before a new version of the build_iso.yml workflow is merged. This is similar to the testing we do in the actual isogenerator action. (do not have it upload to R2, have it upload as an artifact so we can review the ISO it created) 

There should be no reason we are building all the container images when we are updating the build_iso.yml workflow as they exist independently of each other

**Comment by p5** [comment]
> There should be no reason we are building all the container images when we are updating the build_iso.yml workflow as they exist independently of each other

I'm not too sure how we will do this.  The container builds are required checks of the repo, so we can't really skip them.

**Comment by noelmiller** [comment]
I think we can have it ignore the check for certain files? You would want to consult @castrojo on that. I think @KyleGospo does it in the Bazzite repo.

**Comment by castrojo** [comment]
Yeah, we can add the ignore later? Does it matter if it's kicking off builds?
