### ISSUE TITLE
ujust brew-fleek still broken

### ISSUE THREAD

**Issue by bketelsen** [ublue-os/bluefin#995]
### Describe the bug

running ujust brew-fleek reports errors

### What did you expect to happen?

should install fleek configs

**Comment by bketelsen** [comment]
script needs to be run from $HOME

**Comment by bketelsen** [comment]
but that's not enough to fix it :(

**Comment by bketelsen** [comment]
just may be executing in a strange working dir.
`tar: .fleek: Cannot mkdir: Read-only file system
`
command runs fine outside of just.  Strange

**Comment by castrojo** [comment]
I ran the command today and fleek installed successfully without errors. ? ?

**Comment by citrixscu** [comment]
Confirmed successful install by running command directly

**Comment by bketelsen** [comment]
fixed this in fleekbrewgen directly by issuing a `cd $HOME` before doing tar operations.
