### ISSUE TITLE
fleekbrew should match bluefin-cli's packages

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#996]
It'd be nice for `high` to match bluefin-cli since it's pretty awesome. Here's the packagelist: https://github.com/ublue-os/toolboxes/blob/main/toolboxes/bluefin-cli/packages.bluefin-cli

Since this is on the host I think was can make it smaller, we don't need to snag starship, git, etc. with brew. We'll need to do the rust uutils and the customization scripts are all in the repo.

**Comment by bketelsen** [comment]
fleekbrew is actually a go app that assembles the configs real-time for the user
we should just make it a set of configs in /usr/share/ublue-os and move them into place in the justfile

**Comment by dnkmmr69420** [comment]
where can I get fleekbrew?

**Comment by citrixscu** [comment]
> where can I get fleekbrew?

https://getfleek.dev/docs/homebrew

**Comment by m2Giles** [comment]
#1293 includes a brewfile with bluefin-cli packages.
