### ISSUE TITLE
Ensure framework hwe gets moved to bluefin

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#998]
Framework repo/image is going away, we need to remember to bring the kargs over here. Power management will just be `tuned` so no need to move anything over.

**Comment by jbethune** [comment]
> Framework repo/image is going away,

That means Fedora Silverblue will no longer provide it? Or where is it going away from?

**Comment by castrojo** [comment]
This is the repo we're closing: https://github.com/ublue-os/framework

Instead we'll support the Framework right in the bluefin repo so you won't
need a special -framework image.

**Comment by castrojo** [comment]
Kyle's going to do a kmod so people can bazzite on their frameworks also. Leave this open until we load the kmod in the containerfile.

**Comment by lazypower** [comment]
I was asked to drop a `dmidecode` output of my AMD framework 13 here. To keep issue spam down I've placed it in a gist for easier perusal

https://gist.github.com/lazypower/125d4514c778ccd4204848fd8bb7660b

**Comment by castrojo** [comment]
Here's the intel 13 dmidecode:

https://gist.github.com/castrojo/ecfe260b2e6e84ae848fe1d8aeb03191

**Comment by corndog2000** [comment]
Here it is for my Framework 16 with the Ryzen 7940HS.

[https://gist.github.com/corndog2000/9bb2769c60952344691d381b551ffb4d](https://gist.github.com/corndog2000/9bb2769c60952344691d381b551ffb4d)

**Comment by castrojo** [comment]
Most of this is landed and Kyle has the hardware now so let's close this and do one-issue-per-bug for the minutia.
