### ISSUE TITLE
Remove flatpak user remote

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#999]
We should remove the user remote so this dropdown makes sense: 

![image](https://github.com/ublue-os/bluefin/assets/1264109/75165323-2980-45a3-af6c-76f6ddb8d432)

**Comment by fiftydinar** [comment]
> We should remove the user remote so this dropdown makes sense

This would require removing or disabling flathub user remote, as I tried to set "user" remote only in my image some time ago in dconf/gsettings & it didn't work.

But this should be tested, as I tried it long time ago.

**Comment by KyleGospo** [comment]
This will break updates for anyone who's installed a user level flatpak

**Comment by castrojo** [comment]
Could we make it so it's not in the default installation? People adding them afterward is fine, just trying to not have double repos ootb.

**Comment by fiftydinar** [comment]
This below is a workaround & not a solution.

I generally prefer to use system-level flatpaks for system (Bluefin) & user-level flatpaks for the user.
Default preferred flatpak choice in Gnome Software would be in a user remote, while system remote would be a 2nd option, if some app needs it (very rare, but I know that GPU Screen Recorder requires that).

This makes separation & management between Bluefin & user flatpaks much better.
It also allows the user to use some flatpak which Bluefin removed from user remote.

**Comment by KyleGospo** [comment]
> Could we make it so it's not in the default installation? People adding them afterward is fine, just trying to not have double repos ootb. 

Remotes have a priority option, but as far as I can tell gnome software completely ignores it.

**Comment by fiftydinar** [comment]
> Remotes have a priority option, but as far as I can tell gnome software completely ignores it.

They are not ignored in my case (I have user remote prioritized 1st in my image).
Maybe this issue was fixed in the meantime?

**Comment by KyleGospo** [comment]
>  > Remotes have a priority option, but as far as I can tell gnome software completely ignores it.
> 
> They are not ignored in my case (I have user remote prioritized 1st in my image).
> Maybe this issue was fixed in the meantime?

How are you setting that?
https://github.com/ublue-os/bluefin/blob/main/usr%2Flibexec%2Fublue-user-flatpak-manager#L31

**Comment by fiftydinar** [comment]
> How are you setting that? https://github.com/ublue-os/bluefin/blob/main/usr%2Flibexec%2Fublue-user-flatpak-manager#L31

Through dconf/gsettings:
https://github.com/fiftydinar/gidro-os/blob/main/config/gschema-overrides/zz1-gidro.gschema.override#L70

**Comment by castrojo** [comment]
I saw a video on zorin os and they only have one item in the dropdown.

**Comment by m2Giles** [comment]
We've switched over to system by default.

Only users that had installed user flatpaks should have the user repo still enabled.
